### ISSUE TITLE
Error while using CVODES from AMICI

### ISSUE THREAD

**Issue by dlekshmi** [ICB-DCM/AMICI#100]
Hi 

I was playing around with the toolbox as a part of my analysis, and found this error... In my model, I pass in  initial sensitivities at t=0 i.e through option ami.sx0. When I do so, I get the following error:

> Error using bsxfun
> Non-singleton dimensions of the two input arrays must match each other.

in the line inside the simulate_model.m file: 
    `init.sx0 = bsxfun(@times,options_ami.sx0,1./permute(chainRuleFactor,[2,1]));`

I guess it has to be changed to [1,2] rather than [2,1]. 

Kindly confirm.
Thanks a lot.

**Comment by FFroehlich** [comment]
Hi,

Short answer: yes!

Long answer: As far as I can tell the dimensions of chainRuleFactor depend on the dimension of theta, which should not be the case. So if you pass theta as [np,1] matrix everything will be fine, but for a [1,np] matrix the code will fail. So a better way to fix this is by replacing chainRuleFactor by chainRuleFactor(:) in the line you quoted. I will apply the corresponding changes. In the meantime you can change line 352 of generateM to permanently fix the generation of the simulation routine.

Thanks for letting us know.

Best,
Fabian
