### ISSUE TITLE
Version control c++ & python

### ISSUE THREAD

**Issue by mhhoog** [ICB-DCM/AMICI#1004]
After trying to install amici on Windows8 I switched to Ubuntu. Here I've tried to install amici again using Ubuntu 18.04.3 LTS and Python 3.8 (and tried 3.7.4 additionally)

However the `pip install amici` results in.
```
`cannot find -lcblas
Collect2: error: ld returned 1 exit status
Error: command 'g++' failed with exit status 1`
```

To eliminate errors occuring by using non supported versions I was wondering which versions are currently used in the development?

Thank you in advance!

**Comment by dweindl** [comment]
Hi @mhhoog , amici requires some CBLAS-compatible library and header files. On Ubuntu you can install that using `sudo apt install libatlas-base-dev`. Then retry `pip install amici`.

If not done already, you additionally need to install SWIG (https://github.com/ICB-DCM/AMICI/blob/master/INSTALL.md#swig).

This will apply to all AMICI versions. Development version is here on the `develop` branch. There is no development version on pypi.

For CBLAS, there is no specific version requirement.

**Comment by mhhoog** [comment]
Thank you very much, that worked!
