### ISSUE TITLE
Assessment of model properties

### ISSUE THREAD

**Issue by JanHasenauer** [ICB-DCM/AMICI#101]
AMICI should provide routines for evaluating the consistency of the model and additional functionality, e.g.

- [ ]  Evaluation for ensuring positivity of the state variable, i.e. all processes resulting in a consumption of x_i should be multiples with the x_i: dx_i/dt = - g(x)*x_i + h(x) with positive functions g(x) and h(x).

- [ ]  Extraction of conserved moiety.

- [ ]  Some basic functionality for the visualisation of simulations.

**Comment by FFroehlich** [comment]
AMICI is a dynamic simulation toolbox. I would recommend creating a seperate toolbox for static model analysis.
