### ISSUE TITLE
problem with -mici (0.10.17)

### ISSUE THREAD

**Issue by thomassligon** [ICB-DCM/AMICI#1016]
I upgraded from amici 0.10.17 to 0.10.20. Afterwards, my packet manager shows
```
-mici (0.10.17)
amici (0.10.20)
```
I tried to uninstall -mici, but get an error
`no such option: -m`

When I just try to use what I have, I get an error in
`import amici`

```
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\amici\__init__.py", line 88, in <module>
    from . import amici
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\amici\amici.py", line 24, in <module>
    from . import _amici
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by dweindl** [comment]
No idea what happened there, but may deleting everything sounds like *mici in C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\ and reinstalling amici will do the job.

**Comment by thomassligon** [comment]
Well, *mici doesn't work, but I found a comment at
[(https://stackoverflow.com/questions/60541468/pip-uninstall-odd-package-whose-name-starts-with)](https://stackoverflow.com/questions/60541468/pip-uninstall-odd-package-whose-name-starts-with)
which says I need to delete the files under site-packages. That worked, and in python, I ran `pip install amici`, and now only amici 0.10.20 shows up.
But, the import error is still occurring. I can see
`from . import _amici`
on line 24 of amici.py, but I don't understand where _amici can be found.

Just in case it helps, I updated my cloned copy of AMICI and ran `python setup.py sdist` but only got `amici-0.10.17.tar.gz`, no 0.10.20.

**Comment by dweindl** [comment]
> but I don't understand where _amici can be found.

That is the compiled swig interface. This is a binary shared object, not a python module. 

If you clone 0.10.20, there is no way you get amici-0.10.17.tar.gz. Maybe you that is an old file, what does the timestamp say? If no further options are provided, the new file will be created in `dist/`

@thomassligon : Is this still an issue or meanwhile resolved?

**Comment by thomassligon** [comment]
Today, I totally deleted the AMICI clone. I can get a new version later if I need it. Then I uninstalled amici in python and reinstalled it. The output shows that it ran setup.py and used the correct version of the tar file, so 0.10.20 is installed. Then I tried to run
```
import pypesto
import amici
import petab
```
but `import amici` failed with the following output:

```
Loaded '__main__'
Loaded 'runpy'
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\ptvsd_launcher.py", line 119, in <module>
    vspd.debug(filename, port_num, debug_id, debug_options, run_as)
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\debugger.py", line 39, in debug
    run()
  File "c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core\Packages\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\data\Tom\Research\Asthma\python\PE.py", line 2, in <module>
    import amici
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\amici\__init__.py", line 120, in <module>
    raise e
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\amici\__init__.py", line 88, in <module>
    from . import amici
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\amici\amici.py", line 24, in <module>
    from . import _amici
ImportError: DLL load failed: The specified module could not be found.
The thread 'MainThread' (0x1) has exited with code 0 (0x0).
```
Could it be that the import statements need to be called in a different order?

**Comment by dweindl** [comment]
Hi Tom, can you show the output of the verbose installation (`--verbose`) and show the contents of `C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\`?

**Comment by thomassligon** [comment]
Hi Daniel,
I ran pip install amici --verbose and captured the output (2460 lines).
Then I navigated to site-packages and ran dir and dir am* /S (376 lines).
What is the best way for me to show the content of these files?

**Comment by dweindl** [comment]
>  What is the best way for me to show the content of these files?

Attach to the post here. Click " Attach files by dragging & dropping, selecting or pasting them. " at the bottom of the comment box.

E-Mail received.

Installer says 
>     copying build\lib.win-amd64-3.7\amici\_amici.cp37-win_amd64.pyd -> c:\program files (x86)\microsoft visual studio\shared\python37_64\Lib\site-packages\amici

but this is not present in your directory listing. Not quite sure what is going wrong there.

**Comment by thomassligon** [comment]
[Out-2020-03-30.txt](https://github.com/ICB-DCM/AMICI/files/4407807/Out-2020-03-30.txt)
[Dir-2020-03-30.txt](https://github.com/ICB-DCM/AMICI/files/4407808/Dir-2020-03-30.txt)
Here are the documents.

**Comment by thomassligon** [comment]
Hi Daniel,
just to see if you have any more ideas about what I could test, here is a summary of what I recently tried. I upgraded from AMICI 0.10.20 to 0.10.21 and installed everything on a different PC, then also tested `python PE.py` in the command prompt (without Visual Studio). Searching the Internet for this error, I found some that fixed it by adding something to the PATH environment variable. My PATH looks OK, and worked before, but it might be worth noting that the path for site-packages includes spaces. However, python import finds other things there, by using quotes. I also searched the out file for swig, error, and warning, but couldn't find any issues.
Here are some questions that might help us find ideas:
Why does import for `pypesto `and `petab `work, but not for `amici`?
Why does `import amici `work, but not `from . import _amici`? Could it be that that special one has problems with spaces in the path?
Why did it work in AMICI 0.10.17 but fail in 0.10.20?

**Comment by thomassligon** [comment]
This problem looks much different today. I have re-installed amici multiple times, etc., and I no longer get an error in `from . import _amici`. In fact, I get an error on `import amici`.
The error is `DLL load failed: The specified module could not be found.`
I am closing this issue because the title of it is no longer helpful for the current problem.
