### ISSUE TITLE
fill_in_parameters_for_condition requires requires multiple values that could be optional

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#1019]
fill_in_parameters_for_condition makes a whole lot of stuff mandatory that was previously optional in `pypesto.AmiciObjective` (I hope everybody sees the irony of posting a `pypesto` issue which is about `petab` in `amici` ...).

1. `condition_map_preeq_fix`, `condition_map_sim_fix` and `condition_map_sim_var` are all mandatory due to the processing with `_get_par`. This means https://github.com/ICB-DCM/AMICI/blob/f92127899b2e7ad64d2b6149b7331afc2348a026/python/amici/petab_objective.py#L616 will always be true.

2. `petab_to_amici_scale` and `condition_map_sim_var` are both mandatory due to indexing over `model.getParameterIds()`

3. `condition_scale_map_preeq_fix` and `condition_scale_map_sim_fix` should only be necessary if `scaled_parameters` is True (currently true), or if `condition_map_preeq_fix` and `condition_map_sim_fix` are provided respectively.

In all 6 cases appropriate checks for `is None` or `len(...)` would allow not specifying those values. I am aware that all of these values are always given in petab, but specifying all of those fields in pure pypesto is pretty cumbersome (and I think we decided to not have petab define the pypesto API)

**Comment by FFroehlich** [comment]
Previously I was able to pass

```
parameter_mapping = [
                model.getParameterIds()
                for _ in edatas
]
```

to `pypesto.objective.AmiciObjective`, which now exploded to

```
parameter_mapping = [
                (
                    dict(zip(model.getFixedParameterIds(),
                             edata.fixedParameters)),
                    dict(zip(model.getFixedParameterIds(),
                             edata.fixedParametersPreequilibration)),
                    dict(zip(model.getParameterIds(),
                             model.getParameterIds())),
                    {
                        par_id: 'lin'
                        for par_id in model.getFixedParameterIds()
                    },
                    {
                        par_id: 'lin'
                        for par_id in model.getFixedParameterIds()
                    },
                    {
                        par_id: amici.petab_objective.amici_to_petab_scale(
                            par_scale)
                        for par_id, par_scale in zip(model.getParameterIds(),
                                                     model.getParameterScale())
                    }
                )
                for edata in edatas
]
```

ideally this could be reduced to, e.g.,

```
parameter_mapping = [
                (
                    None,
                    None,
                    dict(zip(model.getParameterIds(),
                             model.getParameterIds())),
                    None,
                    None,
                    None,
                )
                for _ in edatas
]
```

(the mapping is non-trivial here since this a multi-model setup where every model needs to be provided with the right set of parameters)

**Comment by yannikschaelte** [comment]
Hi @FFroehlich . I addressed your correct requests regarding the parameter mapping to require too many optional inputs. We had actually planned to make this more accessible, but I was happy that all mappings were working again in the first place. See changes in the feature_parameter_mapping  branches [here](https://github.com/ICB-DCM/AMICI/pull/1020) and in [pypesto](https://github.com/ICB-DCM/pyPESTO/pull/247). This should

* allow to specify only specific mappings, with the others basically set to empty mappings, or linear scales
* address all your points above
* effectively only make map_sim_var necessary in fill_in_parameters (unless there are only fixed parameters, thus None is also allowed in ParameterMappingForCondition), but I think that makes sense to always require that this dict fits with mode.getParameterIds().

If this is not ideal yet (I only use AMICI with PEtab, so it's hard for me to image your use case), please edit and let me know.
