### ISSUE TITLE
Use of uninitialized variable in spline.cpp

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#102]
`i` is used uninitialized and funny things are done with it. This should be fixed.
In https://github.com/ICB-DCM/AMICI/blob/master/src/spline.cpp#L274

Same here: https://github.com/ICB-DCM/AMICI/blob/master/src/spline.cpp#L326

**Comment by paulstapor** [comment]
true enough, but to the best of my knowledge, the function deriv() is never used in the AMICI routines... ;)

**Comment by dweindl** [comment]
Then let's better get rid of it before that changes...

**Comment by paulstapor** [comment]
Should be a good idea. From what I've seen, the Amici-routine only need spline and seval() in spline.cpp. There, we fixed the problem of uninitialized values, since it caused trouble... For the other, I didn't take the effort of checking the routines in detail,since they weren't used...
