### ISSUE TITLE
ModelState

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#1035]
to fix issues in https://github.com/ICB-DCM/AMICI/pull/1002 I want to introduce a ModelState class which will implement the following Model members:

- h
- total_cl
- stotal_cl
- originalParameters
- fixedParameters

and add the following members:

- t
- x
- dx
- sx
- sdx

this makes it a bit easier to carbon copy values of all variables that are necessary for calling of any model functions (which is necessary when evaluating Model functions externally). My current idea would be to implement this as class with pretty liberal public API to avoid introduction of redundant getter/setter functions. Model then gets a ModelState member on which Model getter/setter functions directly operate but also a state getter/setter function that can be used in conjunction with a new `SimulationContext` class to transiently replace the state class.

I prefer this implementation over Model inheriting from ModelState as transient replacement in `SimulationContext` only involves one getter/setter call. This also means we don't need to add getter/setters for `h`, `total_cl`, `stotal_cl`, etc, which also makes extension and maintenance easier.

Opinions?

**Comment by dweindl** [comment]
Sounds good to me

> My current idea would be to implement this as class with pretty liberal public API to avoid introduction of redundant getter/setter functions

Maybe directly go for a (data-only) `struct` then?
