### ISSUE TITLE
memory allocation overhead in am_spline*

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#104]
The am_spline* functions allocate memory on every function call. I believe this is the key reason why calling these functions is quite slow (problematic for the jakstat example which we use quite often). 

`num` can vary from function call to function call but the maximum `maxnum` is constant for every model and can be extracted at compile time. The arrays `ts` `us` `sus` `sus1` `sus2` `uslog` and `ps` should be allocated dynamically at size `maxnum` once for every simulation.

**Comment by paulstapor** [comment]
What would be a good work around? Allocating memory for this in, say, setupAMI and rewriting the spline-calls in the cpp-files to use pointers?

**Comment by dweindl** [comment]
This is all cheap stack memory. I don't see an issue there.

**Comment by FFroehlich** [comment]
these functions are called very often. allocations/deallocations  for ~23% (15.4% in qBdot  + 4.9% in xBdot  + 1.9% in xdot = ~23%) of the complete computation time in the jakstat example: https://imgur.com/a/108hf

**Comment by dweindl** [comment]
Hm... where does the `new` come from??

**Comment by FFroehlich** [comment]
was performed on https://github.com/ICB-DCM/AMICI/tree/fixes_ff previously the allocations did show up as seperate functions calls but where attributed to the parent functions.

**Comment by dweindl** [comment]
Ah :relieved: . And with heap memory it becomes faster? That sounds weird.

**Comment by FFroehlich** [comment]
no the change from double[num] to new double[num]() was just to fix MSVS being picky about array intitialisation. The idea would be to add these arrays to userdata and allocate them in processUserData.

**Comment by dweindl** [comment]
What was the MSVS issue exactly? I think the way it was originally was the cleanest.

**Comment by FFroehlich** [comment]
`
...\src\symbolic_functions.cpp(306) : error C2057: expected constant expression
...\src\symbolic_functions.cpp(306) : error C2466: cannot allocate an array of constant size 0
...\src\symbolic_functions.cpp(306) : error C2133: 'ts' : unknown size
`

the problem already existed before but could not be pinpointed to allocation/deallocation as no respective calls appeared in the call stack

**Comment by dweindl** [comment]
Ah, I did not know that MSVS does not provide variable length arrays. Let's change to alloca() then.
