### ISSUE TITLE
Optimize CI pipeline

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#1053]
CI runs are taking too long on TravisCI. Three concurrent jobs is not enough. Let's make more use of github actions.

Codacy asks for too many permissions and is often enough not greatly helpful. Therefore, let's set up sonarcloud for AMICI for static code analysis (can do both python and c++). 

- [ ] Move time-intensive CI steps github actions  
- [x] configure sonarcloud properly
- [x] run sonarcloud code scanner on github ci 
- [ ] use sonarcloud for coverage?
- [x] drop codacy
- [ ] remove static code analysis from travis ci
- [ ] create and use custom CI docker image to avoid reinstallation of dependencies 
- [ ] parallelize where possible

**Comment by dweindl** [comment]
Static code analysis results: https://sonarcloud.io/dashboard?branch=develop&id=ICB-DCM_AMICI

**Comment by paulstapor** [comment]
Wow, that's a lot (was to be expected, bt still).
We have some stuff to address. Really nice, good job with sonarcloud, thanks!

**Comment by FFroehlich** [comment]
1.1k code smells, ouch 🥇

**Comment by paulstapor** [comment]
> 1.1k code smells, ouch 🥇

ok, maybe more than 1k was not to be expected... 😅

**Comment by dweindl** [comment]
Are we happy with github actions and sonarcloud?
I.e. can we remove redundant tasks from travis CI? 
Would propose to get rid of Linux runs there, and slim down OSX by building documentation on github actions / linux.

Opinions?

**Comment by FFroehlich** [comment]
fine with me, remember having issues with documentation runs on linux though.

**Comment by FFroehlich** [comment]
> > 1.1k code smells, ouch 1st_place_medal
> 
> Many of those are related to function arguments shadowing class members. Would be nice to reduce. Common way to avoid is appending an underscore to data members. Fine to change to that? At least for private members, this wouldn't break anything.

Fine with me

**Comment by dweindl** [comment]
I would think the recent changes have addressed this sufficiently. Closing.
