### ISSUE TITLE
SBMLTestSuite failing

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#1054]
FAILED tests/testSBMLSuite.py::test_sbml_testsuite_case[9]
FAILED tests/testSBMLSuite.py::test_sbml_testsuite_case[13]
FAILED tests/testSBMLSuite.py::test_sbml_testsuite_case[30]
FAILED tests/testSBMLSuite.py::test_sbml_testsuite_case[29]
FAILED tests/testSBMLSuite.py::test_sbml_testsuite_case[118]
FAILED tests/testSBMLSuite.py::test_sbml_testsuite_case[213]
FAILED tests/testSBMLSuite.py::test_sbml_testsuite_case[579]
FAILED tests/testSBMLSuite.py::test_sbml_testsuite_case[1245]
FAILED tests/testSBMLSuite.py::test_sbml_testsuite_case[1422]
FAILED tests/testSBMLSuite.py::test_sbml_testsuite_case[1423]
FAILED tests/testSBMLSuite.py::test_sbml_testsuite_case[1431]
FAILED tests/testSBMLSuite.py::test_sbml_testsuite_case[1638]
FAILED tests/testSBMLSuite.py::test_sbml_testsuite_case[1341]
FAILED tests/testSBMLSuite.py::test_sbml_testsuite_case[1342]

Looks like there are currently 14 failing testcases. Issue was introduced somewhere in #1036, #1047 or #1050. Currently trying to figure out where exactly. In case you are intending to use this code anywhere near production, which I believe is the case here, I would recommend to get this fixed ASAP.

**Comment by FFroehlich** [comment]
Also, if you are touching the SBML import in any way, run the testsuite before merging anything. The testuite runs for close to 1.5h which I would like to avoid having as mandatory requirement for all PRs.

**Comment by dweindl** [comment]
> Also, if you are touching the SBML import in any way, run the testsuite before merging anything. The testuite runs for close to 1.5h which I would like to avoid having as mandatory requirement for all PRs.

Fully agreed. Also, reviewers should remind contributors of that.

If somebody feels bored: Why not check the git diff during each CI run, and run the sbml test suite as soon as sbml import code was modified...

**Comment by dilpath** [comment]
Hm I don't think I changed `sbml_import.py` after my last run of the test suite. I'm on `develop`, commit 0b4f025 (the merging of #1036), so I'll double check and run the test suite now.

**Comment by paulstapor** [comment]
Okay, thanks Dilan for looking into that.
I will see how to get that fixed!

**Comment by dweindl** [comment]
Also, starting from #1047 import of the FroehlichKes model takes >6h:  https://github.com/ICB-DCM/AMICI/runs/610049308?check_suite_focus=true

**Comment by paulstapor** [comment]
Okay, for the sbml test suite failing, I have an idea.
For the long import time, that's harder, but will look into as well

**Comment by paulstapor** [comment]
Yes, the problem for the failing tests is/was that Amici cannot handle "ODEs" without species. In the failing examples, all species were constant, hence the CL functions reduced the models until no species were left. This led to a failure of Amici.

What is more tricky (and currently substantially more urgent for at least our group) is fixing the high import times. I've got a couple of theories for this. Let's see, whether or not the correct one is amongst them...

**Comment by paulstapor** [comment]
Back again.
Concerning the high import times, this seems to happen when computing dwdp. I don't yet know for sure what is the reason here. However, I can continue later this evening at it.

**Comment by dweindl** [comment]
> Concerning the high import times, this seems to happen when computing dwdp

Without having looked at the code: In the past, I stumbled over situations where sympy `.jacobian()` took plenty of time to compute things that were obviously 0. Maybe some check for emptyness or zeroes of either argument already does the trick...

**Comment by paulstapor** [comment]
> > Concerning the high import times, this seems to happen when computing dwdp
> 
> Without having looked at the code: In the past, I stumbled over situations where sympy `.jacobian()` took plenty of time to compute things that were obviously 0. Maybe some check for emptyness or zeroes of either argument already does the trick...

Okay, thanks, will check that out tonight.
Concerning SBML test suite: Still running locally, but it's at model 500+ now and so far all worked again. Will push as soon as all model were tested.

**Comment by paulstapor** [comment]
Update:
It looks like the long import times are coming from the fact that we now have a chain rule in dwdp. Most likely, the same thing is going to hit us also in dwdx (only for real conservation laws, possibly), dxdotdp_explicit (if no assignment rules or rate rules are used, this ones should always be zero, so here a short cut can be done), sx0 and sx0_fixedParameters.

What takes so long (I think) is the matrix-matrix-multiplication in the chain rule (dw/dtcl * dtcl/dp).
I think, the best way to resolve this would be turning those quantities into sparse symbolic matrices.
In the very specific case of the cancer signaling model, the latter term is even zero...

I hope, I can fix this tomorrow... I want to wait at least during tonight, how far the import gets and what the timer tells me tomorrow, in order to make sure, it is really the multiplication....

**Comment by FFroehlich** [comment]
How big is `tcl` for that example? Its guaranteed to be smaller than nx, so I find it unlikely that computation of the individual derivatives is the limiting factor (`J` and `dxdotdp` need <1e3s and should be bigger). If one of the matrices is zero, the multiplication shouldn't be carried out, see `_total_derivative`. So I'm not sure whats going on here.

Don't think sparsifying is the right solution here, there should be a simpler solution. Check free vars before computing either derivative? Make sure the multiplication really isn't carried out?

**Comment by FFroehlich** [comment]
https://github.com/ICB-DCM/AMICI/pull/1059/checks?check_run_id=619041189 should give some pointers whats taking so long

**Comment by paulstapor** [comment]
At least one problem, probably the main problem, is that dtcl/dp is a full matrix, as it carries the symbolics named like `s<nameOfTcl__nameOfParameter>`.  However, for this specific model, all of these will be zero...

**Comment by paulstapor** [comment]
Maybe I got a solution... doing a local testimport of the cancer signaling model atm... Let's see...

**Comment by paulstapor** [comment]
This one has been fixed in #1036 and is in master. Closing.
