### ISSUE TITLE
Jacobian not computed in SBML import for rate rule species

### ISSUE THREAD

**Issue by paulstapor** [ICB-DCM/AMICI#1066]
The current implementation of rate rules allows to import SBML models with species that have rate rules or assignment rules. However, the Jacobian is currently not yet computed symbolically.

There are different options to solve this:
 - Add dummy reaction fluxes (via "expression" model quantities) for the corresponding species rate rule (as Jacobian computation via reaction fluxes is implemented).
 - Just delete setting `dxdotdx` to zero, which is currently done in SBML import, which would compute dxdotdx via the already implemented functionality. This might result in (possibly unnecessary) long computation times for large models, which should hence be tested.
 - Add a flag, to compute dxdotdx only for those species, which have rate/assignment rules, or at least only compute it, if the dynamics are not entirely given by reaction fluxes (since then, dxdotdx will always be zero).

**Comment by FFroehlich** [comment]
I like the first idea, wouldn't call it "dummy reaction fluxes" though. I don't know how many times I have to repeat this, the fact that `w` is equal to the reaction fluxes was (its no longer true!) unique to the python-sbml import, and should thus `w` or `expressions` and `reaction fluxes` should not be used interchangably. It wasn't even historically true as the vanilla matlab code generation automatically generated smart `w's` from equations, which isn't done anymore as its computationally quite expensive to do.
