### ISSUE TITLE
simply returns invalid piecewise function

### ISSUE THREAD

**Issue by jvanhoefer** [ICB-DCM/AMICI#1067]
https://github.com/ICB-DCM/AMICI/blob/7d632b52975b9ef5af2b389d9eaeb38fbd40f1cb/python/amici/sbml_import.py#L1028

For the input `piecewise(k_light, time < 60, k_nolight)` the call of `sp.sympify` returns `Piecewise((k_light, time < 60), (k_nolight, True))`, which is no longer in the format of a piecewise function [expected by libsbm](http://sbml.org/Special/Software/libSBML/docs/formatted/python-api/libsbml-math.html)l and hence can not be parsed in the following.

**Comment by FFroehlich** [comment]
should be fixable by using `sympy.printing.mathml` instead of str and then piping through `libsbml.writeMathMLToString(new_mathml)` (or `libsbml.readMathMLFromString` and `libsbml.formulaToL3String` if necessary). Should also make replacing "**" by "^" obsolete.
