### ISSUE TITLE
AMICI not handling NewtonFailure properly

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#1090]
When `SteadystateProblem::workSteadyStateProblem` rethrows `NewtonFailure` in https://github.com/ICB-DCM/AMICI/blob/5af8725d98ed90b8ebb3af68a7e4b95386e8b78c/src/steadystateproblem.cpp#L103
`SteadystateProblem::state` is not set. This leads to https://github.com/ICB-DCM/AMICI/blob/5af8725d98ed90b8ebb3af68a7e4b95386e8b78c/include/amici/model.h#L626
when calling `rdata->processSimulationObjects`.
This in turn result in `AmiciApplication::runAmiciSimulations` throwing, despite `rethrow=False` (which means that AMICI should handle all exceptions and set an appropriate status in `ReturnData`).

**Comment by paulstapor** [comment]
Okay, I wanted to clean this one up anyway...
Seems like it moved up on the to do list...

**Comment by FFroehlich** [comment]
In ForwardProblem this is addressed by using `FinalStateStorer` which would fix the issue, but I guess that doesn't make too much sense here.
