### ISSUE TITLE
Newest sympy version breaks PEtab test suite

### ISSUE THREAD

**Issue by elbaraim** [ICB-DCM/AMICI#1095]
The sympy package got updated to version 1.6, leading to failure of the tests for the PEtab suite: see trace in https://travis-ci.com/github/ICB-DCM/pyPESTO/builds/168030743

This is repeated for some of the cases in the PEtab suite:
```
ERROR:test.test_petab_suite:Cannot set values of <class 'sympy.matrices.immutable.ImmutableDenseMatrix'>
```

**Comment by yannikschaelte** [comment]
I can confirm that it fails for sympy 1.6, works for 1.5.1. actually, quite a bit changed in the release https://github.com/sympy/sympy/wiki/release-notes-for-1.6

**Comment by FFroehlich** [comment]
Will try to have a look tomorrow.
