### ISSUE TITLE
Best way to implement fully adjoint handling of preequilibration

### ISSUE THREAD

**Issue by paulstapor** [ICB-DCM/AMICI#1128]
Hi,

Before I start fiddling around in parts of the C++ functionality I'm not yet familiar with, I wanted to ask for opinions:

My overall aim is to implement a fully adjoint handling of the post- and pre-equilibration logic, as this will be extremely helpful for working with some large-scale models. Here's how I imagine it (in rough terms):

In amici.cpp, we currently have the following logic
```
1. work preequilibration
2. work forward problem
3. work postequilibration
4. work backward problem
Last. processReturnData
```
#1099 adds work postequilibration backward to it. My aim (and the reason, why I'm asking this question) would be adding: `5. work preequilibration backward`. 

Technically, this could already be implemented after merging #1099 (or #917). However, it would still still restrict the fully adjoint usage to systems with well-conditioned Jacobian. Hence, I already started working on a simulation based version of #1099, which works also for singular Jacobians.

Here's what I would need to make things happen:
1. In the beginning of `workFowardProblem`, the function `updateAndReinitStatesAndSensitivities` is called. A corresponding counterpart would be needed in the end of `workBackwardProblem`. I've been writing down the math for it. As long as (A) we only have an update on the constant parameters (or fixed states) and not in the solver states (`x_solver`), this amounts to a heaviside function at a fixed timepoint. This does not influence the adjoint state, luckily. Hence, implementation is pretty doable.
(B) If we have other types of updates (really updating solver states, e.g., due to conserved quantities), this will be more complicated and not work right away.
2. To discern cases (A) and (B), it would be good to add a member to every model (during python generation), which indicates whether we have the easy case (A), or whether the model has complicated conservation laws (causing case (B)).

What do you think about it?

**Comment by FFroehlich** [comment]
Agree, sounds like a reasonable setup. Also agree that such an indicator would make sense.

**Comment by paulstapor** [comment]
fixed on develop now...
