### ISSUE TITLE
No MPI-HDF5 support?

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#1147]
Entirely not sure who exactly the culprit is here, but when working in an environment with libhdf 1.12.0 with mpi support I get the following error:

> ImportError: libhdf5_hl_cpp.so.100: cannot open shared object file: No such file or directory

That library does indeed not exist, but I could find `libhdf5_hl.so.200` in the expected directory in LD_LIBRARY_PATH, so I am assuming this is some kind of HDF incompatibility? Building AMICI worked without a problem. This is happening on CentOS 7.7.

**Comment by FFroehlich** [comment]
Just realised that its missing `libhdf5_hl_cpp` and not `libhdf5_hl`, still probably worthwhile figuring out what is actually going on and adding an appropriate check.

**Comment by dweindl** [comment]
Some broken symlink or pkg-config files? We don't have a specific HDF5 version specified. What does the linker invocation for the AMICI extension look like?

**Comment by dweindl** [comment]
@FFroehlich : Problem solved?

**Comment by FFroehlich** [comment]
didnt investigate further, would close for now. I would guess that its either due to misconfigured package or pkg-config.
