### ISSUE TITLE
Improper handling of replicate measurements in ForwardProblem::workForwardProblem / high memory usage

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#1150]
`ForwardProblem::workForwardProblem calls `handleDataPoint` for each time point, which saves the full `SimulationState` on each invocation. For replicate measurements this creates potentially enormous overhead.

**Comment by dweindl** [comment]
If the state for the given timepoint has already been saved, don't save again. Need to check how to best handle this, as currently `ForwardProblem::timepoint_states` is indexed by non-unique-timepoints index. This should probably be changed to unique-timepoints index.

Same applies to reading from `ForwardProblem::timepoint_states` in `ForwardProblem::getAdjointUpdates`.

**Comment by FFroehlich** [comment]
What about turning `ForwardProblem::timepoint_states` into a `std::map<realtype, SimulationState>`?

**Comment by dweindl** [comment]
Sounds good.

**Comment by paulstapor** [comment]
This will lead to some changes elsewhere, I think, but should be fine.
however, in Returndata, we want to keep those replicates, right?

**Comment by dweindl** [comment]
Although simulation for the replicates will be identical and don't add much value per se, i think it's much more convenient to have the same dimensions as for `ReturnData::y`. So, yes.

**Comment by paulstapor** [comment]
One more question: We store the `initial_state` in `forwardproblem`. So one could even go a step further and fully omit storing `timepoint_states` which occur at `model->t0()`.
A way to go, or too much of a reduction?

**Comment by dweindl** [comment]
If it's not required anywhere, sure, drop it.
