### ISSUE TITLE
Noise standard deviations dependent on model state

### ISSUE THREAD

**Issue by lcontento** [ICB-DCM/AMICI#1170]
Noise standard deviations dependent on model states are not currently supported in AMICI observables. E.g., in correspondence to a state `x` it should be possible to define an observable `y ~ Normal(x, a*x+b)`. This is also possible in PEtab and it appears as an example in the PEtab format reference.

Compilation fails since the signatures for `sigmay` and `dsigmaydp` do not contain the model state `x` among their arguments.

From a mathematical point of view I do not see any reason not to allow this (please correct me if I am wrong).

**Comment by dweindl** [comment]
You right, but duplicate of #609.

**Comment by lcontento** [comment]
Sorry! Forgot to search before posting...
