### ISSUE TITLE
"Cannot find -lcblas" on Fedora machine

### ISSUE THREAD

**Issue by VitaminBrad** [ICB-DCM/AMICI#1174]
**What did you expect to happen?**
pip install amici
**What has happened instead?**

> /compiler_compat/ld: cannot find -lcblas
> 
> collect2: error: ld returned 1 exit status
>     error: command 'g++' failed with exit status 1
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: /home/benglish/.conda/envs/hbp/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jkn46k6d/amici/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jkn46k6d/amici/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6o0d7neo/install-record.txt --single-version-externally-managed --compile --install-headers /home/benglish/.conda/envs/hbp/include/python3.6m/amici 
> 

**AMICI version and system environment**
 - OS and version: [e.g. Ubuntu, iOS, Windows]
Linux, Fedora 32. GNOME Version 3.64.4 (same result both inside Anaconda environment and out)

I read that this issue was solved for someone on Ubuntu [here](https://gitmemory.com/issue/ICB-DCM/AMICI/1038/613101979), therefore I tried to install on my Fedora machine `sudo dnf install atlas-devel` however, according to [this](https://unix.stackexchange.com/questions/287897/install-and-select-libatlas-in-fedora-23) "Fedora 23 : There is no blas or lapack in atlas-3* / atlas-devel, or in atlas-sse* / atlas-sse*-devel."

Futhermore, I noticed [this comment](https://github.com/apache/incubator-mxnet/issues/1442#issuecomment-182171637) for a similar issues of the libatlas Fedora interaction, saying `On CentOS/Fedora/Red Hat, please change -lcblas to -lsatlas`. 

I have limited knowledge in safely detecting a machine's operating system, however, I am willing to make a fork request to make this edit for Fedora machines and attempt this, if that is ok. 

Thanks for your time and attetion! 
Looking forward to use the packages!

Best,
Brad from University Bonn / Fraunhofer Bioinformatics

**Comment by dweindl** [comment]
Hi @VitaminBrad, you retry installation after setting an environment variable `BLAS_CFLAGS=-lsatlas`. Does that work?

If you provide the default location of the relevant libraries on Fedora, we can also add to that to the current auto-detection...

**Comment by VitaminBrad** [comment]
Hi @dweindl! Thanks for the near immediate response!

As a fairly new linux user, I have to describe what I did in embarssing detail:

I ran `BLAS_CFLAGS=-lsatlas` in my terminal (the same location I attempted to run `pip install amici`) and I also put that line in my root .bashrc file and restarted my computer.

However unfortunately, the result appears to still be the same. I am still getting the following error:

```
/compiler_compat/ld: cannot find -lcblas
  collect2: error: ld returned 1 exit status
  error: command 'g++' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for amici
```

`default location of the relevant libraries on Fedora`:
I really am assumping based on one google search that "atlas-devel" indeed is the Fedora version of Debian's "libatlas-base-dev", however, just to make sure: is that the library you mean? I can also provide the anaconda location, if it differs. (I am still trying the installation in both contexts).

Thanks for your help!

**Comment by dweindl** [comment]
@VitaminBrad, I have no Fedora experience, but according to https://koji.fedoraproject.org/koji/rpminfo?rpmID=14724207, the `blas-devel` package should bring everything necessary and AMICI default settings should work for that. (No changes in environment variables should be necessary, ensure that `BLAS_CFLAGS` is unset again).

**Comment by VitaminBrad** [comment]
That did it! Thanks so much, @dweindl! 

I ran `sudo dnf install blas-devel` on my Fedora machine and now `pip install amici` successfully installed amici-0.11.2. 

Have a great day! :smiley:

**Comment by dweindl** [comment]
Glad it worked. Thanks for feedback. Will add that to the installation instructions.
