### ISSUE TITLE
Document responsibilities of model .cpp files

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#120]
## Common

| File | Content |
|------|------------|
| xdot | Right hand side of differential equation for states x | 
| w | Recurring terms in xdot | 
| dwdx | dw/dx | 
|  J | Jacobian of xdot with respect to states x | 
| x0 | Initial states | 
| Jv | Matrix vector product of J with a vector v (for iterative solvers)  | 
| JBand | J in banded form (for banded solvers) | 
| JSparse | J in sparse form (for sparse solvers from the SuiteSparse Package)  | 
| y | Observables / measurements | 
| z | Event-resolved measurements | 
| deltax | State update functions for events | 
| root | Event trigger function for events   | 
| Jy | Likelihood of measurements y | 
| Jz | Likelihood of event-resolved measurements z | 
| sigma_y | Standard deviation of measurements | 
| sigma_z | Standard deviation of events | 

## First order sensitivities
| File | Content |
|------|------------|
| dwdp | Sensitivity of w w.r.t. model parameters p |
| dxdotdp | Sensitivity of dx/dt w.r.t. model parameters p |
| dydp | Sensitivity of observables y w.r.t. model parameters p |
| sx0 | Sensitivity of initial states x0 | 
| dJydx | Sensitivity of likelihood Jy w.r.t. state variables x |
| dydx | Sensitivity of observables y w.r.t. state variables x | 
| dJydp | Sensitivity of likelihood Jy w.r.t. model parameters p |
| dsigma_ydp | Sensitivity of standard deviation of measurements w.r.t. model parameters p |
| dsigma_zdp | Sensitivity of standard deviation of events w.r.t. model parameters p |

### Forward sensitivities
| File | Content |
|------|------------|
| sxdot | Right hand side of differential equation for state sensitivities sx | 
| sy | Sensitivity of measurements y, total derivative | 
| sJy | Sensitivity of likelihood Jy, total derivative | 
| sz | Sensitivity of z, total derivative |
| sz_tf | Sensitivity of z at final timepoint (ignores sensitivity of timepoint), total derivative | 
| deltasx | Sensitivity update functions for events, total derivative |
| stau | Sensitivity of event timepoint, total derivative  |
| sroot | Sensitivity of event trigger function, total derivative  |
| dJydy | Sensitivity of measurement likelihood Jy w.r.t. observables y |
| sJz | Sensitivity of event-resolved measurement likelihood Jz, total derivative |

### Adjoint sensitivities
| File | Content |
|------|------------|
| xBdot | Right hand side of differential equation for adjoint state xB   |
| qBdot | Right hand side of integral equation for quadrature states qB |
| JB | Jacobian of xBdot with respect to adjoint state xB |
| JvB | Matrix vector product of JB with a vector v (for iterative solvers)  | 
| JBandB | JB in banded form (for banded solvers) | 
| JSparseB | JB in sparse form (for sparse solvers from the SuiteSparse Package)  | 
| dzdx | Sensitivity of event-resolved measurements z w.r.t. to model states x  |
| dzdp |  Sensitivity of event-resolved measurements z w.r.t. to model parameters p  |
| deltaxB | Adjoint state update functions for events  |
| deltaqB | Quadrature state update functions for events  |
| dJzdx | Sensitivity of event-resolved measurement likelihood Jz w.r.t. to model states x |
| dJzdp | Sensitivity of event-resolved measurement likelihood Jz w.r.t. to model parameters p |

## Second order forward sensitivities
| File | Content |
|------|------------|
| s2root | Second order sensitivity of event trigger function, total derivative  |

## Differential Algebraic Problems
| File | Content |
|------|------------|
| dx0 | Initial value for time derivative of states | 
| sdx0 |  Initial value for sensitivity of time derivative of states | 
| dfdx | Jacobian of xdot with respect to states x   | 
| M | Mass matrix of the system |

**Comment by FFroehlich** [comment]
Filled all missing fields, let me know if anything is missing/unclear.
