### ISSUE TITLE
Add AmiciSolver class

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#123]
currently selection between CVODES and IDAS is done via inclusion of the headers cvodewrap.h or idawrap.h, which is intransparent and error prone. Instead make abstract base class AmiciSolver with concrete classes CVODESSolver and IDASSolver. Class should be instatiated as member of AmiciModel class (https://github.com/ICB-DCM/AMICI/issues/122), which holds information whether ODEs or DAEs are specified.

**Comment by dweindl** [comment]
All `wrap_*()` from `wrapfunctions.h` should then be moved to solver-specific files. 

Solver-dependent functions such as CVodeInit should then not be called with the specific model function directly, but with a solver-specific wrapper instead. 

This wrapper should receive a pointer to the AmiciModel, UserData, and TempData and then call the AmiciModel member functions.
