### ISSUE TITLE
Memory deallocation in case of errors

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#13]
The code for memory cleanup is quite messy at the moment. Especially in the case of error I am not too sure that we do not run into memory leaks. Here the structure should definitely be improved (set flags whether certain parts of the memory have been allocated?)

**Comment by dweindl** [comment]
I started initializing all pointers in UserData ... with 0 to be able to test whether memory has been allocated and added respective freeUserData ... functions. Currently only on branch feature_compile_standalone. Will try to merge soon.
