### ISSUE TITLE
Get mex.h out of symbolic_functions.cpp

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#142]
I would like to get `mex.h` completely out of `symbolic_functions.cpp`. 

Currently it is used to provide (is)nan and (is)inf. I suggest, we use the standard C++ versions for the matlab part as well. Or is there any reason not to do so?

Other mex dependency in `symbolic_functions.cpp` is `mexWarnMsgIdAndTxt`, I suggest moving that to `amici_interface*.cpp`. 

Edit: with that we can also get rid of the AMICI_WITHOUT_MATLAB variable.

**Comment by FFroehlich** [comment]
I believe that the main reason to have isnan and isinf implementations was MSVS. So using C++ versions should be fine.
moving mexWarnMsgIdAndTxt to the respective interface also sounds good!
