### ISSUE TITLE
Out of memory error for large models on Windows

### ISSUE THREAD

**Issue by LeonardSchmiester** [ICB-DCM/AMICI#161]
On Windows machines, compilation of large models using the Matlab MinGW add-on can lead to errors of the form:
```
Error using mex
cc1plus.exe: out of memory allocating 248026128 bytes
```

In my case, this problem could be resolved by using a newer version of MinGW.
To do so, download the latest version of MinGW (e.g. from [https://sourceforge.net/projects/mingw-w64/](https://sourceforge.net/projects/mingw-w64/)) and install it. The installation directory must not contain blanks. I had to change the Architecture setting to x86_64.

After installation you have to set the path for the compiler. 
See [https://de.mathworks.com/matlabcentral/answers/313298-i-already-have-mingw-on-my-computer-how-do-i-configure-it-to-work-with-matlab](https://de.mathworks.com/matlabcentral/answers/313298-i-already-have-mingw-on-my-computer-how-do-i-configure-it-to-work-with-matlab) for instructions.

This should solve the compilation problem. However, this can lead to an error while model simulation, saying that some libraries are missing. The libraries shoud be in the `minGW/bin` folder. 
Setting the `LD_LIBRARY_PATH` to this folder doesn't seem to solve the problem, so at the moment I copy the .dll files to the folder of the .mex file of my model.

**Comment by dweindl** [comment]
Another work-around is simplifying large source files (most likely the one for dydx). See script in #213.

**Comment by DantongWang** [comment]
Downloading MinGW from the prvided link does not work for me. 
But it works now when I download this: https://sourceforge.net/projects/tdm-gcc/
Just incase somebody needs in the future.
