### ISSUE TITLE
STRUCT2AMICI needs editing

### ISSUE THREAD

**Issue by JanHasenauer** [ICB-DCM/AMICI#162]
This routine is currently a mess and not documented. The implementation needs to be revised.

**Comment by FFroehlich** [comment]
I would rather completely delete the routine as all users I know anyways directly pass the struct to the amiwrap routine (but that feature should be better documented).

**Comment by JanHasenauer** [comment]
Fair comment!

In the immune cell project I was working, I had to automatically generate many different models. It is easier to do this on the level of the struct. For checking the generated models, the m-file was however more appropriate. I guess that this might also hold true for other models.

May I ask how this is done for the SBML import. Is for the struct generated or is it directly written to a function?

**Comment by FFroehlich** [comment]
SBML is written to a file to allow specification of observables etc later on.
