### ISSUE TITLE
Better definition of initial conditions for DAEs

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#210]
We want three options:

1) user specifies both x0 and dx0, then CalcIC is not called
2) user specifies x0, then CalcIC needs to be called with IDA_YA_YDP_INIT
3) user specifies dx0, then CalcIC needs to be called with IDA_Y_INIT

~probably sufficient to specify this at compile time.~ determine at runtime and take options.x0 and options.dx0 into account.

**Comment by dweindl** [comment]
At compile time? Not at runtime?

**Comment by FFroehlich** [comment]
Hmm you are right, we allow specification of x0 via options.x0 and should probably extend this to options.dx0. But that also means that we should definitely perform the check at runtime and not at compile time.
