### ISSUE TITLE
replace reoccuring expressions 

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#213]
symbolic expressions of derivatives (dydx, dydp, dwdx,dwdp,...) may contain a large number of reoccuring expressions that blow up the file size. We can fix that by finding unique expressions in gccode.

Note: Find unique expressions at the char level.

**Comment by dweindl** [comment]
Proof on concept for dydx attached.
[replaceRecurringExpressions.py.txt](https://github.com/ICB-DCM/AMICI/files/1413933/replaceRecurringExpressions.py.txt)

**Comment by HoangLUT** [comment]
Dear FFroehlich and Dweindl,
How should I replace reoccuring expressions? Is it just like I copy your .py file to my model directory, run it on Python? Then compile my code on Matlab? Could you clarify more how we do it.
My model would have up to 40000 ode equation so it is good to replace those term consuming memory. Please, help me on this issue.
Your help is greatly appreciated.

**Comment by FFroehlich** [comment]
Dear Hoang,

sorry for not replying to your email earlier. 40k ODE equations is a lot and substantially more than any model that we have compiled with AMICI so far. This issue specifically adresses reoccuring expressions in the observables. Those in the ODEs are already automatically handled in AMICI.

Do you need to compute sensitivity equations? If not, setting `model.adjoint = false` and `model.forward = false` should substantially reduce compilation time and memory requirements. Still I am not sure whether compilation will be possible. We are planning to move to a different symbolic engine for quite a while now, which might make compilation of models at that scale more feasible, but as always these things can take a while to implement.

**Comment by HoangLUT** [comment]
Dear Fabian,
Thank you so much for getting back to me.
In my problem, I do not need to compute sensitivity equations and have tried to add those 2 lines you suggested and it could reduce compilation time 3 times in smaller ODE system. However, with my problem it is still out of memory.

Regarding observables, could you please tell me more what this is and why we need this in compilation? Are they experimental data? I have thought we already have SYSTEM EQUATIONS (model.sym.xdot). If observables are the main reason for running out of memory, could we skip it in model?

My model is rather simple, SYSTEM EQUATIONS are the product of model.sym.k * model.sym.x. Could we reduce compilation time and memory consumption?
May I ask if you have some time to take a look on my model (attached) and give me some ideas to avoid those issues? Please, remove .txt extension to run on Matlab.
Thank you so much for your time and I wish you a nice weekend.

[model_polymer_degradation.m.txt](https://github.com/ICB-DCM/AMICI/files/1628154/model_polymer_degradation.m.txt)
[polymer_degradation.m.txt](https://github.com/ICB-DCM/AMICI/files/1628155/polymer_degradation.m.txt)
