### ISSUE TITLE
link sundials related libraries statically

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#224]
filesize should not matter for our applications but static linking might yield a speedup according to http://sundials.2283335.n4.nabble.com/Problems-compiling-a-program-using-CVODE-td4652679.html

**Comment by dweindl** [comment]
I wouldn't expect any measurable performance gain. However, it *might* allow you to run the mex files on other systems on which you don't have a mex compiler installed.

**Comment by FFroehlich** [comment]
I am not sure whether static linking of the mex library is possible. I think static linking of the N_Vector libraries make sense as this allows inlining + optimization etc and the respective functions are heavily used throughout CVodes/IDAs. Moreover this solved the DYLD_LIBRARY issues, so those no longer need to be set as environment variables ;)

**Comment by dweindl** [comment]
No, I did not mean static linking of the mex library. But you can probably run the mex files compiled on computer A to computer B (same OS, same matlab release). 

There won't be any more optimization and no inlining than before.

Getting rid of DYLD_LIBRARY stuff is good though.
