### ISSUE TITLE
function dissect

### ISSUE THREAD

**Issue by thomassligon** [ICB-DCM/AMICI#227]
Running installAMICI.m causes MATLAB warnings
`Warning: Function dissect has the same name as a MATLAB builtin. We suggest you rename the function to avoid a potential name conflict.`
`> In path (line 109)`
`  In addpath (line 94)`
`  In installAMICI (line 3) `
`Warning: Function dissect has the same name as a MATLAB builtin. We suggest you rename the function to avoid a potential name conflict. `
`> In path (line 109)`
`  In addpath (line 94)`
`  In installAMICI (line 4) `
`Warning: Function dissect has the same name as a MATLAB builtin. We suggest you rename the function to avoid a potential name conflict. `
`> In path (line 109)`
`  In addpath (line 94)`
`  In installAMICI (line 5) `
but I can't find the definition of the function dissect in the AMICI code.

**Comment by FFroehlich** [comment]
I cannot reproduce this issue. Can you please check what `which dissect` returns after these warnings have occured?

**Comment by thomassligon** [comment]
Sorry for the confusion, this was my mistake. The error comes as part of tbxstartup, which is part of MPT, which is part of CRNreals, a MATLAB for calculating CRN (chemical reaction networks).
