### ISSUE TITLE
conversion from 'size_t' to 'int'

### ISSUE THREAD

**Issue by thomassligon** [ICB-DCM/AMICI#229]
Compiler warning:
C:\data\Tom\Research\AMICI\src\amici_interface_matlab.cpp(145): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
mxGetM and mxGetN return size_t:
https://www.mathworks.com/help/matlab/apiref/mxgetn.html
https://www.mathworks.com/help/matlab/apiref/mxgetm.html
The type size_t should be defined:
https://www.mathworks.com/help/bugfinder/ref/managementofsize_tsizettypeis.html
Possible solution: dynamic type cast (conversion) to int:
New line 99-100:
```
                             int(mxGetM(prhs[RHS_TIMEPOINTS])) *
                                 int(mxGetN(prhs[RHS_TIMEPOINTS])));
```
New line 69:
`        int len = int(mxGetM(a)) * int(mxGetN(a));          `                        \
New line 162:
`                        int(mxGetM(prhs[RHS_PLIST])) * int(mxGetN(prhs[RHS_PLIST])));`

**Comment by dweindl** [comment]
@thomassligon Which compiler are you using?

**Comment by thomassligon** [comment]
I am using Visual Studio 2017 C++.

**Comment by dweindl** [comment]
Changing that to `size_t` is not a big issue. However, we didn't want to care about MSVS anymore...

**Comment by thomassligon** [comment]
This is just a warning and doesn't prevent compilation, so one possible solution is to leave it as it is and close the issue.
Another possible solution is an explicit cast to int, which also removes the warning:
line 69:
`        int len = (int)mxGetM(a) * (int)mxGetN(a);      `
line 99-100:
```
                             (int)mxGetM(prhs[RHS_TIMEPOINTS]) *
                                 (int)mxGetN(prhs[RHS_TIMEPOINTS]));
```
line 162:
`                        (int)mxGetM(prhs[RHS_PLIST]) * (int)mxGetN(prhs[RHS_PLIST]));`

PS: You didn't want to care about MSVS, but now you have customers.
