### ISSUE TITLE
Compiler warnings in amici_interface_matlab.cpp

### ISSUE THREAD

**Issue by thomassligon** [ICB-DCM/AMICI#231]
C:\data\Tom\Research\AMICI\src\amici_interface_matlab.cpp(505): warning C4244: 'argument': conversion from 'amici::realtype' to 'const int', possible loss of data
c:\data\tom\research\amici\src\amici_interface_matlab.cpp(253) : warning C4715: 'amici::amici_blasCBlasTransToBlasTrans': not all control paths return a value
It would be good to clean up these compiler warnings, but I don’t have a suggestion for how to do it.

**Comment by FFroehlich** [comment]
`c:\data\tom\research\amici\src\amici_interface_matlab.cpp(253)`:
the switch statement covers all enum values of the AMICI_BLAS_TRANSPOSE typedef. I don't see a problem here. A default value does not make sense in this context.

`C:\data\Tom\Research\AMICI\src\amici_interface_matlab.cpp(505)`:
this indeed an error in the function definition and should be fixed

**Comment by dweindl** [comment]
We can throw an exception when reaching the end of the function. A default value does indeed not make much sense.
