### ISSUE TITLE
Warning: Support of character vectors will be removed in a future release.

### ISSUE THREAD

**Issue by thomassligon** [ICB-DCM/AMICI#234]
When I import SBML, I get this warning 208 times:
```
Warning: Support of character vectors will be removed in a future release. Character vectors can be used only for variable names and numbers. Instead,
to create symbolic expressions first create symbolic variables using 'syms'. To evaluate character vectors and strings representing symbolic
expressions, use 'str2sym'. 
> In sym>convertExpression (line 1581)
  In sym>convertChar (line 1486)
  In sym>tomupad (line 1236)
  In sym (line 215)
  In cell2sym (line 31)
  In sym>tomupad (line 1248)
  In sym (line 215)
  In SBMLode/importSBML>cleanedsym (line 686)
  In SBMLode/importSBML (line 208)
  In SBMLode (line 63)
  In testAMICI (line 6) 
```
This makes it difficult to see the real messages.
The solution is easy, and is contained in the warning itself.
Just replace importSBML line 686
`csym = sym(sanitizeString(strrep(str,'time','__time_internal_amici__')));`
by
`csym = str2sym(sanitizeString(strrep(str,'time','__time_internal_amici__')));`

**Comment by FFroehlich** [comment]
This is a known issue: https://github.com/ICB-DCM/AMICI/issues/50

The last time I checked, the warning did not recommend usage of `str2sym`. I would thus assume that this functionality is not backwards compatible and we probably need to perform version checking.

Still thanks for pointing this out :)

**Comment by thomassligon** [comment]
Yes, I checked the MATLAB documentation. str2sym was introduced in R2017b.

**Comment by dweindl** [comment]
In R2018a this no longer raises a warning but SBML-import fails, see #303.
