### ISSUE TITLE
Compilation failure on windows due to missing execinfo.h

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#245]
Occurs in https://github.com/ICB-DCM/AMICI/blob/5cb96b75b4c9ba3405165e756b7a7c03d046d4bf/include/amici_exception.h#L10
This header is not available by default on windows.

**Comment by HoangLUT** [comment]
Hello Dweindl,
What is that error really? I am using GitHub desktop on macOS and clone this repository and run 'installAMICI.m'. I test some models and it works just fine.
I did the same thing on my Windows PC and got that error. How should we fix it now? I am not sure why only Windows PC get that issue.
Thanks for your time.

**Comment by FFroehlich** [comment]
I will try to fix this issue on Monday.
