### ISSUE TITLE
Compilation and Simulation tasks

### ISSUE THREAD

**Issue by HoangLUT** [ICB-DCM/AMICI#247]
Hello Fabian and Daniel,
Let's say that I do a compilation 'amiwrap' on Linux and fetch all the outputs from compilation task including: 'simulate_name.m', 'ami_name.mexa64', and the folder for that compilation in 'models' folder.
Can I then do a simulation task on Windows PC?
Thanks for your time.
Best regards,

**Comment by FFroehlich** [comment]
Hi Hoang,

Unfortunately this is not possible. The simulation routines have to be compiled on the respective platform. Linux platforms will generate `.mexa64`, while windows platforms will generate `.mexw64`.

**Comment by HoangLUT** [comment]
Hi Fabian,
Thanks for your answer :)
