### ISSUE TITLE
Possibility of including piecewise functions in model definition?

### ISSUE THREAD

**Issue by dlekshmi** [ICB-DCM/AMICI#260]
Hi 

I have a piece wise input function that I would like to use. I tried using the ami_piecewise function  however, this fails. I guess the symbolic conversion from the 'syms' model to '.m' model does not yet allow for piecewise input functions. Am I correct in my understanding ?

Regards
Lekshmi

**Comment by FFroehlich** [comment]
Hi Lekshmi,

We actually do support piecewise functions in AMICI! Check https://github.com/ICB-DCM/AMICI/blob/master/symbolic/am_piecewise.m . It does not have the same interface as the symbolic piecewise function, but should have the same functionality.
