### ISSUE TITLE
Invalid MEX-file ...: Missing symbol 'ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4swapERS4'  (was: example_dirac does not work)

### ISSUE THREAD

**Issue by kjnousia** [ICB-DCM/AMICI#263]
Hi, 
I have been testing examples extracted from the zip file. They do not work. For example, example_dirac function starts fine but does not produces error shown below. What is going on?

>> example_dirac
Generating model struct ...
Parsing model struct ...
x | k | p | z | root | rz | sigma_z | Jrz | Jz | dJrzdsigma | dJrzdz | dJzdsigma | dJzdz | deltax | ddeltaxdp | xB | deltaqB | drootdx | sx | drootdp | xdot | w | drootdt | dtaudp | ddeltaxdx | deltaxB | drzdp | drzdx | sigma_y | dsigma_ydp | dsigma_zdp | dwdp | dwdx | y | dydp | dzdp | dtaudx | dzdx | srz | x0 | sx0 | dzdt | sroot | stau | sz | 
Generating C code ...
deltax | root | sigma_y | stau | xdot | y | CMakeLists | main | 
Compiling mex file ...
wrapfunctions | Building with 'g++-4.9'.
MEX completed successfully.
linking | Building with 'gcc-4.9'.
MEX completed successfully.
Generating M code ...
Invalid MEX-file '/m/cs/project/epimodel/software/ICB-DCM-AMICI-65b21e5/examples/example_dirac/ami_model_dirac.mexa64':
Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4swapERS4_' required by
'/m/cs/project/epimodel/software/ICB-DCM-AMICI-65b21e5/examples/example_dirac/ami_model_dirac.mexa64'
Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_assignERKS4_' required by
'/m/cs/project/epimodel/software/ICB-DCM-AMICI-65b21e5/examples/example_dirac/ami_model_dirac.mexa64'
Missing symbol '_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm' required by
'/m/cs/project/epimodel/software/ICB-DCM-AMICI-65b21e5/examples/example_dirac/ami_model_dirac.mexa64'
Missing symbol '_ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEED1Ev' required by
'/m/cs/project/epimodel/software/ICB-DCM-AMICI-65b21e5/examples/example_dirac/ami_model_dirac.mexa64'
Missing symbol '_ZTTNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE' required by
'/m/cs/project/epimodel/software/ICB-DCM-AMICI-65b21e5/examples/example_dirac/ami_model_dirac.mexa64'
Missing symbol '_ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE' required by
'/m/cs/project/epimodel/software/ICB-DCM-AMICI-65b21e5/examples/example_dirac/ami_model_dirac.mexa64'
Missing symbol '_ZTVNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE' required by
'/m/cs/project/epimodel/software/ICB-DCM-AMICI-65b21e5/examples/example_dirac/ami_model_dirac.mexa64'.

Error in simulate_model_dirac (line 233)
sol = ami_model_dirac(tout,theta(1:4),kappa(1:0),options_ami,plist,pbar(plist+1),xscale,init,data);

Error in example_dirac (line 26)
sol = simulate_model_dirac(t,log10(p),k,[],options);

**Comment by dweindl** [comment]
Hi kjnousia,

This seems to be a common problem with mex files. Matlab uses an incompatible version of the c++ standard library. You can fix this by preloading the correct library.

On Ubuntu 17.10 you can do `export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6:/usr/lib/x86_64-linux-gnu/libprotobuf.so.10`

On Fedora 25 you can do `export LD_PRELOAD=/usr/lib64/libstdc++.so.6`

For other operating systems you might have to adapt that. 
It will be more convenient if you add this line into you shell startup file or to your matlab launcher.

**Comment by kjnousia** [comment]
Thank you for your kind reply. I do not have libprotobuf.so.10 but adding /usr/lib/x86_64-linux-gnu/libstdc++.so.6 to the environtmental variable helped. The example works.
