### ISSUE TITLE
Error with am_max

### ISSUE THREAD

**Issue by LoosC** [ICB-DCM/AMICI#298]
After updating to the newest version, I get the following error message when using am_max in the definition of the observables (Matlab2016b):

Error using mex
/Users/..._dydx.cpp:9:23: error: use of undeclared identifier 'max'; did you mean 'fmax'?
  dydx[1+0*27] = diff(max(x[0],1.0E1),x[0]);

**Comment by FFroehlich** [comment]
looks like MATLAB is ignoring that max is a function again :(
for which matlab version is this happening?

**Comment by LoosC** [comment]
Matlab2016b
