### ISSUE TITLE
example_dirac_adjoint_hessVecProd broken

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#304]
When running `example_dirac_adjoint_hessVecProd`

> Y must have size [11,1] ([D.nt,D.ny])!

But has size:  9     1

**Comment by FFroehlich** [comment]
cannot reproduce this issue, does it still occur for your?

**Comment by dweindl** [comment]
Works with v0.6.0. Still fails on some older version. Closing.
