### ISSUE TITLE
Improve exception handling

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#328]
Currently all AMICI exceptions are caught in amici.cpp and are converted to status code + printf output. In my opinions it is easier to rethrow or not handle them. At the moment, it is not possible to access the messages programmatically in python (at least not without huge hacks). When using jupyter notebooks, they will only show up in the shell, but not within the notebook.

**Comment by FFroehlich** [comment]
The problem is that throwing exceptions in cpp code takes away the possibility to check simulation results + diagnostics after the exception was thrown. This means that all model debugging would have to happen at the cpp level, which is quite inconvenient.
What we could do is implement a debug switch that switches between the two modes.

**Comment by dweindl** [comment]
Agreed on that point. But maybe we can then distinguish between those exceptions after which there is something useful to retain (integration errors) and all the rest (during solver setup, when setting invalid options, ...).

**Comment by FFroehlich** [comment]
Uncaught exceptions will crash python, so I guess not handling them is not a viable option:

```
libc++abi.dylib: terminating with uncaught exception of type amici::AmiException: Dimension mismatch. Size of x0 does not match number of model states.
```

**Comment by dweindl** [comment]
Yes, unfortunately they are not automatically turned into python exceptions. Can be done though http://www.swig.org/Doc3.0/SWIGDocumentation.html#Customization_exception .

**Comment by FFroehlich** [comment]
Initial support for python exception handling in #92c5480, will do a more specialized PR later on.
Could not get it to work with `%exception` so currently still using the deprecated `%exception(python)`.
