### ISSUE TITLE
paper citation

### ISSUE THREAD

**Issue by thomassligon** [ICB-DCM/AMICI#329]
Please include a citation to the AMICI paper in README.md. The citation might be the following, or perhaps some other format:
Fröhlich, F., Kaltenbacher, B., Theis, F. J., & Hasenauer, J. (2017). Scalable Parameter Estimation for Genome-Scale Biochemical Reaction Networks. Plos Computational Biology, 13(1), e1005331. doi: 10.1371/journal.pcbi.1005331

**Comment by dweindl** [comment]
Might be good to include a longer/full list of references where AMICI was used. Could be also helpful to show some benchmarking results of AMICI vs Matlab solvers / sundialsTB.
