### ISSUE TITLE
Preequilibration: make newton_preeq=True implicit if conditionPreequilibration is provided

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#331]
I propose to make `newton_preeq=True` implicit if `conditionPreequilibration` is provided, so that not two options need to be changed to enable preequilibration. Does that change any expected behaviour?

We could also remove `newton_preeq` completely, and only decide based on whether `conditionPreequilibration` is set. This would also be helpful for #262, when we want to allow passing `std::vector<ExpData>` and include the `conditionPreequilibration` there and don't have to fiddle with the `Solver` object.

**Comment by FFroehlich** [comment]
Yes, that sounds reasonable. I am not sure about completely removing `newton_preeq`, as it might come handy when debugging and preequilibration should be possible without passing ExpData.

**Comment by dweindl** [comment]
Great. Regarding the debugging part: might be more flexible and helpful then to allow specifying the preequilibration parameters themselves in `AmiOptions` instead of only yes/no. They would be overwritten then by those in ExpData if provided.

**Comment by FFroehlich** [comment]
We need to keep in mind that we might want to request preequilibration with the same fixed parameters as for the dynamic simulation. I think we should still remove `newton_preeq`, but also add a function provides the same functionality but simply copies the regular fixed parameters to  `conditionPreequilibration`.

**Comment by dweindl** [comment]
True. In my opinion it is fine to simply provide a copy of the fixed parameter vector. This creates minimal overhead.
