### ISSUE TITLE
Matlab version fails, when pscale is a vector

### ISSUE THREAD

**Issue by LeonardSchmiester** [ICB-DCM/AMICI#350]
In `amioption`, function `set.pscale`, pscale is assumed to be a single value.

Same holds true for the `simulate` files for:
```
switch (options_ami.pscale)
    case 1
        chainRuleFactor = exp(theta(options_ami.sens_ind));
    case 2
        chainRuleFactor = 10.^theta(options_ami.sens_ind)*log(10);
    otherwise
        chainRuleFactor = ones(size(options_ami.sens_ind));
end
```

**Comment by FFroehlich** [comment]
looks like the matlab implementation was never updated after implementing that feature in cpp. should be easy to fix by simply looping over `.pscale` (if it is a vector) and assigning chainRuleFactor individually. However, on the long run, `chainRuleFactor` should completely disappear from the simulate files.
