### ISSUE TITLE
[doc] missing dependency documentation

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#352]
explicitly list `swig` as dependency for the python interface

**Comment by dweindl** [comment]
... and provide more detailed installation guide for osx, ubuntu, windows.

**Python**: Minimal python version is set to 3.6 in CMake scripts. Current pypi package ran successfully with Ubuntu16.04/Python3.5 though. 

**SWIG**: version 3.0

**CMake**: TODO

**BLAS**: Tested: Accelerate, Intel MKL, cblas, openblas, atlas

Notes:
**Ubuntu dependency installation**
`sudo apt-get install libatlas-base-dev libhdf5-dev swig3.0`

**Comment by dweindl** [comment]
And maybe mention somewhere, that on (some/all?) Ubuntu the swig executable for version 3.0 is called `swig3.0` but setuptools only looks for `swig`.
