### ISSUE TITLE
[feature] Possibility to ensure positivity of states

### ISSUE THREAD

**Issue by paulstapor** [ICB-DCM/AMICI#364]
The option qpositivex was deleted from the AMICI options since it did not work well. Using am_max on the corresponding states is a better workaround.

Since the Python-interface doesn't have a syms-file, we can't use this workaround in the Python-version. Hence we need some other possibility to encode the positivity of states...

**Comment by dweindl** [comment]
Could add an option `nonNegativeStates=list()`in `SbmlImporter.sbml2amici` taking an index list and wrapping the respective terms in `max()`.

**Comment by paulstapor** [comment]
Would be a way to go.
Is there any possibility to specify this list in an sbml file?

**Comment by FFroehlich** [comment]
You need a good method to enforce positivity in the first place. Its not that easy to do this efficiently with multistep solvers
