### ISSUE TITLE
[core] Apply model.requireSensitivitiesForAllParameters() by default

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#365]
really confusing to set `solver.setSensitivityMethod(amici.AMICI_SENSI_FSA)` and not finding any sensitivities at all

**Comment by FFroehlich** [comment]
overall it feels weird that `setSensitivityOrder` is a `Solver` method and `requireSensitivitiesForAllParameters` is a `Model` method. From a coding perspective it would probably would make more sense moving `setSensitivityOrder` to the Model, as `plist_` only affects things in the Model but effectively neither of them really belong in the model from a conceptual point of view ...

**Comment by dweindl** [comment]
Agreed that it is not super intuitive. For me it is fine moving everything to `Model`. If we find another, more natural way, then it's even better.
