### ISSUE TITLE
Xdata structs

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#37]
We should turn these structs into proper C++ classes with Functions which parse hdf5 or MATLAB rhs. This will make maintenance easier and improve readability/interpretability of code. We should probably also get rid of these accessor macros. 

Note that udata and tempdata are used in C code (model specific functions).

**Comment by dweindl** [comment]
Will start with UserData

**Comment by dweindl** [comment]
- [x] UserData
- [x] ReturnData
- [ ] TempData
- [ ] ExpData
