### ISSUE TITLE
add timepoints to ExpData

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#370]
same as for `fixedParameters`, make specification in `ExpData` supersede specification in `Model`.

**Comment by dweindl** [comment]
Should timepoints in ExpData be mandatory? Not strictly necessary, but might prevent some errors due to timepoint mismatches...

**Comment by FFroehlich** [comment]
I have implemented them to be not mandatory, this gives us backwards compatibility and some flexibility how we specify timepoints. By Timepoint mismatches you mean that `nt` for `my` and `sigmay`  in ExpData does not agree with timepoints in model? I believe we already check for that.

**Comment by dweindl** [comment]
By mismatch, I meant that the data is for timepoints [1.0, 2.0, 3.0], but the model has for some reason timepoints [0.0, 5.0, 10.0].

Okay, if it was not optional, one would have to inflate edata.my to cover time points for which we want the simulation but where there is no data...

**Comment by FFroehlich** [comment]
But, having to fill inflate edata for higher resulotion is the status quo anyways, right?
As we now have access to the solver, I would rather add additional calls there where you would do something like getStates(timepoints) to recover more finegrained simulations for e.g. plotting.

**Comment by dweindl** [comment]
> to recover more finegrained simulations for e.g. plotting

Yes, that was what i meant

> But, having to fill inflate edata for higher resulotion is the status quo anyways, right?

But, right. Not sure what I had in mind...
