### ISSUE TITLE
[python] checkLibSBMLErrors does not print all errors

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#373]
In https://github.com/ICB-DCM/AMICI/blob/master/python/amici/sbml_import.py#L248: 

- Only warnings are printed
- Errors are not printed, only a rather uninformative exception message is shown instead
- [`libsbml.LIBSBML_SEV_FATAL`](http://sbml.org/Software/libSBML/5.13.0/docs//python-api/namespacelibsbml.html#a3f11c0477625f75fba21f2848d705b3c) is ignored completely (although docstring says different..) 

- There should be an option to ignore errors?

**Comment by FFroehlich** [comment]
I don't think we should ever ignore errors, they usually indicate that a function failed to execute.

**Comment by dweindl** [comment]
By ignoring, I mean to not throw an exception (maybe turn into warning) and continue model generation. I think this should be allowed to deal with SBML models with messy unit definitions and so on. Default behaviour should be an error though.

**Comment by FFroehlich** [comment]
I believe that we cannot continue after an error. I don't think Unit defintions issues will lead to errors, but checking those can be turned off by passing `check_validity=False` to the `SbmlImporter` constructor.

**Comment by dweindl** [comment]
E.g. 
> libSBML Error (SBML component consistency): The value of a <species>'s 'units' attribute is restricted. 
Reference: L2V4 Section 4.8.5
 The value of a <species>'s 'substanceUnits' attribute can only be one of the following: 'substance', 'mole', 'item', 'gram', 'kilogram', 'dimensionless', or the identifier of a <unitDefinition> derived from 'mole' (with an 'exponent' of '1'), 'item' (with an 'exponent' of '1'), 'gram' (with an 'exponent' of '1'), 'kilogram' (with an 'exponent' of '1'), or 'dimensionless'.  The current value ('unitDef_nM') is not allowed.

If this is covered by `check_validity=False`, then it is okay. When checking the code that was not obvious to me. Did not try though.

**Comment by FFroehlich** [comment]
Okay, I was not aware that validateSBML would produce errors. `check_validity` should bypass that (but also not show the error). We really need everything but `validateSBML` to pass without errors as we are at serious risk to simulate the wrong equations otherwise (given we can even generate them).
