### ISSUE TITLE
Python steadystate example broken

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#379]
... due to renaming of `get*Names` functions.

Additionally, SBML model needs to be fixed to not show warnings during import.

**Comment by FFroehlich** [comment]
can we include notebooks in CI?

Also, what is the meaning of the "good first issue" label?

**Comment by dweindl** [comment]
> can we include notebooks in CI?

Yes, [nbconvert](https://nbconvert.readthedocs.io/en/latest/execute_api.html) can run them on the shell.

> Also, what is the meaning of the "good first issue" label?

That you can work on that without being too deep in the codebase (https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/)
