### ISSUE TITLE
unsetter Functions for values that supersede model defaults

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#383]
It's currently impossible to unset optional values that are empty by default

- [x] model.initialStates
- [x] model.initialStateSensitivities
- [x] model.plist_
- [x] ~model.fixedParameters~
- [ ] ~model.fixedParametersPreequilibration~
- [ ] ~edata.fixedParameters~
- [ ] ~edata.fixedParametersPreequilibration~
- [x] edata.ts

**Comment by dweindl** [comment]
Is it really necessary to have those? I suggest simply creating a new model instance with default values. If you know you will have to reuse some of those, keep a copy.

For ExpData the default would empty, not?

**Comment by FFroehlich** [comment]
How about introducing a formalism that we can pass either `nullptr` or and empty vector to the setter function to reset them?

Enabling those is important for e.g., the loop in `amici.cpp`
```
    auto originalFixedParameters = model.getFixedParameters(); // to restore after simulation
    auto originalTimepoints = model.getTimepoints();
    ...
    model.setFixedParameters(originalFixedParameters);
    model.setTimepoints(originalTimepoints);
```

because if `originalFixedParameters` or `originalTimepoints` are empty, the setter calls will fail due to bad model dimensions. I think this simply did not fail so far because they were always set in the test cases.

**Comment by dweindl** [comment]
I would avoid storing the default parameter inside the model. If they are overwritten, they are overwritten. They are available in a new instance if required.

`originalFixedParameters` should never be empty if nk>0. Can that currently happen?

For timepoints we can allow empty vectors to be set.

**Comment by FFroehlich** [comment]
Ah, I think I encountered the problem with `model.initialStates`, where it was not set in the beginning (which is fine as `model->fx0` will be used for initialization) and I could not unset it.

> originalFixedParameters should never be empty if nk>0. Can that currently happen?

you are right.

It's not so much about having default parameters in the model, but about looping over multiple experimental data and keeping the `Model` object in a consistent state. Always using deepcopies of `Model` would indeed be a solution, but doing this for every single simulation may add quite a bit of overhead.

> I would avoid storing the default parameter inside the model. If they are overwritten, they are overwritten. They are available in a new instance if required.

True, I think we agreed at some point that the state of `Model` transient and that it could be reused over simulation. Yet, this is a bit conflicting with the approach that we moved many things from `udata` into the model. As far as I can tell the current offenders, i.e. default values are

```
        /** unscaled parameters (dimension: np) */
        std::vector<realtype> unscaledParameters;

        /** orignal user-provided, possibly scaled parameter array (size np) */
        std::vector<realtype>originalParameters;

        /** constants (dimension: nk) */
        std::vector<realtype> fixedParameters;

        /** indexes of parameters wrt to which sensitivities are computed (dimension nplist) */
        std::vector<int> plist_;

        /** state initialisation (size nx) */
        std::vector<double>x0data;

        /** sensitivity initialisation (size nx * nplist, ordering = ?) */
        std::vector<realtype>sx0data;

        /** timepoints (size nt) */
        std::vector<realtype>ts;

        /** maximal number of events to track */
        int nmaxevent = 10;

        /** parameter transformation of `originalParameters` (dimension np) */
        std::vector<AMICI_parameter_scaling> pscale;

        /** starting time */
        double tstart = 0.0;
```

I would argue that most of them it actually makes sense to keep them there. For `plist_`, empty vectors actually alreay work. For the remaining ones, it would be great if this was actually possible.

For the attributes in edata that were mentioned above, being able to set them to empty is mostly about convenience that if multiple instances are created, they don't have to all be constructed from scratch or in a certain sequence.

**Comment by FFroehlich** [comment]
I think all I want is that object.set(object.get(...)) is guaranteed to roundtrip. We should probably add unittests to check this.

**Comment by dweindl** [comment]
> For the attributes in edata that were mentioned above, being able to set them to empty is mostly about convenience that if multiple instances are created, they don't have to all be constructed from scratch or in a certain sequence.

In ExpData they should be allowed to be empty, to indicate "don't override model settings". So the default constructor should also not allocate memory for them. I think in future we also want to use `ExpData` with actual measurements, but only to simulate for a range of conditions. Therefore, we should also allow `my`, ... to be empty. (And ask ourselves if that will still be the most descriptive name...) I think this would require a few more code changes, though.
