### ISSUE TITLE
[python] AssignmentRules for parameters (non-observables)

### ISSUE THREAD

**Issue by LoosC** [ICB-DCM/AMICI#384]
It should also be possible to include assignment rules for non-observables. So far, there is still the SBMLExpection:

`amici.sbml_import.SBMLException: Non-float parameter assignment rules are currently not supported!`

**Comment by FFroehlich** [comment]
Oh, I did not realize this but I think I fixed this at some point ;)

**Comment by dweindl** [comment]
In 653faddbe6ba437b912f7e4a2cfd4d96ecad37e9 (but not yet on pypi)

**Comment by FFroehlich** [comment]
oh, good point, I was anyways planning to make a new release after #448 is merged.

**Comment by FFroehlich** [comment]
@LoosC could you please check whether this is fixed now, new release should now be available on pypi

**Comment by LoosC** [comment]
yes it works :)
