### ISSUE TITLE
Gsl, codacy, c++14

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#393]
A couple of questions regarding general AMICI development:

- What do you think about introducing [gsl-lite](https://github.com/martinmoene/gsl-lite)? This would be especially interesting in terms of [`gsl::span`](https://stackoverflow.com/questions/45723819/what-is-a-span-and-when-should-i-use-one). It's a single-file header-only library.

- What do you think about using [C++14](https://en.wikipedia.org/wiki/C%2B%2B14#New_language_features)? Not super necessary, but a handful of convenience features. I don't think we would lose support for any platform on which amici is used at the moment.

- What do you think about adding static code analysis via [Codacy](https://github.com/marketplace/codacy) to our CI pipeline? It integrates nicely with github and posts code review comments automatically. Works for both Python and C++.

**Comment by FFroehlich** [comment]
> What do you think about introducing gsl-lite? This would be especially interesting in terms of gsl::span. It's a single-file header-only library.

sounds good!

>What do you think about using C++14? Not super necessary, but a handful of convenience features. I don't think we would lose support for any platform on which amici is used at the moment.

Hmm this would drop support for GCC4 and older, whats the situation on the HMGU servers? I remember they were running gcc 4.8 for a long time. As MATLAB now officially supports GCC 6.3, I don't see any issue.

> What do you think about adding static code analysis via Codacy to our CI pipeline? It integrates nicely with github and posts code review comments automatically. Works for both Python and C++.

I already set up codacy a while, just did not enable posting yet ;)

**Comment by dweindl** [comment]
> Hmm this would drop support for GCC4 and older, whats the situation on the HMGU servers? I remember they were running gcc 4.8 for a long time. As MATLAB now officially supports GCC 6.3, I don't see any issue.

gcc-4.9 should still work, this supports [a number of C++14 features](https://gcc.gnu.org/gcc-4.9/changes.html) and this has been the matlab default for quite some versions. hmgu servus have gcc-6.4.1.
Fine to wait for another year though.

**Comment by FFroehlich** [comment]
No I think then we are fine to move ahead.
