### ISSUE TITLE
ReturnData::x is set to NaN upon integration failure in CVodeB

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#396]
In case of integration failure in `CVodeB`, `ReturnData::x` is overwritten in https://github.com/ICB-DCM/AMICI/blob/71530631d9007fec8b2d50dc117682bc4d256bea/src/amici.cpp#L95

Is there a good reason to not keep the forward simulation result despite backwards integration failure?

**Comment by FFroehlich** [comment]
No.
