### ISSUE TITLE
[python] [sbml-import] Move species with constant=True to fixed parameters?

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#397]
Currently constant species are added to `x`. Do we want to keep that? Moving them from x to k would save resources...

**Comment by FFroehlich** [comment]
I think keeping them in `x` was primarily a matter of convenience, so the may very well be moved to `k`.

**Comment by dweindl** [comment]
Should we always do that or have that as an option?

This would apply to boundary conditions and constant species? Or all rows in the stoichiometric matrix with sum(abs((.))==0?

**Comment by dweindl** [comment]
I am not sure if we should do that during SBML-import. Maybe it is cleaner to provide a function to change that inside the sbml model (change constant states to parameters) prior to the import.
