### ISSUE TITLE
Read HDF5

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/AMICI#419]
Enable amici to understand our hdf5 data format for experimental data, pre-equilibration, fixed parameters etc.
As a first step, map from hdf5 to amici.ExpData. This will then be used in particular in pyPESTO (Objective / Problem) and for plotting.

Language: Probably python.
Related projects:
* Extend the amici.ExpData class to allow for multiple experimental conditions.

**Comment by dweindl** [comment]
@yannikschaelte I somehow missed this discussion on whether we want to use intermediary hdf5 files or not. Let's discuss that Monday morning.

This is what AMICI understands so far:
https://github.com/ICB-DCM/AMICI/blob/71d0f3dae284e28388dea84be2150bf4b860ac59/src/hdf5.cpp#L93

**Comment by yannikschaelte** [comment]
yes, just discussed with Leonard. Eventual goal is to easily use models - in particular the benchmark ones - in a standardized way for pypesto. Therefore all data somehow need to be passed to amici, maybe using hdf5 from the model files. How to do that in detail, we need to discuss :) .

**Comment by FFroehlich** [comment]
Be aware that I implemented support for pandas DataFrames in #418

**Comment by LeonardSchmiester** [comment]
- Regarding the models from the benchmark collection: I transformed the data of the Crauste, Fujita and Boehm model to our data format, created HDF5 files from that and was able to reproduce the simulation results reported in the Benchmark paper with the Matlab pipeline.

- Regarding the HDF5 files: as far as I remember from the last discussion, we wanted to use the experimental_table and cost_function tables as Inputs and use the HDF5 files that are created from these tables internally.

**Comment by dweindl** [comment]
One issue to keep in mind here is that to use amici hdf5 function, the user needs to have hdf5 libraries and header files available when building building the amici source distribution (which will be very annoying for windows users at least) or we need to provide the respective wheels.

**Comment by yannikschaelte** [comment]
you mean aside from h5py (which is easily installed from pip or conda), one also needs the library files, installed on linux via ``apt install libhdf5-dev``, which would need an additional step on windows?

**Comment by dweindl** [comment]
Correct.

**Comment by yannikschaelte** [comment]
> @FFroehlich Be aware that I implemented support for pandas DataFrames in #418

Only for export, not dataframe2expdata yet, right?

**Comment by FFroehlich** [comment]
> Only for export, not dataframe2expdata yet, right?

Nope, also import: 
https://github.com/ICB-DCM/AMICI/blob/cdfb8166483a670f22e98cc4d00f4614b7a3a6c9/python/amici/pandas.py#L375

**Comment by dweindl** [comment]
Any new developments here? Still an issue?

**Comment by yannikschaelte** [comment]
there will certainly be issues on how exactly to make amici understand the income data format (using hdf5 or not), but this is not the case right now, so I'd say we can close this issue.
