### ISSUE TITLE
[newton] Use klu_refactor instead of repeatedly factorizing the problem de-novo

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#421]
We should be able to use `klu_refactor` instead of repeatedly using `klu_factor`, right?

see https://github.com/PetterS/SuiteSparse/blob/master/KLU/Source/klu_refactor.c

**Comment by paulstapor** [comment]
For doing so, we would need to at least once factor the Jacobian, before using KLU refactor, right?
Any good way to check whether KLU factor has already been performed?
Similarly: we don't need to go through symbolic analysis over and over again, right? Once perform, we could skip it on repetitions, I think?

**Comment by FFroehlich** [comment]
yes, https://users.encs.concordia.ca/~krzyzak/R%20Code-Communications%20in%20Statistics%20and%20Simulation%202014/Zubeh%F6r/SuiteSparse/KLU/Doc/KLU_UserGuide.pdf is pretty helpful with this

**Comment by FFroehlich** [comment]
If `NewtonSolverSparse::sparse` and `NewtonSolverSparse::numeric` are non-null these functions have already been called. Should be straightforward to implement.
