### ISSUE TITLE
[CI, python] Windows support

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#424]
Since we unfortunately decided to support Windows, it would be great if somebody could reenable/setup [AppVeyor ](https://www.appveyor.com/). This would also be helpful for the generation, and required for the auto-deployment of Windows wheels (#423).

**Comment by dweindl** [comment]
@yannikschaelte : Wanna give it a try? :)

**Comment by FFroehlich** [comment]
https://brew.sh/2019/02/02/homebrew-2.0.0/ this might simplify dependency installation on windows a bit.

**Comment by FFroehlich** [comment]
Closing this due to lack of interest and https://docs.microsoft.com/en-us/windows/wsl/install-win10 as better alternative.

**Comment by dweindl** [comment]
@thomassligon : Since you seem to be very interested in using AMICI with Visual C++, would you be able to set up a CI workflow for that? Otherwise, since none of the developers is using VC++, chances are high that future changes will break compatibility...

**Comment by thomassligon** [comment]
That sounds reasonable, especially since the installation on Windows with Visual Studio seems to be almost working, as soon as a one-line fix becomes available, but first I need to understand what is expected. My guess is that "CI workflow" means "continuous integration workflow", but that is a very general concept and I don't know exactly what is expected. In particular, does this refer to a tool and managing the workflow in that tool? In addition, I don't know Appveyor, Windows wheels, or travis, so I might need to learn some of this, or, at least, know what a "CI workflow" needs to look like. PS: AMICI on Windows with Visual C++ was working for MATLAB, and using it with Python has uncovered one line of incompatible code, and there is already a fix for that, but it is not yet in master.

**Comment by dweindl** [comment]
Hi Tom,

Our current continuous integration workflow, among others, builds AMICI and installs the Python package and then runs and verifies a number of test simulations. This currently happens on travis CI. See https://travis-ci.com/ICB-DCM/AMICI/jobs/232096602 for an example, and https://github.com/ICB-DCM/AMICI/blob/master/.travis.yml for how this is achieved.

There are different providers with free basic subscriptions and decent github integrations. At some point we used appveyor, see https://github.com/ICB-DCM/AMICI/blob/master/bu_.appveyor.yml for the broken configuration. 

Options are:
* https://www.appveyor.com/
* https://www.shippable.com/windows.html
* https://docs.travis-ci.com/user/reference/windows/
* https://github.com/features/actions.
* and probably others. 

I no Windows-experience with any of them and no clear preference.

The minimum we would need is:
- [ ] Setting up the environment (python, VC++)
- [ ] Performing the AMICI development installation

Ideally in addition:
- [ ] Running the example Jupyter notebooks from `python/examples/`

We won't be able to test the matlab interface, due to licensing restrictions.

Regarding the pull request with fixes for your current issues: I commented on that earlier, should be merged soon. That was waiting due to me being on vacation.

**Comment by thomassligon** [comment]
Hi Daniel,

I plan to take the following next steps:
As soon as the one-line change in solver_cvodes.cpp, I will continue testing “pip install amici” on my configuration.
After that is working, I plan to compare my experience with Yannik’s in hopes of learning a few key points.
Also, I will look at the travis documentation you have cited, and maybe the others, with the goal of seeing how much work it would be to create the CI workflow that is needed.

Tom
(Dr. Thomas S. Ligon)
Tom@thomassligon.info<mailto:Tom@thomassligon.info>
Frohnloher Str. 6a
81475 Muenchen
Germany
Tel. +49(89)74575075

**Comment by dweindl** [comment]
> Also, I will look at the travis documentation you have cited, and maybe the others, with the goal of seeing how much work it would be to create the CI workflow that is needed.

Okay, great. Therefore reopening this issue.
