### ISSUE TITLE
Confirm that sensitivities are computed correctly for replicate measurements

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#433]
Confirm that sensitivities are computed correctly for replicate measurements -> See discussion in #262 

Ideally add a test case to one of the existing models.

**Comment by dweindl** [comment]
Is anybody currently using that or has anybody ever looked into that?

**Comment by FFroehlich** [comment]
I am currently using it (not replicates, but equal conditions+timepoint  but differing non-NaN observables, should not matter though) and it seems to be working (FSA).
