### ISSUE TITLE
more information from CVODE(S)

### ISSUE THREAD

**Issue by thomassligon** [ICB-DCM/AMICI#438]
I am looking for some advice on the best way to get more information from CVODE. 

1. Should I compile with symbols and use a debugger?
2. Should I find a way to make stack trace work on Windows?
3. Would it be reasonable to implement an options.verbose and enhance CVODE to include a bit more data?

Here is an abbreviated version of some typical error messages. My questions are enclosed in ().
**Warning: AMICI simulation failed at t = 1.556988:**
AMICI failed to integrate the problem
**(It would be nice to know which reaction caused the problem.)**
Error occured in:
stacktrace not available on windows platforms
In simulate_ASTHMA_V40_M07 (line 206)
(some lines deleted)
**Warning: AMICI encountered a NaN value at index 0 of 268 in residual function! Trying to recover ...**  
**(It would be nice to know what the residual function looks like at this point, and what index 0 is.)**
In simulate_ASTHMA_V40_M07 (line 206)
(some lines deleted)
**Warning: AMICI encountered a NaN value at index 4 of 295 in w! Trying to recover ...**  
**(It would be nice to know what w looks like at this point, and what index 4 is.)**
In simulate_ASTHMA_V40_M07 (line 206)
(some lines deleted)
**Warning: AMICI simulation failed at t = 0.000000:**
AMICI failed to integrate the problem
**(It would be nice to know which reaction caused the problem.)**
Error occured in:
stacktrace not available on windows platforms
In simulate_ASTHMA_V40_M07 (line 206)

By the way, "occurred" has 2 "r"s.

Does the stack trace give us any of this information? In the worst case, it just shows us which routines of CVODE have been called, but what we need is the data..

Just in case, here is some more information about the stack. Of course, it is easy to access the stack on Windows. The problem is that it would require additional code, and the options don't look nice. AMICI uses the "backtrace" API, which was defined in POSIX (or earlier), and is available on Unix, Linux, and OSX (which runs on a Unix kernel). In Windows, it would be possible to use the Windows "StackWalk" API, but that has some disadvantages. It would require compiling with debug symbols, which makes the object larger and a bit slower, and it would require coding extra logic since the interface is not the same as "backtrace".
Then it looked like the Windows Subsystem for Linux (WSL) might be a good idea, since it is very easy to activate (just a configuration setting), and enables all Unix/Linux APIs on Windows. However, unfortunately, it does not make it possible to call Linux APIs from Windows programs. What it does is make it very easy to install Linux directly on Windows, without using a virtual machine or dual boot, making it very efficient to run Linux on Windows, and exchange data directly between Windows and Linux. For AMICI, that doesn't add anything new, except another way to run Linux. In case anyone is interested, here is some more discussion:
https://github.com/Microsoft/WSL/issues/3448#issuecomment-411453195

**Comment by FFroehlich** [comment]
Hey Tom,

I don't think backtraces would help you a lot with the problem you encountered as the respective exceptions are not thrown in the piece of code that led to the described problems. 

However, you can use the info provided to figure out what is going wrong:

> Warning: AMICI encountered a NaN value at index 0 of 268 in residual function! Trying to recover

means that there is some problem in the right hand side, which is encoded in `_modelname__xdot.cpp`.  "index 0" means that the problem is in the formula `xdot[0]`. Most likely the problem is not directly visible in `xdot[0]`, but `xdot[0]` depends on `w[4]` or `w4` which already contains a NaN value:

> Warning: AMICI encountered a NaN value at index 4 of 295 in w! Trying to recover ...

means that there is some problem in the expression vector w, which is encoded in `_modelname__w.cpp`.  "index 4" means that the problem is in the formula `w[4]`. NaNs are typically caused by divisions 0/0 or by pow(a, e), where a is negative and e is non-integer.

**Comment by thomassligon** [comment]
Hi Fabian,
your answers are very helpful. Finally, I know what the residual function and w mean and how to use them. This helped me understand where all error messages except the first one come from. The first error happens during preequibiliation (without newton), and caused the program to hand a list of NaNs to the next simulation in options.x0. That makes all the remaining error messages clear.
In order to understand the first error, failure after a certain time, I simulated to a slightly smaller time and analyzed the results. I can see that it is caused by something I originally saw in Copasi, and now I need to go back and look at it more closely. The problem is caused by reactions that include 2 substrates, which might be the same. When both go slightly below zero, it then amplifies the error, until the state has a large negative value. I will continue my discussion with Jan, Leonard and Paul, and we might decide to write a new AMICI issue for it.
