### ISSUE TITLE
Arbitrary data-types as constants?

### ISSUE THREAD

**Issue by ciropom** [ICB-DCM/AMICI#442]
Hello I'm trying to migrate my matlab model to AMICI but my integrating function takes several non-scalar parameters (structures, cell arrays, matrices)

how can I pass these kind of elements to an AMICI function?

so far I have

```
function [model] = test()
syms state1 state2 state3
model.sym.x = [state1,state2,state3];
x = [state1,state2,state3];
model.sym.p = [ ];
syms k const1 const2 cm
model.sym.k = [k const1 const2 cm ];
syms t
model.sym.xdot = tt(t, k, [const1,const2], x, cm);
model.sym.x0 = [ 1, 0, 0 ];
model.sym.y(1) = x(1)-x(2);
model.sym.y(2) = x(3)-x(2);
```

but k, const1, const2, behave like single values, while they are matrices.
Also is it possible to define 
model.sym.x as a single vector instead of a list of state variables? because I have hundreds of state variables and I don't want to name them all.

Thanks
Danilo

**Comment by FFroehlich** [comment]
Hi Danilo,

> but k, const1, const2, behave like single values, while they are matrices.

The way you instantiate the symbolic variables `k`, `const1`, `const2` and `cm` will create scalar symbolic variables. For information on how to create matrices, check https://www.mathworks.com/help/symbolic/syms.html

Note that `model.sym.k` has to be a vector, so you will have to linearize those matrices in the end.

> Also is it possible to define
model.sym.x as a single vector instead of a list of state variables? because I have hundreds of state variables and I don't want to name them all.

Is `model.sym.x = sym('state',[1 100])` what you are looking for?

**Comment by ciropom** [comment]
Hello and thank you for your answer.

> Note that model.sym.k has to be a vector, so you will have to linearize those matrices in the end.
OK

> Is model.sym.x = sym('state',[1 100]) what you are looking for?

Not really. I want to access my state array in a loop and if I name all the elements I can't do that.

Loops and if statements are allowed?

Thank you
Danilo

**Comment by FFroehlich** [comment]
Hi Danilo,

> Not really. I want to access my state array in a loop and if I name all the elements I can't do that.

I don't understand your question. Using the above definition, you can access elements in  `model.sym.x` programmatically using `model.sym.x(ix)`

 > Loops and if statements are allowed?

`model.sym.xdot` must contain a symbolic expression. What you do in `tt(t, k, [const1,const2], x, cm)` is up to you, but the function `tt` must return symbolic variablers. These symbolic variables may contain conditional expressions (these must be encoded via heaviside or any of the symbolic functions in https://github.com/ICB-DCM/AMICI/tree/master/matlab/symbolic). 

If the specified ODE contains loops and conditional expressions, simply using the rhs function that was passed to matlab solvers such as ode15s will NOT work.

**Comment by ciropom** [comment]
Ok it's clear now. thanks.
