### ISSUE TITLE
Warning: AMICI ERROR: in module CVSLS in function cvKLUSetup : A call to an external package failed. 

### ISSUE THREAD

**Issue by thomassligon** [ICB-DCM/AMICI#444]
I am sometimes getting this error. Why should a call to an external package fail, unless there is an error in compiling the mex? But that reported no errors.

How can I debug the problem? Do need a more verbose amiwrap report, or do I need to debug the mex executable?

Error during simulation:
Warning: AMICI ERROR: in module CVSLS in function cvKLUSetup : A call to an external package failed.  
Warning: AMICI ERROR: in module CVODES in function CVode : At t = 37309.7, the setup routine failed in an unrecoverable manner.  
Warning: AMICI forward simulation failed at t = 37309.729416:
AMICI failed to integrate the forward problem

Report after amiwrap:
Warning: AMICI does not officially support Microsoft Visual Studio Compilers. If the compilation fails, we recommend using MinGW. 
> In amiwrap (line 22)
  In optimize_ASTHMA_V40_M07 (line 70) 
amiwrap version 71d0f3dae284e28388dea84be2150bf4b860ac59
Generating model struct ...
Parsing model struct ...
p | x | k | xdot | w | dwdx | J | JB | JDiag | JSparse | JSparseB | Jv | JvB | root | drootdx | sx | drootdp | drootdt | sroot | deltax | deltaxdot | ddeltaxdx | ddeltaxdp | ddeltaxdt | dtaudp | stau | deltasx | xB | deltaxB | dwdp | dxdotdp | z | dzdp | dtaudx | dzdx | qBdot | sxdot | dzdt | sz | xBdot | sparse | sparseB | 
Generating C code ...
J | JB | JDiag | JSparse | JSparseB | Jv | JvB | dwdp | dwdx | dxdotdp | qBdot | sxdot | w | xBdot | xdot | CMakeLists | swig | main | 
Compiling mex file ...
ffuns | Building with 'Microsoft Visual C++ 2017'.
MEX completed successfully.
wrapfunctions | Building with 'Microsoft Visual C++ 2017'.
MEX completed successfully.
linking | Building with 'Microsoft Visual C++ 2017 (C)'.
MEX completed successfully.
Generating M code ...
Elapsed time is 321.236918 seconds.

**Comment by thomassligon** [comment]
OK, I'll assume that the error message doesn't mean what it says, but instead that KLU factorization failed. Thanks for the help.

**Comment by FFroehlich** [comment]
The message does mean what it says, KLU is an external package and the call to a function in that external package failed, i.e., threw an error.
