### ISSUE TITLE
simulate_ runs overtime

### ISSUE THREAD

**Issue by thomassligon** [ICB-DCM/AMICI#445]
I am calling simulate_ with tout=[0;60;180;540] but then I get the error:
Warning: AMICI forward simulation failed at t = 2011045.451891:
AMICI failed to integrate the forward problem

Why does simulate_ run for more than 540?

Just in case, here are the options:
options = 

  amioption with properties:

                  atol: 1.0000e-08
                  rtol: 1.0000e-08
              maxsteps: 1000
             quad_atol: 1.0000e-12
             quad_rtol: 1.0000e-08
             maxstepsB: 0
              sens_ind: []
                tstart: 0
                   lmm: 2
                  iter: 2
                linsol: 9
                stldet: 1
            interpType: 1
                   ism: 1
            sensi_meth: 2
                 sensi: 1
             nmaxevent: 10
              ordering: 0
                    ss: 0
                    x0: [268×1 double]
                   sx0: []
       newton_maxsteps: 0
    newton_maxlinsteps: 100
          newton_preeq: 0
               z2event: []
                pscale: 2

**Comment by thomassligon** [comment]
PS: This seems to occur only if the third parameter in simulate_, the data, is set. If it is empty, and tout is a vector (not just a scalar), simulate_ doesn't run past tout.

**Comment by dweindl** [comment]
> PS: This seems to occur only if the third parameter in simulate_, the data, is set. If it is empty, and tout is a vector (not just a scalar), simulate_ doesn't run past tout.

I guess `amidata.conditionPreequilibration` was not empty. Was it?

**Comment by thomassligon** [comment]
True:

The call looks like this:
                    sol = self.simulate(t, pSim, k, d, options);

Here is d:
d = 

  amidata with properties:

                           nt: 4
                           ny: 3
                           nz: 0
                           ne: 10
                           nk: 55
                            t: [4×1 double]
                            Y: [4×3 double]
                      Sigma_Y: [4×3 double]
                            Z: [10×0 double]
                      Sigma_Z: [10×0 double]
                    condition: [55×1 double]
    conditionPreequilibration: [55×1 double]

Here is d.conditionPreequilibration:
K>> d.conditionPreequilibration

ans =

           0
           0
           0
           0
        1580
        4160
        3950
        3210
        5210
        4580
        1370
        1470
        1320
        4790
        2950
        1050
        1000
        1580
         530
        1100
        1160
        1210
        2420
         580
        3890
        4160
        4000
         530
           0
        1210
        1320
        5260
        1370
         530
        1890
        1630
        1530
         530
           0
         580
         530
         630
         530
         530
         580
         530
           0
           0
           0
           0
           0
           0
           2
           2
           2

**Comment by dweindl** [comment]
> Why does simulate_ run for more than 540?

Setting `amidata.conditionPreequilibration` implies asking for preequilibration. The time to reach equilibrium is inpedendent of your `tout` and in this case takes longer than that.

**Comment by thomassligon** [comment]
Now I can see that I have no need for conditionPreequilibration (at the moment). Since we are not using Newton, but finding preequlibrium by simulating to tout=1e4, we only need condition (but set to the vector that we previously used for conditionPreequilibration). With that simulation is running well without integration errors.
