### ISSUE TITLE
Change symbolic library?

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#449]
I am not sure wether symengine was a good pick as symbolic library as even simple things such as parsing still contain some serious bugs. Would be interesting to see how well sympy performs compared symengine as syntax difference should be minimal.

**Comment by FFroehlich** [comment]
For future reference: in libsbml `varj.getFormula()` may yield strings containing expressions such as `pow(x, -1)` which symengine brilliantly evaluates to `-1 + 1/x`. To avoid this, we have to use `formulaToL3String(var.getMath())` which yields `x^(-1)` which is correctly parsed by symengine.
The other problem was described in #381 .

**Comment by dweindl** [comment]
Sympy would have the benefit of better documentation... No clue about performance differences.
