### ISSUE TITLE
How to change the options regarding the solvers

### ISSUE THREAD

**Issue by FloBru** [ICB-DCM/AMICI#459]
Dear all,

thank you very much for AMICI. I would like to use your tool and Matlab for my master thesis. 
I have questions regarding the use of SUNDIALS solvers CVODES. How can I change the solvers in the options of the simulation and which solvers of CVODES can be used? How can I change the settings for the solvers, for example the step size?
Sorry, I could not find it in the documentation. Thank you in advance!

**Comment by FFroehlich** [comment]
Hi,

CVODES only offers a single solver. You can change the linear multistep method or the nonlinear iteration method, but the defaults are usually good choices.

CVODES is an adaptive solver, so you cannot change the step-size as it it automatically determined from tolerances. All options that you can pass to the simulation routine should be documented in the generated simulation `.m` file.
