### ISSUE TITLE
PyTorch Solver

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#466]
Might be interesting to implement an interface to this:

https://github.com/rtqichen/torchdiffeq

**Comment by JanHasenauer** [comment]
Do you think that odeint() reaches a performance similar to CVODES?

**Comment by FFroehlich** [comment]
I only had a very superficial look at the code, but they claim that they can offload the code to GPUs and it sounded like they were using implicit solvers.
