### ISSUE TITLE
Model.clone() does not copy `steadyStateSensitivityMode`

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#469]

**Comment by FFroehlich** [comment]
same for `Solver.absoluteToleranceSensi` and `Solver.relativeToleranceSensi`

**Comment by FFroehlich** [comment]
same for `Model.reinitializeFixedParameterInitialStates`

**Comment by FFroehlich** [comment]
We _need_ better unit tests for this (probably best testable in python as dynamic member access is tricky in c++)

**Comment by dweindl** [comment]
That's why I started getting rid of explicit copy constructors. Don't implement tests, change the class that the default copy constructor does the correct job.
