### ISSUE TITLE
Simplify building python AMICI with OpenMP

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#473]
- [ ] Check for available compiler
- [ ] Compile test file to see if OpenMP supported
- [ ] Set respective flags automatically (see https://github.com/astropy/astropy-helpers/blob/master/astropy_helpers/openmp_helpers.py)
- [ ] For package installation
- [ ] And model building

**Comment by dweindl** [comment]
With the more sophisticated handling of compiler options, we could now probably add the respective flags more easily. Shall we try enabling OpenMP by default? At least for compiler class `unix`?

**Comment by FFroehlich** [comment]
sounds good. for osx suitable flags are 
```
AMICI_CXXFLAGS="-Xpreprocessor -fopenmp"
AMICI_LDFLAGS="-Xpreprocessor -fopenmp -lomp"
```
should be available by default.

**Comment by dweindl** [comment]
> should be available by default.

@FFroehlich : On travis `libomp` is not. So maybe safer to not enable by default?

**Comment by FFroehlich** [comment]
Ah turns out its apparently not installed by default, I just happened to have it installed. Most common installation is via `brew install libomp`, which should place a symlink for `libomp.a` and `libomp.dylib` in `/usr/local/lib`
