### ISSUE TITLE
Unscale default parameters

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#477]
For models generated from pysb/sbml, default parameters (from pysb/sbml) set at model initialization are not unscaled according to parameter scaling.

**Comment by dweindl** [comment]
Not sure I understand.

Parameter scaling is linear at initialization time when SBML-parameter are set to the model.

Then you change parameter scaling and parameters are not updated?

**Comment by FFroehlich** [comment]
> Then you change parameter scaling and parameters are not updated?
 Yes, I think that is whats happening.

**Comment by dweindl** [comment]
I can't reproduce or don't understand.

Using `python/examples/example_steadystate/ExampleSteadystate.ipynb`:

```
model = model_module.getModel()
print(model.getParameters())
```
> (1.0, 0.5, 0.4, 2.0, 0.1, 2.0, 3.0, 0.2)

```
print(model.getUnscaledParameters())
```
> (1.0, 0.5, 0.4, 2.0, 0.1, 2.0, 3.0, 0.2)
```
model.setParameterScale(amici.ParameterScaling_log10)
print(model.getParameters())
```
> (1.0, 0.5, 0.4, 2.0, 0.1, 2.0, 3.0, 0.2)
```
print(model.getUnscaledParameters())
```
> (10.0, 3.1622776601683795, 2.51188643150958, 100.0, 1.2589254117941673, 100.0, 1000.0, 1.5848931924611136)

Besides "getUnscaledParameters" maybe being a somewhat confusing name, I think that is what I expected to happen.

**Comment by dweindl** [comment]
Ah, you mean that in this case, the outputs of `getUnscaledParameters()` and `getParameters()` should be swapped?

**Comment by FFroehlich** [comment]
After you change the parameter scaling, the output of `model.getUnscaledParameters()` should remain the same and the output of `model.getParameters()` should remain the same, not the other way around

**Comment by dweindl** [comment]
Yes, understood. Easy to fix. Does not only apply to parameters set during model initialization but at any time when parameter scaling is changed.
