### ISSUE TITLE
Order of the derivatives of the Sensitivity Analysis 

### ISSUE THREAD

**Issue by FloBru** [ICB-DCM/AMICI#483]
Hello all,

I have a question about the order of derivatives of the Jacobian matrix when you perform sensitivity analysis. 
You only get a long vector and no Jacobian matrix so my question is what is the order 
of the derivatives? I need to transform the vector into a Jacobian matrix so I need to know the 
order of the derivatives to arrange them into a matrix. 
Thank you in advance!

**Comment by FFroehlich** [comment]
Hi, sorry for the late reply. Are you using the python, matlab or c++ interface? Also the derivative of what with respect to what?

Unless you explicitely request second order derivatives, you will get first order derivatives.

**Comment by FloBru** [comment]
Hello,

no problem. I use the matlab interface. I want to use sol.sx to get the derivatives of the states with respect to the parameters. But you get only a vector and no matrix so my question is how to transform the vector into a matrix which is like the Jacobian matrix:

(dstate1)/(dparameter1)  (dstate1)/(dparameter2) .... (dstate1)/(dparameterm)
...                                          ....                                          ...
(dstaten)/(dparameter1) (dstaten)/(dparameter2) .... (dstaten)/(dparameterm)

My questions is how the derivatives of the states with respect to the parameters are ordered?
Thank you in advance!

**Comment by FFroehlich** [comment]
`sol.sx` has the dimensions [time,state,parameter] so for (dstate_i)/(dparameter_j) you would have to look at `sol.sx(:,i,j)`.
