### ISSUE TITLE
Change Parameters During Events?

### ISSUE THREAD

**Issue by FloBru** [ICB-DCM/AMICI#485]
Hello all,

is it possible to change parameters during an event or can you only change the states when an event is performed? Like:
event A --> change parameter1 = 1.0  to parameter1 = 2.0
Is this possible? 
Thank you in advance!

**Comment by paulstapor** [comment]
Hi FloBru,

only changes of states are possible. However, if you want to encode something like this, you might introduce a new state, which has to time-evolution and is just updated on the event.

Best,
Paul

**Comment by FFroehlich** [comment]
The problem is that if you change a parameter in an event, it's not really well defined how the respective sensitivity behaves in that situation.

**Comment by ramosone** [comment]
could this be a solution?
One can create a variable
syms var1
var1=am_if(condition,1,2)
one example of condition is using another AMICI function: am_ge(something,0)
while the 'something' is greater than 0 for example var1 is 1, after 'something'  is equal or lower than 0, var1 is 2
Whenever using parameter1, one could multiple it with var1

**Comment by FFroehlich** [comment]
Definitely.

We strictly interpret parameters as quantities that we want to dynamically vary outside of simulation (in, e.g., MCMC/Optimization). Accordingly, changing these values during a simulation is not a well defined operation (both numerically and philosophically). In general, other software tools/modeling languages may not follow this strict definition, but as you pointed out, introducing secondary variables that dynamically change during the simulation is a good way to resolve this conflict.
