### ISSUE TITLE
newline does not exist in older MATLAB releases

### ISSUE THREAD

**Issue by CsatiZoltan** [ICB-DCM/AMICI#493]
`amimodel.compileAndLinkModel>getCompilerVersionString` fails because it contains the `newline` function which was introduced in [R2016b](https://fr.mathworks.com/help/matlab/ref/newline.html). Replacing it by `char(10)`, as recommended in the link above, fixes the problem.

**Comment by FFroehlich** [comment]
Hi, thank you for the remark. We generally recommend using more recent MATLAB versions as keeping backwards compatibility in MATLAB is just impossible as long as third party platforms such as travis.org do not allow automated testing. Unfortunately, we currently only support MATLAB up to R2017b.

**Comment by dweindl** [comment]
Is guess I can quickly fix that. Only one single occurrence and fix won't affect upward or download compatibility.
