### ISSUE TITLE
warning for creation of symbolic variables

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#50]
Currently matlab produces the warning:

Warning: Support of character vectors that are not valid variable names or define a number will be removed in a future release. To create
symbolic expressions, first create symbolic variables and then use operations on them.

This will require changing lots of code and is likely going to break many things in one of the next MATLAB releases.

**Comment by paulstapor** [comment]
Maybe a good moment to think about ginac...
