### ISSUE TITLE
Remove code that ignores multiple @param section warnings from doxygen

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#507]
https://github.com/ICB-DCM/AMICI/commit/dce9bbcf97b9bbbe08757de63180de93f8d8496c#diff-54abb0898515f76fa9c5e3a8082ce275

is to be reverted as soon as 

https://github.com/doxygen/doxygen/issues/6754

is fixed.

**Comment by FFroehlich** [comment]
should be fixed now, https://github.com/doxygen/doxygen/issues/6754#event-2544178143

**Comment by dweindl** [comment]
Not fixed in my doxygen 1.8.17

**Comment by FFroehlich** [comment]
I am just checking this and I think its a different issue that produced multiple parameter sections

**Comment by SteveBronder** [comment]
@FFroehlich looking at fedfbca79e13f5f706566540d6af7e2da6aea601 can you clarify what the fix was? It looks like remove [in] and only documenting some specific versions of functions? Getting this same error after updating doxygen for stan math and not sure how past me goofed up

**Comment by FFroehlich** [comment]
> @FFroehlich looking at [fedfbca](https://github.com/AMICI-dev/AMICI/commit/fedfbca79e13f5f706566540d6af7e2da6aea601) can you clarify what the fix was? It looks like remove [in] and only documenting some specific versions of functions? Getting this same error after updating doxygen for stan math and not sure how past me goofed up

Hmm, not so sure what we actually did here. 

On the one hand fedfbca79e13f5f706566540d6af7e2da6aea601 removes a workaround that was necessary to avoid false posititives from https://github.com/doxygen/doxygen/issues/6754 which led to issues when a @param and a @retval had the same name in doxygen versions prior to `1.8.16`. On the other hand we moved a couple of docstrings from source files to header files, which might have had an effect, but I'm not so sure about that.

**Comment by dweindl** [comment]
> On the other hand we moved a couple of docstrings from source files to header files, which might have had an effect, but I'm not so sure about that.

Not sure anymore, but it might have been about having documentation for both function declaration and function definition.

**Comment by SteveBronder** [comment]
Word, thanks!
