### ISSUE TITLE
Core Dump Feature

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#517]
For debugging, it would be great to have a "core dump" functionionality. This should contain

- [ ] contents of all vectors in model.
- [ ] integration step-points extracted from the solver.

Both of these things could be extracted after the failure occured, so the user can take of the when and ifs. Anything else missing?

**Comment by dweindl** [comment]
On the core level, easiest would to implement that by means of serializing Model, Solver, ExpData. However, serialization is currently neither available in Python nor in Matlab.

**Comment by FFroehlich** [comment]
will not work since solve doesnt store full history.
