### ISSUE TITLE
Get simulation time as output of solver

### ISSUE THREAD

**Issue by paulstapor** [ICB-DCM/AMICI#524]
If we want to study the influence of the system size on computation time, it might be good to have computation time as an additional output of the C++ code of AMICI. This would be more rigorous for small-scale models than using tic, toc in Matlab or similar python functionality around solver calls. For the Newton solver, we already have that.

Should I introduce that for the ODE solve as well (it would hep me, at least)?
And if so, how to handle the preequilibration then? Get the time after preequilibration only, or also before?

**Comment by dweindl** [comment]
> It depends a little bit on the question you want to ask. For practical purposes, the interface overheads are actually relevant and should be considered

I second that. Not sure which models you will consider exactly, but to really get an idea about scaling, there would be quite a few where the overhead becomes negligible. If you really want to time individual model functions, there will be a few code changes necessary... A overall timing of the AMICI call you can implement outside AMICI, but I can see the convenience of having it reported automatically.

**Comment by paulstapor** [comment]
The idea behind is that we have the project with our Hiwi Philipp, who had a look at the influence of model size, linear solver, tolerances etc. on computation time. 

This is currently done for 345 models of of the biomodels database (for all curated models, for which sbml2amici and amiwrap works without trouble). It's currently done in Matlab (since events are supported here) and time is taken outside Amici. Unsurprisingly, there are many small models which have a significant overhead over the pure ODE solve, which you see when you look at the scaling of cpu-time over number of state variables. 

When doing such a study, it might however be interesting to get an idea of the pure ODE-solve scaling behavior, since this is more reliable when being extrapolated towards bigger models. So reporting it is not only for convenience reasons, it's simply to answer another scientific question.

So, the question is to some degree as well: Would you be interested in the results of such a study, which differentiates between these two types of cpu times (outside and inside Amici)? Or do you rather find that not worth being investigated?

**Comment by dweindl** [comment]
Since the result will anyways be quite implementation and solver dependent, I would go more practice-oriented. If the models are so small that computation time seems almost independent of model size and is dominated by overhead, then I would rather try to include larger models to get meaningful results.
The goal would be predict/understand scaling of larger models mostly, I guess?
