### ISSUE TITLE
Speed up compilation

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#537]
For me it seems as if compilation of `JSparse` (10 min) and `JSparseB` (13 min) can take excessively long compared to `J` (<1min) and `JB` (<1min) for large models (~15k nonzero entries). The main difference is `indexvals` and `indexptrs`, might be worthwhile to put them in a seperate function. Did anybody have a similar experience?

**Comment by dweindl** [comment]
I am having trouble with wrapfunctions.cpp and other files containing large amounts of data, especially with Intel C++ compiler. Turning of compiler optimizations saves close to 1h in some cases. For JSparse(B) it might be worth testing the runtime impact of not optimizing...
