### ISSUE TITLE
Update sundials to 4.x.x

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#545]
We are using `2.6.2, August 2015`. In this version adjoint sensitivities are not thread-safe. On first glance, this is  fixed in the current version and would be worth an update (this is not only relevant for https://github.com/ICB-DCM/parPE/, but also for https://github.com/ICB-DCM/pyPESTO/ and OpenMP support in AMICI).

Other interesting updates:
- CVodeSetConstraints should allow for handling non-negativity constraints, making our workaround superfluous

Not sure how more effort it will take, but willing to invest some time.

**Comment by FFroehlich** [comment]
Pretty sure we are at least using v2.8.0 as KLU was not available in v2.6.2. Still, I agree that we should upgrade at some point. Probably not too much work.

**Comment by dweindl** [comment]
> Pretty sure we are at least using v2.8.0 as KLU was not available in v2.6.2.

Okay, INSTALL_GUIDE.pdf says 2.7.0, Readme says 2.6.2, although it already has 2.7.0 in the release history, CMakeLists.txt says 2.6.0, include/sundials/sundials_config.h says 2.6.1. That is another reason to update.

**Comment by FFroehlich** [comment]
okay I'll start working on this, might take a little while as the interfaces seem to have changed substantially.

**Comment by FFroehlich** [comment]
fixed in 122da546bfb72d597de139ab6686f3de61c54aa4
