### ISSUE TITLE
Event firing at initial timepoint

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#55]
Event triggers that are 0 at timepoint t=t0 should fire their respective events before simulation starts. 6595513 only throws errors in trivial examples, but should be removed once fixed.

**Comment by JanHasenauer** [comment]
If the simulation starts at initial time t = -1 and the event fires at t = 0, does everything work properly?

**Comment by JanHasenauer** [comment]
Okay, I just checked and even of the initial time is negative the simulation results are different (= incorrect).

**Comment by FFroehlich** [comment]
t0 is passed at simulation time which makes this problem a bit hard to tackle but the check is currently performed at compile time. At the moment it should not be possible to define an event which fires at t=0.

**Comment by JanHasenauer** [comment]
the model with heaviside(t) compiled without error (Version from 5 days ago). Only the simulation was completely off compared to heaviside(t-1e-8).

**Comment by FFroehlich** [comment]
I cannot reproduce :( that problem. For me any model with `heaviside(t)` fails in makeEvents and produces the following error:
> The trigger of event 1 fires at initial timepoint t0 = 0, which is currently not supported.

which version of MATLAB are you using? maybe this is a problem with the symbolic toolbox.

**Comment by JanHasenauer** [comment]
My fault. I compiled wit heaviside(t-k) and set later the input k = 0. This compiles (as no k is specified) but provides later an incorrect solution.

**Comment by FFroehlich** [comment]
okay I implemented the check at run-time, which means the model can now always be compiled and simulation will always be stoppend when started in a root. This could be extended in the future to automatically check in which the crossing is, but I really do not see a good reason to start a simulation in an event. (Also this can always be fixed by the user by specifying an earlier t0).
