### ISSUE TITLE
Exception handling in AMICI

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#552]
Closely related to #328, but opening a new issue.

It would be very helpful to (have the option to) catch AMICI exception in the calling function and not already in `runAmiciSimulation`. Currently this would require some funny string parsing to programmatically figure out what went wrong. For example, I might want to adjust specific tolerances during optimization if something went wrong. Therefore I need to know where they occurred. This is much clearer from `IntegrationFailureB` than from parsing the message string.

I would therefore suggest to add a `rethrow=False` flag to `runAmiciSimulation`. @FFroehlich What do you think?

**Comment by FFroehlich** [comment]
sounds good.

**Comment by dweindl** [comment]
Related: Currently `llh` and `chi2` are set to `NAN`upon `IntegrationFailureB`. Can't we retain that?

**Comment by FFroehlich** [comment]
Agreed, thats not good. Lets split https://github.com/ICB-DCM/AMICI/blob/9c34570b8d4a3fa351fd2e351d12895208833c65/src/rdata.cpp#L159.
