### ISSUE TITLE
Dimension mismatch when writing rdata->newton_numsteps to matlab results

### ISSUE THREAD

**Issue by liweiyap** [ICB-DCM/AMICI#560]
Hi there

I think there might be a possible bug in the file AMICI/matlab/@amimodel/compileAndLinkModel.m. There should be an ellipsis at the end of line 186.

A second problem I ran into whilst using the __Matlab interface__: Previously, in version 0.8.1, I was able to compile my model using amiwrap, and this returned as output the simulate_${MODELNAME}.m, which I could call without getting any error. However, now, in __version 0.9.1__, although I can still compile my model using amiwrap, running the resulting output simulate_${MODELNAME}.m generates the following error:
```
'Unexpected Standard exception from MEX file.↵What() is:Dimension mismatch when writing rdata->newton_numsteps to matlab results↵..'
```

This error is thrown from line 210 in AMICI/src/returndata_matlab.cpp. As I'm not sure what I happening, I had to post this issue.

Other details:
 * macOS Mojave (version 10.14.2)
 * Clang++ compiler (Apple LLVM version 10.0.0, clang-1000.11.45.5, Target: x86_64-apple-darwin18.2.0)
 * Matlab version R2017a

**Comment by paulstapor** [comment]
Hi,

thanks for pointing out. I'll have a look into that!

Best,
Paul

**Comment by dweindl** [comment]
Pretty sure related to #527 where ReturnData::newton_numsteps and ReturnData::newton_numlinsteps changed, but wasn't adapted in ReturnDataMatlab. Thanks for looking into that Paul.

**Comment by liweiyap** [comment]
Thanks all for your kind assistance!! :)
