### ISSUE TITLE
Automatic Deployment to pypi still not working

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#572]
See https://travis-ci.org/ICB-DCM/AMICI/builds/486266021

Looks like `twine` is not in the path, even after installing. Looks like `PATH=/Users/travis/Library/Python/3.7/bin` is only applied for osx builds

**Comment by FFroehlich** [comment]
@dweindl where do we expect python binaries for linux builds?

**Comment by dweindl** [comment]
This is a pyenv (which we only use on linux) issue when installing new packages coming with anything in `bin/`. I hope fa616fdb808547062251465663461fc533124221 fixes it.

**Comment by FFroehlich** [comment]
Oh right. I don't think we actually need to be in a pyenv for twine. Isn't it easier if we just `deactivate` and add the default python path?

**Comment by dweindl** [comment]
Works now https://travis-ci.org/ICB-DCM/AMICI/jobs/491563709
