### ISSUE TITLE
Allow for context-specific printErrMsgIdAndTxt

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#576]
This is currently global. When running AMICI multi-threaded, this can get messy. Would be great to pass a custom output function as an argument to runAmiciSimulations.

**Comment by ramosone** [comment]
By the way on matlab this multi-threaded warning can be disabled.
1 - open the parpool ---> parpool(Nworkers)
2- run pctRunOnAll warning('off','all')

You will get no warnings related related to CVODES failure and so on
To enable warning back on pctRunOnAll warning('on','all'), see doc on pctRunOnAll  and warnings
