### ISSUE TITLE
Optimize ReturnData->ndarray

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#581]
For large matrices this still takes ages. sx0 with 2M entries takes minutes.

**Comment by dweindl** [comment]
This issue was introduced with getting rid of `DoubleVector`s. The current way is somewhat more convenient. You can set the contents directly (e.g. `print(x)` instead of `print(list(x))`. However, all `std::vector`s are currently converted to `tuple`. From then on they are not contiguous in memory anymore. That makes copying of large vectors extremely costly.

What do we prefer? I'd actually prefer a couple of `list(.)`s or `np.array(.)`s here and there instead of spending seconds to minutes for copying matrices.

**Comment by dweindl** [comment]
The ideal option would be returning everything as `numpy.array` directly. This will involve some non-trivial swigging. Would be cool in the longer run. For short-term I'd go for `DoubleVector`.
If we'd use multidimensional arrays already in AMICI core, it would also be comparably easy to return everything as numpy arrays with correct dimensions.

**Comment by dweindl** [comment]
@FFroehlich Any thoughts on that?

**Comment by FFroehlich** [comment]
Ideal solution for this is that as soon as `https://github.com/ICB-DCM/AMICI/pulls` is done, we no longer export all results to the solver, but instead copy the solver object to rdata and permit the dynamic computation of quantities of interest. This has multiple advantages:

- plotting of trajectories at arbitrary time resolutions
- less overhead when dealing with results that are in any way "large"
- easier debugging when integration fails as we could have access to full solver trajectory.
- generally cleaner interface for model/solver/rdata

**Comment by dweindl** [comment]
Okay, sounds good, but no matter where the data is coming from exactly, we still need to get them from C++ to Python.

**Comment by FFroehlich** [comment]
but you could implement those fields as views, i.e. they are only computed when requested.
