### ISSUE TITLE
Channel output to screen

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/AMICI#591]
Would it be possible to, when using the python interface, have warnings like

> [Warning] AMICI:mex:CVODES:CVode:ERR_FAILURE: AMICI ERROR: in module CVODES in function CVode : At t = 115.946 and h = 9.47311e-06, the error test failed repeatedly or with |h| = hmin. 
[Warning] AMICI:mex:simulation: AMICI forward simulation failed at t = 115.945988:
AMICI failed to integrate the forward problem

not appear on standard output, but be channeled e.g. to file? The reason is that there tend to be many of these, clouding the output from important messages. I don't know if that is possible already. One way would be to define different layers like debug/info/warning/error, as in the python logging framework, and only display higher-rated ones per default Might not be possible from C++ though.

**Comment by dweindl** [comment]
You can redirect stdout yourself. Besides that, there is currently no customizable "logging framework" in use, but would be nice to have (#576).

**Comment by yannikschaelte** [comment]
ah ok. hadn't seen that issue.

closed in favor of #576
