### ISSUE TITLE
Defining simulation options directly in C++?

### ISSUE THREAD

**Issue by liweiyap** [ICB-DCM/AMICI#602]
Hi

I'm planning on using the C++ interface of AMICI for my project and was wondering how to specify the amici integration options in C++ directly, rather than via hdf5 files? Is hdf5 the only way (as implied in INSTALL.md)? I assume there is a class allowing me to define amioptions manually but am unable to find it. 

Thanks in advance for the clarification.

**Comment by dweindl** [comment]
Hi @liweiyap,

You don't need to use HDF5 files. You can directly set all options on [amici::Solver](http://icb-dcm.github.io/AMICI/classamici_1_1_solver.html) and [amici::Model](http://icb-dcm.github.io/AMICI/classamici_1_1_model.html).
You can also have a look at [this Python example](https://github.com/ICB-DCM/AMICI/blob/master/python/examples/example_steadystate/ExampleSteadystate.ipynb), most of the `solver.set*` and `model.set*` are the same in C++.

Hope that helps.

**Comment by liweiyap** [comment]
It works! Thanks!!
