### ISSUE TITLE
SBML import breaks if parameters are named e.g. v0

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#604]
... because of macro redefinition. For example: 
`p.h`
```
#define v0 p[21]
```

`v.h`
```
#define v0 v[0]
```

Possibly affects other letters as well.

**Comment by dweindl** [comment]
More precisely: It does not fail to import and build, but it will lead to questionable results. Compilation warnings should be turned into errors in addition to fixing this.

**Comment by FFroehlich** [comment]
lets rename `v` in `v.h` to something less ambiguous like `hessProdVec`?

**Comment by dweindl** [comment]
Sounds good.

**Comment by dweindl** [comment]
Maybe worth starting a "reserved symbols" list somewhere.

**Comment by FFroehlich** [comment]
fixed in 5dfee11897a36b834d3922d1fbcf185ff283963d
