### ISSUE TITLE
DataFrame export: Have an option to use the id for observables as column headers

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/AMICI#607]
In https://github.com/ICB-DCM/AMICI/blob/master/python/amici/pandas.py#L8 (``amici.pandas.getDataObservablesAsDataFrame(model, edata_list)``, observable names are used as column headers. Since we use that in pypesto, it would be good to have an option ``use_ids=True`` or sth like that to use the observable ids instead.

In addition, one could think about using the id also when the name is empty ("").

**Comment by yannikschaelte** [comment]
implemented id usage in https://github.com/ICB-DCM/AMICI/blob/fix_edata_to_df/python/amici/pandas.py

Default behavior should not have changed since default value is to use names.

Please feel free to optimize/modify the code, since I do not know what else these functions are used for, so as not to destroy intended behavior :)

**Comment by dweindl** [comment]
I am not using them currently, but find it very reasonable to allow for choice between id/name. And empty names should be handled appropriately (multiple nameless entities would currently override each other, right?). Feel free to create a pull request.

Leaving further points to @FFroehlich

**Comment by yannikschaelte** [comment]
There is a check in ``_get_names_ord_ids`` whether the names are unique, so shadowing of '' names should not be possible. If no unique names can be created, an error seems to be thrown.

**Comment by FFroehlich** [comment]
Aren't we currently automatically using ids when names are non-unique? Yet, I have also come to the conclusion that the current implementation is not very intuitive and agree it should be changed. I am traveling for the next few days, will have a look next week.

**Comment by yannikschaelte** [comment]
Yes, but here we have just one observable, and it has name '', so it is still unique.

**Comment by yannikschaelte** [comment]
implemented in #608
