### ISSUE TITLE
List of publications using AMICI

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#624]
Would be nice to show on the landing page...

**Comment by dweindl** [comment]
For a start:
https://www.sciencedirect.com/science/article/pii/S0022519318305484
https://iopscience.iop.org/article/10.1088/0266-5611/32/12/125009/meta
https://academic.oup.com/bioinformatics/article/33/7/1049/2769435
https://academic.oup.com/bioinformatics/article/34/24/4266/5053308
https://academic.oup.com/bioinformatics/article/34/13/i151/5045760
https://www.sciencedirect.com/science/article/pii/S2405896316327999
https://academic.oup.com/bioinformatics/article/35/5/830/5078478
https://www.biorxiv.org/content/10.1101/579045v1
https://www.cell.com/cell-systems/fulltext/S2405-4712(18)30438-1

**Comment by FFroehlich** [comment]
https://www.biorxiv.org/content/10.1101/219188v1

**Comment by dweindl** [comment]
Maybe we add a `.bib` file from which we generate the markdown list automatically

**Comment by JanHasenauer** [comment]
Showing the publications would be very good! 
I will compile the list of our publications using AMICI

**Comment by paulstapor** [comment]
Also add:
https://bmcsystbiol.biomedcentral.com/articles/10.1186/s12918-017-0433-1
https://www.nature.com/articles/s41540-018-0079-7
https://academic.oup.com/bioinformatics/article/34/13/i494/5045751
https://www.sciencedirect.com/science/article/pii/S2405896318316823

And possibly also (I can not check...):
https://www.sciencedirect.com/science/article/pii/S0022247X18304414

**Comment by FFroehlich** [comment]
https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-019-2630-y

**Comment by JanHasenauer** [comment]
@dweindl Thanks for setting it up!

Now, we have to improve the formatting and keep it up-to-date.
Organisation by years?

**Comment by dweindl** [comment]
Done, by year https://github.com/ICB-DCM/AMICI/blob/references/documentation/references.md
