### ISSUE TITLE
AMICI logo

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#628]
Would be great to have a cool logo for AMICI to be used in presentations... Any ideas?

**Comment by mirzazulfan** [comment]
Hi @dweindl ,, I've designed a logo, what do you think? if you need something else please let me know.
![amici](https://user-images.githubusercontent.com/36124339/53853746-4d6e6d80-3ff9-11e9-8f68-93e120fb7f49.png)

**Comment by dweindl** [comment]
Hi @mirzazulfan , great, thanks a lot for your effort for designing those logos. We will discuss and get back to you soon.

**Comment by mirzazulfan** [comment]
Okay. Thanks for your response. :)
