### ISSUE TITLE
Error in example_dirac on staging

### ISSUE THREAD

**Issue by paulstapor** [ICB-DCM/AMICI#63]
Error using symengine
The dimensions do not match.

Error in sym/privBinaryOp (line 937)
            Csym = mupadmex(op,args{1}.s, args{2}.s, varargin{:});

Error in  *  (line 270)
        X = privBinaryOp(A, B, 'symobj::mtimes');

Error in amifun/getSyms (line 499)
            this.sym = diff(model.fun.root.sym,'t') +
            model.fun.drootdx.sym*model.fun.xdot.sym_noopt;

Error in amimodel/getFun (line 48)
        [fun,this] = fun.getSyms(this);

Error in amimodel/checkDeps (line 38)
                this.getFun([],deps{id});

Error in amimodel/getFun (line 22)
                cflag = this.checkDeps([],fun.deps);

Error in amimodel/checkDeps (line 38)
                this.getFun([],deps{id});

Error in amimodel/getFun (line 25)
                    cflag = this.checkDeps([],fun.deps);

Error in amimodel/checkDeps (line 38)
                this.getFun([],deps{id});

Error in amimodel/getFun (line 25)
                    cflag = this.checkDeps([],fun.deps);

Error in amimodel/parseModel (line 154)
    this.getFun(HTable,funs{ifun});

Error in amiwrap (line 73)
    model.parseModel();

Error in example_dirac (line 7)
amiwrap('model_dirac','model_dirac_syms',exdir)

====================================
For some reason, model.fun.xdot.sym_noopt is empty...

**Comment by FFroehlich** [comment]
gimme a sec
