### ISSUE TITLE
Get variable names or ids if the list is (correctly) empty raises Error in pandas.py

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/AMICI#636]
Example: The Boehm model has no fixed parameters. Since we fixed an error which was only testing for ObservableIds but not {variable}Ids, this throws an error, in https://github.com/ICB-DCM/AMICI/blob/master/python/amici/pandas.py#L381.

**Comment by yannikschaelte** [comment]
fixed in #637

**Comment by FFroehlich** [comment]
please don't close issues unless commits are merged to master, in this case this should hopefully be done automatically.

**Comment by yannikschaelte** [comment]
ah ok, makes sense. thanks!
