### ISSUE TITLE
Include symbol names in simulation results

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#64]
I would find it very helpful to have the names of the model species from the model_*_syms file included in the simulation results.

It would also be nice to be able to get a list of the symbol names for the fixed and variable parameters of the compiled model. Not sure where to put them, though.

**Comment by FFroehlich** [comment]
I totally agree. I think it would make sense to restructure the return struct a bit. Things like integration steps, newton solves etc could be moved to an subfield which is a statistics struct. 
We could then add additional structs for "input" and "names".

**Comment by dweindl** [comment]
Sounds good.

Maybe a call to simulate_model_* without arguments could return some model information (parameter and state names and order, number of parameters/events/..., ...). This would allow to verify whether a certain compiled model matches a given *_syms file without rewrapping/recompiling.

**Comment by FFroehlich** [comment]
hmm i think it would be much easier to simply add the hash of the syms file to the header of the (MATLAB) simulation routine, this is already done with the amici git version but not with the syms file

**Comment by dweindl** [comment]
Won't add names to simulation results, but make them available via `Model`
