### ISSUE TITLE
Memory leak in AmiVector Array

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#645]
Apparently swig is unable to find the destructor of `AmiVectorArray`. Only happens in `testCPP`:
```
swig/python detected a memory leak of type 'AmiVectorArray *', no destructor found.
swig/python detected a memory leak of type 'AmiVectorArray *', no destructor found.
swig/python detected a memory leak of type 'AmiVectorArray *', no destructor found.
```

**Comment by dweindl** [comment]
Unclear to me when/why that happens. Somewhere around `getattr(model, 'dxdotdp')`, but I had trouble reproducing that in other contexts. I seem to remember that such things occurred when incompatible libraries were combined, but that shouldn't happen during travis run...

**Comment by FFroehlich** [comment]
I tried to expose `AmiVector` and `AmiVectorArray` via swig and ran into trouble due to incompatibilities in the destructor, so this might be a real problem. Problems with `dxdotdp` would actually make sense since it's an `AmiVector`. 

Swig is returning the following for `dxdotdp`: 
```
resultobj = SWIG_NewPointerObj((new AmiVectorArray(static_cast< const AmiVectorArray& >(result))), SWIGTYPE_p_AmiVectorArray, SWIG_POINTER_OWN |  0 );
```
But that does look fine to me.

**Comment by dweindl** [comment]
> I tried to expose `AmiVector` and `AmiVectorArray` via swig and ran into trouble due to incompatibilities in the destructor, so this might be a real problem. Problems with `dxdotdp` would actually make sense since it's an `AmiVector`.
> 
> Swig is returning the following for `dxdotdp`:
> 
> ```
> resultobj = SWIG_NewPointerObj((new AmiVectorArray(static_cast< const AmiVectorArray& >(result))), SWIGTYPE_p_AmiVectorArray, SWIG_POINTER_OWN |  0 );
> ```
> 
> But that does look fine to me.

Yes that line looks fine.


However, `    ~AmiVectorArray() = default;` seems not take care of `std::vector<N_Vector> nvec_array;` properly. We'd need to run `N_VDestroy_Serial` over that. Somewhat surprised, that valgrind did not complain there.

**Comment by dweindl** [comment]
Did see that happening anywhere recently. Closing.
