### ISSUE TITLE
Custom "llh" for Python SBML import

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#646]
Via the matlab interface one can provide custom formulas for `Jy`. Would be good to also specify some way to do that in Python to allow for different error models, etc. 

Currently, this is hard-coded in `python.amici.sbml_import.SbmlImporter.processObservables` as `llhYString`. We could allow passing that as `observables[.]['llh']`, and defaulting to the current value if empty.

Any opinions?

**Comment by yannikschaelte** [comment]
fixed via #656
