### ISSUE TITLE
UserData::am_sensi and UserData::am_sensi_meth

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#65]
In [/include/udata.h](https://github.com/ICB-DCM/AMICI/blob/master/include/udata.h)
>    /** flag indicating whether sensitivities are supposed to be computed */
    int am_sensi;

>    /** method for sensitivity computation */
    /*!
     * CW_FSA for forward sensitivity analysis, CW_ASA for adjoint sensitivity analysis
     */
    int am_sensi_meth;

Is there a need for having both UserData::am_sensi and UserData::am_sensi_meth? 

If I understood correctly, am_sensi is either <= 0, meaning no sensitivities are to be provided and am_sensi_meth = 1...3 determines the method. 
Then am_sensi seems to be rather redundant, since am_sensi_meth = 0 implies am_sensi = 0. Removing it would prevent potential inconsistencies (just found mine...).

PS: However, there exist a few
> if(sensi>1) {

e.g. https://github.com/ICB-DCM/AMICI/blob/master/src/amici.cpp#L1253
Is there a different meaning to sensi == 1 and sensi > 1?

**Comment by FFroehlich** [comment]
UserData::am_sensi specifies the sensitivity order (second order sensitivities via sensi == 2 and directional second order sensitivities via sensi == 3) and UserData::am_sensi_meth switches between forward and adjoint sensitivity analsysis.

**Comment by dweindl** [comment]
Thanks for clarifying!
