### ISSUE TITLE
Update to sundials 5.2.0

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#679]
See https://computation.llnl.gov/sites/default/files/public/cv_guide-dev.pdf

**Comment by dweindl** [comment]
Released https://github.com/LLNL/sundials/releases/tag/v5.0.0

**Comment by FFroehlich** [comment]
> Fixed a bug in CVODES where CVodeF would return the wrong flag under certain circumstances.
> 
> Fixed a bug in CVODES where CVodeF would not return a root in NORMAL_STEP mode if the root occurred after the desired output time.

Those are changes that are relevant for us that we are currently fixing on our own. With this fixed, we no longer need to provide our own sundials implementation. `Solver::resetState` and `Solver::reInitPostProcess` still use private sundials API from `cvodes_impl.h`/`idas_impl.h` though.

**Comment by dweindl** [comment]
There is 5.2 meanwhile

https://github.com/LLNL/sundials/releases/tag/v5.2.0

**Comment by FFroehlich** [comment]
Lets update after #1002 is done

**Comment by dweindl** [comment]
Sounds good
