### ISSUE TITLE
Import error with species Id "RR"

### ISSUE THREAD

**Issue by LeonardSchmiester** [ICB-DCM/AMICI#714]
I tried to import a model with the species Id "RR" which led to the error:
`amici.sbml_import.SBMLException: Kinetic law "compartment * (K1 * R^2 - Dimerize_k2 * RR)" contains an unsupported expression!`

Apparently, RR is already reserved in sympy.

**Comment by dweindl** [comment]
`RR` is interpreted as `sympy.polys.domains.realfield.RealField`. Not completely sure if this is a feature or bug in sympy.

**Comment by FFroehlich** [comment]
Can we work around that by explicitely instantiating ‘sympy.Symbol(“RR”)’?

**Comment by dweindl** [comment]
`sp.sympify("1 * RR", locals={'RR': sp.Symbol('RR')})` does the trick. Maybe we should use `locals` by default in all sympifications.

**Comment by dweindl** [comment]
@LeonardSchmiester : Can you please test if this is resolved by #718?
