### ISSUE TITLE
am_max throws error [Matlab2018b]

### ISSUE THREAD

**Issue by jvanhoefer** [ICB-DCM/AMICI#722]
If I am calling `am_max(a, b)` in MATLAB-AMICI I get the error message

>Character vectors and strings in the first argument can only specify a variable or number. To evaluate character vectors and strings representing symbolic expressions, use 'str2sym'. 

 wich is thrown in line 10 of am_max. I tried replacing sym by str2sym, but that did not reslove the problem.

**Comment by FFroehlich** [comment]
I suppose this is related to #307
