### ISSUE TITLE
new publication using amici

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#727]
add 
https://www.biorxiv.org/content/10.1101/690222v1.abstract

**Comment by dweindl** [comment]
- https://www.biorxiv.org/content/10.1101/690222v1

- Upcoming: Lines et al "Efficient computation of steady states in large-scale ODE models of biochemical reaction networks"

**Comment by dweindl** [comment]
Replace Fischer2017 by https://www.nature.com/articles/s41587-019-0088-0

**Comment by dweindl** [comment]
Done in cae005c6b0e00c993548bc02d634c7beb6f42ea1. Create new issues for new publications.
