### ISSUE TITLE
Running SBML test suite as travis-ci cron job failing since months?

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#731]
See https://travis-ci.com/ICB-DCM/AMICI/builds

To be checked if problem persists with updated `master`.

**Comment by FFroehlich** [comment]
Number of tests is too big. needs to be split into multiple jobs

**Comment by dweindl** [comment]
In some cases, yes. But many failures occurred even before any test was run.

**Comment by FFroehlich** [comment]
lets replace this cronjob by https://github.com/features/actions (should have 6h runtime which should hopefully be enough for the whole testsuite)

**Comment by dweindl** [comment]
Sounds good. Nice first test as we finally got beta access...

**Comment by dweindl** [comment]
Closed in #789
