### ISSUE TITLE
Python SBML import: add support for SBML RateRules

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#732]
Currently AMICI SBML import does not support `RateRules`. Would be nice to have, e.g. for #654.

**Comment by matthiaskoenig** [comment]
Yes, RateRules are important and using these often.

Also is there somewhere a list of SBML things which are supported/not supported in AMICI? E.g., can you handle 
- variable compartment sizes?
- events?

**Comment by FFroehlich** [comment]
Thats a good point. Currently things that are not supported will throw an error, but there is no comprehensive list (Should be straightforward to compile from the implemented error messages).

RateRules should be super straightforward to implement.

Events are a little bit more involved but @paulstapor mentioned that he wanted to work on that.

Variable compartment sizes are currently not supported. They key thing that needs to be handled to implement that is that volumes need to become state variables. With state reduction implemented this is now straightforward as we could directly apply it if no volume dynamics are added.

**Comment by dweindl** [comment]
Support for rate rules has been added a while ago in #1036. Closing.
