### ISSUE TITLE
Python SBML import: add support for compartment assignment rules

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#763]

**Comment by cemale** [comment]
This addition would definitely be very useful, biologically relevant, and necessary. I would very much appreciate making the compartment size variable (i.e. dependent on a specific species amount).

**Comment by FFroehlich** [comment]
Hmm, I believe @matthiaskoenig was also interested in this feature. Shouldn't be too difficult to implement this, so I will give this a try.

**Comment by matthiaskoenig** [comment]
Yes, definitely interested. I have a few models with variable compartment sizes (i.e. `constant=false` compartments and assignment rules which calculate the compartment sizes. Only normal assignment rules no rate rules).
This should not be too complicated to implement. Depending on if volumes are set via
- rate rule (`dv/dt=rule`), a new state variable must be tracked
- assignment rule (`v=rule` , depending on state variables), a derived quantity must be calculated from state variables, parameters, ...

If you have any questions about the SBML part let me know.

**Comment by dweindl** [comment]
Support for compartment assignment rules has been added a while ago in #1036. Closing.
