### ISSUE TITLE
Python SBML import: add support for floor() ceil()

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#765]

**Comment by FFroehlich** [comment]
Floor and ceil are not differentiable and thus incompatible with sensitivity analysis.

**Comment by yannikschaelte** [comment]
But abs is also not differentiable, and we still do it anyway, right? For floor and ceil it could just be 0 everywere except integers, where the gradient is not defined.

**Comment by FFroehlich** [comment]
Technically yes, but for `abs`, the gradient is informative for all values where the function is differentiable, so a local approximations are sensible and we can have at least some hope that a gradient based method will work.

For floor and ceil local approximations don't do a particularly good job and the gradient will not be informative about the function shape (as long as intervals bigger than 1 are considered).

I wouldn't spend too much time on trying to help people to shoot themselves in the foot.
