### ISSUE TITLE
SIMULATION ERROR in step function when the defined time for the step is zero

### ISSUE THREAD

**Issue by elbaraim** [ICB-DCM/AMICI#772]
I found this error in **MATLAB-AMICI**, not sure whether it is reproducible in **PYTHON-AMICI**.
May be worth checking.

I am trying to simulate the Weber_BMC2015 model from the benchmark collection in MATLAB-amici. This model contains some step functions, e.g.: `u2 = heaviside(t-0)*Ect_Expr_PKD_flag` which also could be written as `u2 = am_piecewise(Ect_Expr_PKD_flag,t-0,0)`.
When I come to simulate the model I get the following error:
`AMICI is stuck in an event, as the initialstep-size after the event is too small. To fix this, increase absolute and relative tolerances!`
I tried doing that, increasing values of `atol` and `rtol` (many different values), but still fails.

Additional:
When `options.ami.tstart = 0` I get the error
`AMICI setup failed: (Simulation started in an event. This could lead to unexpected results, aborting simulation! Please specify an earlier simulation start via options.t0)`
therefore I changed its value to `options.ami.tstart = -10` (arbitrary chosen) still, the error persists.
`AMICI is stuck in an event, as the initialstep-size after the event is too small. To fix this, increase absolute and relative tolerances!`

**Comment by FFroehlich** [comment]
Sounds like that model is numerically difficult to simulate. Solutions to discontinuous right-hand-sides are not necessarily well defined. Changing atol and rtol can help, but thats not guaranteed.

**Comment by FFroehlich** [comment]
In what version of AMICI did this problem appear? We introduced some changes in 0.10.8 which fixed some similar problems for me (the same can happen with preequilibration + change of fixed parameters)

**Comment by elbaraim** [comment]
so far I am using the version from commit `4da5dd993b2c0e14bcebc3445201f3c178510b98`

**Comment by dweindl** [comment]
> so far I am using the version from commit `4da5dd993b2c0e14bcebc3445201f3c178510b98`

Hint: When pasting commit hashes omit backticks, then they are rendered as links. Like so: 4da5dd993b2c0e14bcebc3445201f3c178510b98 :)

**Comment by FFroehlich** [comment]
@elbaraim whats the status of this?

**Comment by FFroehlich** [comment]
closing stale issue
