### ISSUE TITLE
cblas.cpp cannot open cblas.h

### ISSUE THREAD

**Issue by thomassligon** [ICB-DCM/AMICI#802]
`pip install amici `
fails because cblas.cpp cannot open cblas.h.
The code in cblas.cpp is
`#include "amici/cblas.h"

#ifdef __APPLE__
#include <Accelerate/Accelerate.h>
#elif defined(AMICI_BLAS_MKL)
#include <mkl.h>
#else
extern "C"
{
   #include <cblas.h>
}
#endif`
There are two include statements for cblas.h, which does not make sense, and the second is missing the directory amici. A quick fix would be to replace
   #include <cblas.h>
by
   #include <amici/cblas.h>
However, it doesn't make sense to call the same include twice. This looks very much like a case of code that was never finished. The logic says that if we do not have APPLE and we do not have AMICI_BLAS_MKL, then we should repeat the include for cblas.h. Why?

**Comment by thomassligon** [comment]
The compiler error disappeared after CBLAS was installed, indicating that
#elif defined(AMICI_BLAS_MKL)
now returns true, which invokes
 #include <mkl.h>
instead of
extern "C"
{
#include <cblas.h>
}
As a result, I don't need a solution now, but the logic is still false.

**Comment by FFroehlich** [comment]
`"amici/cblas.h"` and `<cblas.h>` refer to different files.

`"amici/cblas.h"`, as indicated by the surrounding `"`, is user-defined header provided by AMICI (see https://github.com/ICB-DCM/AMICI/blob/master/include/amici/cblas.h).
`<cblas.h>, as indicated by the surrounding `<`, is a system header provided by the installation of the respective MKL (see https://github.com/ICB-DCM/AMICI/blob/master/INSTALL.md#dependencies)

The missing `cblas.h` is a strong indication that the linking does not work properly (see https://github.com/ICB-DCM/AMICI/issues/781). It is likely that the respective header has a different name and is thus not found during compilation. Could you please tell us what operating system you are using and which implementation of cblas, openblas, atlas, mkl etc it provides?

**Comment by thomassligon** [comment]
OK, after installing CBLAS, the error disappeared, and I don't need to understand the logic of 
extern "C"
{
#include <cblas.h>
}
