### ISSUE TITLE
cvodes:impl.h missing 

### ISSUE THREAD

**Issue by thomassligon** [ICB-DCM/AMICI#804]
I cloned a copy of AMICI from Github.
AMICI/src/solver_cvodes.cpp line 10 is:
#include <cvodes/cvodes_impl.h>
but this file is not included in
AMICI/ThirdParty/sundials/include/cvodes

**Comment by FFroehlich** [comment]
`cvodes/cvodes_impl.h` is only generated after installation of cvodes.

To manually install CVODES, please use the script https://github.com/ICB-DCM/AMICI/blob/master/scripts/buildSundials.sh

**Comment by thomassligon** [comment]
The problem is solved. cvodes_impl.h ist NOT included in
AMICI/ThirdParty/sundials/include/cvodes
It IS included in
AMICI/ThirdParty/sundials/src/cvodes

**Comment by FFroehlich** [comment]
Ah correct `cvodes/cvodes_config.h` will only be generated after installation, `cvodes_impl.h` should always be available.
