### ISSUE TITLE
syntax error in solver_cvodes.cpp line 68

### ISSUE THREAD

**Issue by thomassligon** [ICB-DCM/AMICI#805]
Question: Is this easy to avoid? My (superficial) understanding is that "__attribute__" is not a C++ standard feature, but something specific to GNU compilers. Visual Studio has had greatly improved compatibility with the ISO standard and Linux since VS 2017, and I am using VS 2019. It looks like "__declspec" in VS is equivalent.

When I run
pip install amici
and also when I run
pip install --global-option="build_clib" --global-option="build_ext" amici --verbose
I get a syntax error in AMICI\src\solver_cvodes.cpp line 68.
(Just FYI, compiler finds cvodes_impl.h in AMICI\ThirdParty\sundials\src\cvodes, a directory that I didn't have on the include path in a previous test.)

Here is line 67-68:
`static int fJDiag(realtype t, N_Vector JDiag, N_Vector x, void *user_data)
__attribute__((unused));`

"__attribute__" appears to be a GNU-specific keyword. Here is a very old discussion, and I'm not sure what the current status is. 
[https://stackoverflow.com/questions/19249521/attribute-macro-and-its-effect-on-visual-studio-2010-based-projects](https://stackoverflow.com/questions/19249521/attribute-macro-and-its-effect-on-visual-studio-2010-based-projects)
This discussion says that Visual Studio "__declspec" is equivalent to GCC "__attribute__".
[https://stackoverflow.com/questions/8290177/what-is-the-equivalent-of-v4sf-and-attribute-in-visual-studio-c](https://stackoverflow.com/questions/8290177/what-is-the-equivalent-of-v4sf-and-attribute-in-visual-studio-c)

documentation for error code C3646 unknown override specifier
[https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c3646?view=vs-2019](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c3646?view=vs-2019)

Now I copied the compiler command, including the errors, from the output, and modified it slightly. This is exactly the compiler command created by Python pip install, but with the directories completed so that I can run it in a standalone command window.

`“C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\cl.exe” /c /nologo /Ox /W3 /GL /DNDEBUG /MT -IC:\data\Tom\Research\AMICI/include -IC:\data\Tom\Research\AMICI/ThirdParty/SuiteSparse/KLU/Include/ -IC:\data\Tom\Research\AMICI/ThirdParty/SuiteSparse/AMD/Include/ -IC:\data\Tom\Research\AMICI/ThirdParty/SuiteSparse/COLAMD/Include/ -IC:\data\Tom\Research\AMICI/ThirdParty/SuiteSparse/BTF/Include/ -IC:\data\Tom\Research\AMICI/ThirdParty/SuiteSparse/SuiteSparse_config/ -IC:\data\Tom\Research\AMICI/ThirdParty/SuiteSparse/include -IC:\data\Tom\Research\AMICI/ThirdParty/sundials/include -IC:\data\Tom\Research\AMICI/ThirdParty/sundials/src -IC:\data\Tom\Research\AMICI/ThirdParty/gsl/ "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /TpC:\data\Tom\Research\AMICI\src\solver_cvodes.cpp /Fobuild\temp.win-amd64-3.7\amici\src\solver_cvodes.obj -std=c++11 -IC:/data/Xinstall/BLAS/OpenBLAS-0.3.6-x64/include
…leads to…
cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
solver_cvodes.cpp
C:\data\Tom\Research\AMICI\src\solver_cvodes.cpp(68): error C3646: '__attribute__': unknown override specifier
C:\data\Tom\Research\AMICI\src\solver_cvodes.cpp(68): error C2059: syntax error: '('
C:\data\Tom\Research\AMICI\src\solver_cvodes.cpp(68): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\data\Tom\Research\AMICI\src\solver_cvodes.cpp(849): error C2084: function 'int amici::fJDiag(amici::realtype,N_Vector,N_Vector,void *)' already has a body
C:\data\Tom\Research\AMICI\src\solver_cvodes.cpp(67): note: see previous definition of 'fJDiag'
`

**Comment by thomassligon** [comment]
According to
[http://gcc.gnu.org/wiki/Visibility#How_to_use_the_new_C.2B-.2B-_visibility_support](http://gcc.gnu.org/wiki/Visibility#How_to_use_the_new_C.2B-.2B-_visibility_support)
It should be possible to use __declspec in GCC.
As an alternative, it can be in this kind of code:
 #ifdef __GNUC__
    #define DLL_PUBLIC __attribute__ ((dllexport))
 #else
     #define DLL_PUBLIC __declspec(dllexport) // Note: actually gcc seems to also supports this syntax.
 #endif

**Comment by FFroehlich** [comment]
I do not like using one non-standard language extension over the other, but I agree that __attribute is not standard C++11. It might be possible to use ``[[gnu::unused]]`` instead (see https://github.com/ICB-DCM/AMICI/pull/807/commits/48a9463b37e21f9e3e4a78bf16b260d9df62b288). If that does not work, it might be worthwile to look into why this function is actually unused.

**Comment by thomassligon** [comment]
As far as I can tell, the fix in #807?
[https://github.com/ICB-DCM/AMICI/commit/48a9463b37e21f9e3e4a78bf16b260d9df62b288](https://github.com/ICB-DCM/AMICI/commit/48a9463b37e21f9e3e4a78bf16b260d9df62b288)
  is working for me.
