### ISSUE TITLE
Deploy build artifacts

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#809]
Would be great to have build artifacts deployed somewhere. E.g. SBML test suite results for easy submission to database (#791). Also this would allow for easy retrieval of python packages from `develop` prior to release.

Couldn't find any free hosted artifact repositories, so a free S3 instance might be the easiest start. See e.g. https://docs.travis-ci.com/user/uploading-artifacts/

**Comment by FFroehlich** [comment]
What about github-pages?

**Comment by dweindl** [comment]
> What about github-pages?

1GB limit, we'd have to delete stuff quite regularly. While we have the documentation there, I'd keep that separate and only deploy things to github-pages on merge to master.

**Comment by dweindl** [comment]
Deployments from pull request commits are currently not possible with Travis-CI https://github.com/travis-ci/travis-ci/issues/5579 :-/. Would have to be implemented manually or from something non-travis.
