### ISSUE TITLE
Remove code for generating `JDiag` files during model import ?

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#814]
@FFroehlich : After removing `Model::fJDiag` in #807, there is not really a need to create those files during model import, right? That code could/should be removed then (Matlab + Python).

**Comment by FFroehlich** [comment]
Agreed. I think @paulstapor used this for preconditioning but apparently its no longer needed.

**Comment by paulstapor** [comment]
puh... good question.  I'm pretty sure we have good evidence that KLU substantially outperforms the iterative solvers... So we can indeed remove them, as nobody really wants to use them.

**Comment by dweindl** [comment]
As the respective function was unused, it was apparently not possible to use it for preconditioning so far. (Did that break during the last sundials update?). So either that needs to be repaired or removed completely. No opinion on that.

**Comment by paulstapor** [comment]
Honestly: rather remove, maybe even together with the support for the BiCGStab-Solver...
That's some hand-crafted legacy code, which looks really bad.

**Comment by paulstapor** [comment]
But wait a second... What exactly do you mean with "is not possible to use"?
It is used here:
https://github.com/ICB-DCM/AMICI/blob/50313ad30abbb4c9c23fcbd6cc9cda1b31ad2e7f/src/newton_solver.cpp#L233

**Comment by dweindl** [comment]
Ah, thanks, you are right. So then there was just a slightly different unused redefinition of `fJDiag`. That closes this issue.
