### ISSUE TITLE
Model::getInitialStates() return empty list

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#818]
When instantiating `Model` and calling `getInitialStates()`, this returns an empty vector. Not sure whether this is a bug, but I'd consider it at least unexpected behaviour. If initial states have not been set explicitly, this should in my opinion call `Model::initializeStates()` automatically. Other opinions?

**Comment by paulstapor** [comment]
I would agree, but I'm not aware whether or not this make break some functionality in some other place. If not, I would suggest to change it...

**Comment by yannikschaelte** [comment]
I think I stumbled across this some time ago and found it highly unintuitive.

**Comment by FFroehlich** [comment]
Sounds reasonable!
