### ISSUE TITLE
Compute state sensitivities within C++ code

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#82]
Move to C++ part. Use SuiteSparse and KLU.
```
if(options_ami.sensi_meth == 3)
    sol.sx = -sol.J\sol.dxdotdp;
    sol.sy = sol.dydx*sol.sx + sol.dydp;
end
```

**Comment by FFroehlich** [comment]
for sy part best use fsy, for linear solve use KLU with fJSparse as J typically is very sparse.

**Comment by paulstapor** [comment]
Best to do within the Newton solver framework?
