### ISSUE TITLE
Objective Function output

### ISSUE THREAD

**Issue by ramosone** [ICB-DCM/AMICI#836]
Hi,
How does one apply this default obj fun 'J = 1/2*sum(((y_i(t)-my_ti)/sigma_y_i)^2 + log(2*pi*sigma_y^2)'
and get the model.sym.Jy=J output?

I'm not sure if this J is automatically calculated or if we do it manually... If it is manually done what variables would y_i(t) and sigma_y_i  be inside the sym model, if we provide them when doing the simulation as in sol = simulate_modelname(t,theta,kappa,[y sigma_y],options)
thanks in advance :)

**Comment by dweindl** [comment]
Hi @ramosone,

As mentioned in the [AMICI Matlab documentation](https://icb-dcm.github.io/AMICI/matlab_interface.html): 

> By default, AMICI assumes a normal noise model and uses the corresponding negative log-likelihood
>
>J = 1/2*sum(((y_i(t)-my_ti)/sigma_y_i)^2 + log(2*pi*sigma_y^2)
>
>as objective function.

So if you leave `model.sym.Jy` unset, the above likelihood function will be used. After successfully running a simulation, the respective result will be available in `sol.llh`.

**Comment by ramosone** [comment]
Hi, Ty
Oh yeah the ReturnData  section... Sorry I should have tried harder... Was expecting sol.Jy 😅   Anyway with -1e6 its probably not a good sign

**Comment by dweindl** [comment]
Agreed that `Jy` might be more intuitive. Especially when using some custom non-likelihood `model.sym.Jy`...
