### ISSUE TITLE
Add Newton solver extensions

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#842]
Merge the Newton solver improvements from

G. T. Lines, @paszkow, L. Schmiester, D. Weindl, P. Stapor, and J. Hasenauer. Efficient computation of steady states in large-scale ODE models of biochemical reaction networks. accepted for Proceedings of the 8th IFAC Conference on Foundations of Systems Biology in Engineering (FOSBE), Valencia, Spain, October 2019.

**Comment by paulstapor** [comment]
Is an implementation of the continuation meant to be implemented as well, os is this rather something for pyPESTO? If not, I would consider this issue as closed...

**Comment by dweindl** [comment]
What is missing for that? We can already provide steady-state guesses, right? I would *not* track previous steadystate solutions within AMICI. That should be done somewhere outside, where there is more information on which solution to keep and which to drop.

**Comment by paszkow** [comment]
The entire continuation method is built on top of amici. The framework is used to compute steady-states only. The entire process of choosing "simpler" parameters and collecting data is up to users. Can be done either using C++ or python.
