### ISSUE TITLE
Quadratures in adjoint computation take extremely long for large models

### ISSUE THREAD

**Issue by paulstapor** [ICB-DCM/AMICI#849]
On the human cancer model, adjoint sensitivity computation takes much longer than expected (more than 100 times as long as expected, to be precise). The problem seems to be located in 
`amici::model_ODE::qBdot()`, or https://github.com/ICB-DCM/AMICI/blob/76162dfc09d74d439939ab92eac7a2f7b80f0873/src/model_ode.cpp#L316.

This is happening in AMICI 10.13, but going trough the AMICI history, I could spot that the code part in which 99% of the time is spent was added in #627. In there, more than 80% are spent in `Model_ODE::fdxdotdp`, https://github.com/ICB-DCM/AMICI/blob/76162dfc09d74d439939ab92eac7a2f7b80f0873/src/model_ode.cpp#L99, and in there again 90% are spent in `dxdotdw.multiply`.

I would suggest to restructure this part and handle dxdotdp and dwdp as sparse matrices (they should be sparse, as each reaction flux usually depends on one or two parameters). This should bring us back to computation speeds which we once had...

Any objections?

**Comment by FFroehlich** [comment]
This is not good. I remember that I wanted to make `dxdotdp` and `dwdp` sparse matrices, but that turned out difficult because, as far as I remember, one of the reasons is the reindexing of parameters, which screws up the storage of these matrices in CSR form, but I am pretty sure thats not the full story.

Reverting these changes will likely require a boatload of carefully handpicked changes and may lead to performance degradation in other applications, so I would ideally want to avoid.

Before we move forward on this, we should make sure that we are 99% sure that this is the actual issue. Can you compile the model using AMICI 10.13 and a pre #627 amici (you probably want to use the matlab compilation there, as #627 also fixed an issue with the sign of the jacobian for the backwards problem that only existed in the python implementation), to ensure that the number of steps in the backwards integration, nonlinear failures and convergence failures are approximately the same between the two versions and the main difference is actually the time to evaluate amici::model_ODE::qBdot?

The reason I am a bit sceptical is because 0.99*0.8*0.9 accounts for just ~70% of computation time, so even if you get the computation time of that part down to zero, you can only expect a threefold reduction in computation time, which doesn't really add up to the 100 fold you are describing there.
Just because something is taking up most of the compute time, does not necessarily mean it is the source of the problem. Could also be that part of the code is called too often and the issue is somewhere upstream (convergence failures, etc).

**Comment by paulstapor** [comment]
> Can you compile the model using AMICI 10.13 and a pre #627 amici (you probably want to use the matlab compilation there, as #627 also fixed an issue with the sign of the jacobian for the backwards problem that only existed in the python implementation), to ensure that the number of steps in the backwards integration, nonlinear failures and convergence failures are approximately the same between the two versions and the main difference is actually the time to evaluate amici::model_ODE::qBdot?

That's what I'm doing right now ;)

> The reason I am a bit sceptical is because 0.990.80.9 accounts for just ~70% of computation time

You're right that I owe you an explanation of the remaining 20%. Of this
 - about one third goes into evaluations of AmiVectorArray::at of dxdotdp (of which more than 00% should be zeros)
 - about two thirds are self time of this routine (no real clue where this goes, maybe due to looping over ix and ip and summing the terms up (of which very should be zeros, I think)

**Comment by paulstapor** [comment]
I totally see your point, that this might be very unpleasant to resolve...
I try to nail it down tomorrow. The point is that step numbers, rhs-calls and error_test_fails seem to be in a reasonable regime, forward and backward. I can give more details on this tomorrow.

**Comment by paulstapor** [comment]
Last version before the change in fqBdot was v0.9.4.
I tried the Python installation, but I am running in problems with setuptools and pkgconfig due to missing hdf5 libraries. As this may or may not take long (and other fixes would have to be done anyhow, such as the Jacobian), I decided to go for Maltab-AMICI...
Any objections?

**Comment by dweindl** [comment]
> I tried the Python installation, but I am running in problems with setuptools and pkgconfig due to missing hdf5 libraries.

Yeah, some progress has been made in installability since then ;). Changing https://github.com/ICB-DCM/AMICI/blob/v0.9.4/python/sdist/setup.py#L52 to `h5pkgcfg = {'found': False}` should probably do the trick.

With Matlab you will have significantly longer import times. But in general it's okay to use that.

**Comment by paulstapor** [comment]
> Yeah, some progress has been made in installability since then ;). Changing https://github.com/ICB-DCM/AMICI/blob/v0.9.4/python/sdist/setup.py#L52 to `h5pkgcfg = {'found': False}` should probably do the trick.

Tried that already and guess what: Still doesn't work, as other fields in `h5pkgcfg` are requested later on ;) That's actually when I decided to not follow this path... :D

**Comment by paulstapor** [comment]
Yes, it will take longer, indeed. But: By today evening, we should have an answer...

**Comment by paulstapor** [comment]
To be even more clear, I can retry this with AMICI v0.9.5, which should be the version in which the qBdot code changed...

**Comment by dweindl** [comment]
> Tried that already and guess what: Still doesn't work, as other fields in h5pkgcfg are requested later on ;) That's actually when I decided to not follow this path... :D

Okay, then
``` 
   h5pkgcfg = {
'found' = False, 
'include_dirs': [],
                'library_dirs': [],
                'libraries': [],
                'define_macros': []
                }
```

**Comment by paulstapor** [comment]
The last one worked indeed...

**Comment by paulstapor** [comment]
Okay, got the stuff working now in Matlab _and_ Python...
Beyond the fact that some funny little fixes had to be done to get things running, here are the results (from Matlab):
rdata["numsteps"]: [606]
rdata["numrhsevals"]: [650]
rdata["numerrtestfails"]: [4]
rdata["numnonlinsolvconvfails"]: [0]
rdata["order"]: [1]
rdata["numstepsB"]: [953]
rdata["numrhsevalsB"]: [1008]
rdata["numerrtestfailsB"]: [5]
rdata["numnonlinsolvconvfailsB"]: [0]
External time-stepping says:
forward solve: 1.175609 seconds
forward & backward solve: 3.134953 seconds
In this case, quadrature tolerances were used, so I would not worry about the 50% higher number of steps for backward integration...

**Comment by FFroehlich** [comment]
Okay, what matlab and python version do you refer to respectively?

How do the diagnosis values compare between old Matlab and new python?

**Comment by FFroehlich** [comment]
ah just saw the details for python further up, I agree that the most likely culprit is fqBdot. Which is really unfortunate, because it means that the previous symbolic preoptimization made a substantial difference.

**Comment by paulstapor** [comment]
As the imports in Matlab and Python don't do exactly the same things, it's very hard to check the in a really comparative setting. However, that's not my aim...

I think what could help is:
fqBdot is basically using dxdotdp, which is using dxdotdw and dwdp.
I would hence suggest to make dxdotdw and dwdp sparse. This should resolve the whole problem, as whose two should be very spasre for large models. 

It also makes sense conceptually: We're integrating 3 ODE systems: xdot, xBdot, and qBdot. The latter is the only one which is not sparsified, the first two ones are...

**Comment by paulstapor** [comment]
Concerning correctness of the implementation: I'm now running through all the benchmark models we can import and checking the gradients there. If we find things such as FSA == ASA == FD for many points in parameter space, then I think we'e fine to say that the python import is testing for now...
However, we should add according unit tests... Maybe similar to what we do now with the SBML test suite, that at least every once in a while, the corresponding tests are run...

**Comment by FFroehlich** [comment]
Just summarizing my thoughts here:

I would initially focus on `fdxdotdp`, as this seems to be the key bottleneck and the primary difference between matlab and python interfaces (did you also check performance with the most recent matlab importer?).

Should actually be pretty straightforward to just reimplement the generation of `fdxdotdp` in python and remove the `wasPythonGenerated()` check in `Model_ODE::fdxdotdp`.

**Comment by paulstapor** [comment]
> I would initially focus on `fdxdotdp`, as this seems to be the key bottleneck and the primary difference between matlab and python interfaces (did you also check performance with the most recent matlab importer?).

I didn't check that. I would guess the matlab_interface-functionality would have to be fixed first. Usually, changes in the API in Amici break that, and there been some in recent times. I wanted to skip that and first really find the main cause for the current problem.

I think that, in the long run, we want dwdp to be sparse. For large models, it has millions of entries, and only a few thousand of them are not zero...

**Comment by paulstapor** [comment]
Good news is: I'm through 8 models now and, at least around the nominal parameter vector, the results look fine for FSA and ASA ...
I will continue on this tomorrow in more detail. But at a first glance, I would say that adjoints seem to do meaningful things also for the python import, at least in AMICI v0.9.13...

**Comment by FFroehlich** [comment]
> Good news is: I'm through 8 models now and, at least around the nominal parameter vector, the results look fine for FSA and ASA ...
I will continue on this tomorrow in more detail. But at a first glance, I would say that adjoints seem to do meaningful things also for the python import, at least in AMICI v0.9.13...

That was never the question. We ensure that FSA and ASA are quantitatively correct through unittest. I am 95% sure though that they are conceptually incorrectly computed (I think it is was a bad sign in the jacobian or a missing transpose), which explains the performance difference between matlab and python.

**Comment by paulstapor** [comment]
> I am 95% sure though that they are conceptually incorrectly computed (I think it is was a bad sign in the jacobian or a missing transpose), which explains the performance difference between matlab and python.

I tested this (tested Transposing and non-transposing). If the transposition of the Jacobian is incorrect, we see that in the gradient. Right now, the Jacobian is definitely correctly transposed.

**Comment by paulstapor** [comment]
> which explains the performance difference between matlab and python.

In Amici v0.9.13, I am pretty sure this one is not due to the Jacobian any more. It used to be a while ago, but that one was fixed and is correct now.

**Comment by FFroehlich** [comment]
> I tested this (tested Transposing and non-transposing). If the transposition of the Jacobian is incorrect, we see that in the gradient. Right now, the Jacobian is definitely correctly transposed.

The jacobian of `xBdot`, you can pretty accurately integrate an ODE with an incorrect jacobian, only the performance will take a big hit.

**Comment by FFroehlich** [comment]
...

I am 3000% certain that the fix did not change results but only performance. If what you tested changes results, it cannot possibly be what I fixed.

The fix was in #583 which made the 0.9.3 release, so we should be fine.

**Comment by paulstapor** [comment]
> I am 3000% certain that the fix did not change results but only performance. If what you tested changes results, it cannot possibly be what I fixed.

Okay, now I see that we're talking of two different things...

You fixed the sign of the Jacobian. That one was perfectly fine and perfectly improved performance, but the gradient was correct. Also makes sense: multiplying the JAcobian with a scalar does not affect it's eigenvectors.

I recently tested whether or not we might be missing a transposition (I first blamed the performance problem to something like this). The result here was: We're not missing a transposition, as transposing JB does indeed affect the correctness of the gradient. I think this makes sense as a transposition does affect the eigenvectors of JB.

**Comment by paulstapor** [comment]
Some new numbers now:
```
rdata["numsteps"]:  [1187]
rdata["numrhsevals"]:  [1266]
rdata["numerrtestfails"]:  [3]
rdata["numnonlinsolvconvfails"]:  [0]
rdata["order"]:  [1]
rdata["cpu_time"]:  106.84
rdata["numstepsB"]:  [985]
rdata["numrhsevalsB"]:  [1077]
rdata["numerrtestfailsB"]:  [13]
rdata["numnonlinsolvconvfailsB"]:  [0]
rdata["cpu_timeB"]:  405.503
```
So, adjoint computation is now back to what it was before. Compared to what we had after recent changes, this is a speed-up of about 100. Compared to what we had originally, it is more than a 200-fold faster now.

**Comment by dweindl** [comment]
That's great news! Good job.

**Comment by JanHasenauer** [comment]
Really great. Thanks
