### ISSUE TITLE
sbml_flattener

### ISSUE THREAD

**Issue by jvanhoefer** [ICB-DCM/AMICI#857]
@FFroehlich suggested in #855 to implement a sbml_flattener function, that reformulates SBML functionality that is not supported yet by functionality that we already support. 

If the rest of you (i.e. mainly @dweindl , @FFroehlich and @JanHasenauer ) are fine with this, I would implement such a function. I would at first focus on

- [x] Rate Rules #732 
- [x] Species Assignment Rules #759

**Comment by dweindl** [comment]
This is obsolete now, right?

**Comment by jvanhoefer** [comment]
yes
