### ISSUE TITLE
osx, travis-ci: CMake unable to find python3

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#894]
... seems to be due to some changes in brew packages.

**Comment by FFroehlich** [comment]
I assume thats due to python 2 becoming EOL. Thats probably more of a cmake problem than a brew problem.

**Comment by dweindl** [comment]
Fixed it. CMake did not change. It was about not creating required links by homebrew.

**Comment by FFroehlich** [comment]
> Fixed it. CMake did not change. It was about not creating required links by homebrew.

Right, that fixes the problem, but I would assume that those changes in brew are intentional, so we might want to revisit this as soon as cmake catches up.

**Comment by dweindl** [comment]
I am not completely sure about the rational. Before, brew seemed to have set python3 links as we need them, but now, as python2 officially died, it does not set them correctly. Not completely sure if now there is no `python3` anymore but only `python `, or whether this was just some random bad interaction. But I guess as long as CI runs it's fine. None of these changes really affects users. The CMake implementation works fine with recent CMake versions, although probably not with all, as there have been many changes. I don't want to implement support for all cmake 3.8...3.16 unless we have user requests. I hope quickly everybody is using a CMake with a working FindPython3.
