### ISSUE TITLE
python 3.8

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#897]
Python 3.8 was released October last year but tests are still running on python 3.7. 
We are currently claiming support for >=3.6 but don't actually check that in CI. Did we ever decide on how many minor python versions we want to support?

**Comment by dweindl** [comment]
We didn't. The most recent 2 stable minor versions? Unless there is good reason to drop support earlier...

**Comment by FFroehlich** [comment]
> We didn't. The most recent 2 stable minor versions? Unless there is good reason to drop support earlier...

Sounds good!
