### ISSUE TITLE
Failing to install amici

### ISSUE THREAD

**Issue by paulflang** [ICB-DCM/AMICI#908]
I am just trying to install amici on Ubuntu, but the following ways fail:

1)
```pip3 install amici```
cannot build wheel (see here: [amici_installation_failure.txt](https://github.com/ICB-DCM/AMICI/files/4064899/amici_installation_failure.txt)).

2)
```
root@4760652c400e:~/host/Documents/Project07_Parameter Fitting# pip3 install -e https://github.com/icb-dcm/amici/archive/master.zip#egg=amici\&subdirectory=python/sdist
ERROR: https://github.com/icb-dcm/amici/archive/master.zip#egg=amici&subdirectory=python/sdist is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with svn+, git+, hg+, or bzr+).
```

3)
```
root@4760652c400e:~/host/Documents/Project07_Parameter Fitting# pip3 install -e git+https://github.com/icb-dcm/amici/archive/master.zip#egg=amici\&subdirectory=python/sdist
Obtaining amici from git+https://github.com/icb-dcm/amici/archive/master.zip#egg=amici&subdirectory=python/sdist
  Cloning https://github.com/icb-dcm/amici/archive/master.zip to ./src/amici
  Running command git clone -q https://github.com/icb-dcm/amici/archive/master.zip '/root/host/Documents/Project07_Parameter Fitting/src/amici'
  Warning: Permanently added the RSA host key for IP address '140.82.118.4' to the list of known hosts.
  fatal: remote error:
    icb-dcm/amici/archive/master.zip is not a valid repository name
    Email support@github.com for help
ERROR: Command errored out with exit status 128: git clone -q https://github.com/icb-dcm/amici/archive/master.zip '/root/host/Documents/Project07_Parameter Fitting/src/amici' Check the logs for full command output.
```

**Comment by dweindl** [comment]
Hi @paulflang,

Thanks for reporting.

Your first issue seems to be related to an incomplete build environment on your machine. Could you check if the solutions reported [here](https://stackoverflow.com/questions/11912878/gcc-error-gcc-error-trying-to-exec-cc1-execvp-no-such-file-or-directory) fix this problem?

Second issue: The URL in the install guide was wrong, this has been fixed already on `develop` an will show up in the documentation later today.
This one should work:

> pip3 install -e git+https://github.com/icb-dcm/amici.git@master#egg=amici\&subdirectory=python/sdist

(Although this will most likely end with the same error as reported for (1))

Third: same problem as second.

Hope this helps.

**Comment by paulflang** [comment]
Hey @dweindl ,
Thank you very much for getting back so quickly.

1) The docker container I am working in (I do not know if it is docker-alpine) does not have sudo. I tried to install amici outside the docker container. This did not work either and could also not be resolved via ```sudo apt-get install --reinstall build-essential``` as suggested in the link you provided (see 
[amici_installation_failure_2.txt](https://github.com/ICB-DCM/AMICI/files/4066062/amici_installation_failure_2.txt) for details.)

2) I also tried ```pip3 install -e git+https://github.com/icb-dcm/amici.git@master#egg=amici\&subdirectory=python/sdist``` outside docker and ran into a different problem:
```
(base) paul@paul-VirtualBox:/media/sf_DPhil_Project/Project07_Parameter Fitting$ pip3 install -e git+https://github.com/icb-dcm/amici.git@master#egg=amici\&subdirectory=python/sdist
Obtaining amici from git+https://github.com/icb-dcm/amici.git@master#egg=amici&subdirectory=python/sdist
  Cloning https://github.com/icb-dcm/amici.git (to master) to ./src/amici
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/media/sf_DPhil_Project/Project07_Parameter Fitting/src/amici/python/sdist/setup.py", line 22, in <module>
        from custom_commands import (my_install, my_build_clib, my_develop,
      File "/media/sf_DPhil_Project/Project07_Parameter Fitting/src/amici/python/sdist/custom_commands.py", line 16, in <module>
        from amici.setuptools import generateSwigInterfaceFiles
      File "/media/sf_DPhil_Project/Project07_Parameter Fitting/src/amici/python/sdist/amici/__init__.py", line 1
        ../../amici/__init__.py
        ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /media/sf_DPhil_Project/Project07_Parameter Fitting/src/amici/python/sdist
```

**Comment by dweindl** [comment]
ad 1.: 

The problem from the previous post does not occur here. What is missing is a CBLAS implementation. On Ubuntu/Debian you would install that with `apt install libatlas-base-dev`. For your container, it's hard to tell without knowing your linux distribution.

ad 2.: 

This seems like you are using a file system which does not support symlinks (NTFS?). Try `pip3 install amici`, this should not have this problem.

**Comment by paulflang** [comment]
ad1.:
thank you very much @dweindl , the installation worked now by typing `apt install libatlas-base-dev` and `pip install amici` (outside docker I need to use `pip` rather than `pip3` to install into the correct python environment.)

ad2.:
I am afraid, I do not know if my file system supports symlinks (`ln -s` works, if this is what you mean). But I ran `pip install amici` in 1 anyway and it worked.

**Comment by dweindl** [comment]
Glad it worked.

If `ln -s` works **within** `/media/sf_DPhil_Project/Project07_Parameter Fitting/`, then I don't know what's going wrong there. But as the other option works, I will close this.

**Comment by paulflang** [comment]
You are right. It does not work in `/media/sf_DPhil_Project/Project07_Parameter Fitting/`.
```
(base) paul@paul-VirtualBox:/media/sf_DPhil_Project/Project07_Parameter Fitting$ ln -s test.txt ./testsym/otherfile
ln: failed to create symbolic link './testsym/otherfile': Operation not permitted
```
FYI, this is in a Ubuntu Virtualbox. The directory `sf_DPhil_Project` contains several folders mounted from `OneDrive - Nexus365` of the Windows 10 host. Never noticed that I cannot create symlinks here. Thanks!
