### ISSUE TITLE
cleanup pstatus

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#91]
some functions have write in the pstatus pointer and return status flags. some only write the pstatus pointer. I think it would be more intuitive to simply return a status flag (int) from all functions and not pass the pstatus point around.

**Comment by dweindl** [comment]
Yes, that is a bit messy. Return code for all void functions, for the rest we will have to keep the pointer.

**Comment by dweindl** [comment]
We should use UserData::status wherever applicable and change it to Int (mxInt32)
