### ISSUE TITLE
Matlab: CalcMD5 required but not built when using Python-generated compileMexFile

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#914]
_Originally posted by @paulflang in https://github.com/ICB-DCM/AMICI/issues/389#issuecomment-574859922_

Thanks a lot. I'll call it a day, too. FYI, I could not run `matlab/examples/example_steadystate/example_steadystate.m` because I am using Matlab 2019b.
```
>> compileMexFile
AMICI base files | Building with 'MinGW64 Compiler (C++)'.
MEX completed successfully.
Error using CalcMD5 (line 70)
Cannot find MEX script.

Error in amimodel.compileAndLinkModel>getFileHash (line 244)
    hash = CalcMD5(file,'File','hex');

Error in amimodel.compileAndLinkModel>updateFileHash (line 256)
    hash = getFileHash(fullfile(fileFolder,filename));

Error in amimodel.compileAndLinkModel>updateFileHashSource (line 250)
        updateFileHash(sourceFolder,objectFolder,fileName);

Error in amimodel.compileAndLinkModel>@(x)updateFileHashSource(amiciSourcePath,objectFolder,x) (line 211)
        cellfun(@(x) updateFileHashSource(amiciSourcePath, objectFolder, x), sourcesForRecompile);

Error in amimodel.compileAndLinkModel>compileAmiciBase (line 211)
        cellfun(@(x) updateFileHashSource(amiciSourcePath, objectFolder, x), sourcesForRecompile);

Error in amimodel.compileAndLinkModel (line 72)
    [objectStrAmici] = compileAmiciBase(amiciRootPath, objectFolder, objectFileSuffix, includesstr, DEBUG, COPT);

Error in compileMexFile (line 6)
amimodel.compileAndLinkModel(modelName, '', [], [], [], []);
 
>> example_steadystate
Error using amiwrap (line 16)
MATLAB R2018a or higher is currently not supported (see https://github.com/ICB-DCM/AMICI/issues/307)

Error in example_steadystate (line 7)
    amiwrap('model_steadystate','model_steadystate_syms',exdir)
```

**Comment by dweindl** [comment]
@paulflang: Can you try again with https://github.com/ICB-DCM/AMICI/blob/fix_914_md5/matlab/auxiliary/CalcMD5/CalcMD5.m?

**Comment by paulflang** [comment]
@dweindl : I tried:
```
>> compileMexFile
AMICI base files | Building with 'MinGW64 Compiler (C++)'.
MEX completed successfully.
CalcMD5 has not been compiled yet. Compiling now!
Building with 'MinGW64 Compiler (C)'.
MEX completed successfully.
ffuns | Building with 'MinGW64 Compiler (C++)'.
Error using mex
Assembler messages:
Fatal error: can't create C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter
Fitting\benchmark\inputs\intermediate_models\project\models\model_steadystate_scaled\2019b\g0x2B0x2B_x86_64_posix_seh_rev20x2C_Built_by_MinGW_W64_project_\release\model_steadystate_scaled_J.obj:
No such file or directory


Error in amimodel.compileAndLinkModel (line 130)
        eval(['mex ' DEBUG COPT ...

Error in compileMexFile (line 6)
amimodel.compileAndLinkModel(modelName, '', [], [], [], []);
```

Turns out that the directory `C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\benchmark\inputs\intermediate_models\project\models\model_steadystate_scaled\2019b\g0x2B0x2B_x86_64_posix_seh_rev20x2C_Built_by_MinGW_W64_project_\release` is empty.

**Comment by dweindl** [comment]
Okay, seems all to be related to not having performed any model import with matlab before importing a python-generated model. Seems like you are the first one doing that with a Matlab>R2018a. Will look into that.

**Comment by dweindl** [comment]
I can't reproduce this error. A non-existing destination directory would explain the error message, but as you say it exists, I am a bit puzzled.

**Comment by paulflang** [comment]
I just tried again on a different machine (my laptop, Windows 10, Matlab 2019a) and got a different error:
```
>> compileMexFile
Expected one output from a curly brace or dot indexing expression, but there were 0 results.

Error in amimodel.compileAndLinkModel>getCompilerVersionString (line 340)
    [~,systemreturn] = system([mex.getCompilerConfigurations('c++').Details.CompilerExecutable ' --version']);

Error in amimodel.compileAndLinkModel (line 43)
    compilerVersion = getCompilerVersionString();

Error in compileMexFile (line 6)
amimodel.compileAndLinkModel(modelName, '', [], [], [], []);
```
Will try to (a) reproduce the error and (b) run the whole thing on Matlab 2017b when I am back in the office tomorrow

**Comment by paulflang** [comment]
Back on the machine in my office I could reproduce the error:
```
>> compileMexFile
ffuns | Building with 'MinGW64 Compiler (C++)'.
Error using mex
Assembler messages:
Fatal error: can't create C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter
Fitting\benchmark\inputs\intermediate_models\project\models\model_steadystate_scaled\2019b\g0x2B0x2B_x86_64_posix_seh_rev20x2C_Built_by_MinGW_W64_project_\release\model_steadystate_scaled_J.obj:
No such file or directory


Error in amimodel.compileAndLinkModel (line 130)
        eval(['mex ' DEBUG COPT ...

Error in compileMexFile (line 6)
amimodel.compileAndLinkModel(modelName, '', [], [], [], []);
```
![image](https://user-images.githubusercontent.com/47160416/72606979-92507980-3917-11ea-942c-c8fe6c7e0477.png)

**Comment by dweindl** [comment]
Thanks for further testing @paulflang. I am wondering if that is a Windows/mingw issue. I don't have Windows available and can't verify that. Do you happen to have a Linux Matlab installation? Can you try moving the `model_steadystate_scaled` directory to a path without blanks and retry `compileMexFile`?

**Comment by dweindl** [comment]
> I just tried again on a different machine (my laptop, Windows 10, Matlab 2019a) and got a different error:
> 
> ```
> >> compileMexFile
> Expected one output from a curly brace or dot indexing expression, but there were 0 results.
> 
> Error in amimodel.compileAndLinkModel>getCompilerVersionString (line 340)
>     [~,systemreturn] = system([mex.getCompilerConfigurations('c++').Details.CompilerExecutable ' --version']);
> 
> Error in amimodel.compileAndLinkModel (line 43)
>     compilerVersion = getCompilerVersionString();
> 
> Error in compileMexFile (line 6)
> amimodel.compileAndLinkModel(modelName, '', [], [], [], []);
> ```
> 

Does `mex.getCompilerConfigurations('c++') ` return anything meaningful? If not, it may be that there is no compiler set up for matlab.

**Comment by luwidmer** [comment]
Regarding path not found, I would hypothesize you are running into MAX_PATH restrictions on Windows (max. 260 characters, your path is 266), see https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation

**Comment by paulflang** [comment]
@luwidmer : that was probably it! I just put the `model_steadystate_scaled` directory a bit further up in the path but still in OneDrive (`C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\model_steadystate_scaled`) and it worked.
Thanks a lot!

**Comment by dweindl** [comment]
Oh my... Thanks, good to know.

**Comment by paulflang** [comment]
@dweindl : Thank you very much for your great support over the last days!
