### ISSUE TITLE
Compiler error on Macbook with Clang

### ISSUE THREAD

**Issue by paulstapor** [ICB-DCM/AMICI#95]
Unfortunately, I encountered a compilation error for the Memoir version of the Bachmann JAK2/STAT5 model on the master-branch of Amici:

Error using mex
Undefined symbols for architecture x86_64:
  "_cblas_dgemm", referenced from:
      fsJy(double, int, double*, double*, double*, double*, double*, double*, double*, double*, double*, void*) in amici.o
  "_cblas_dgemv", referenced from:
      fsy(double, int, double*, double*, double*, _generic_N_Vector**, void*) in amici.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Error in amimodel/compileC (line 444)
    eval(['mex ' DEBUG ' ' COPT ' ' CLIBS ...

Error in amiwrap (line 87)
    model.compileC();

Error in Estimation_jakstat (line 23)
amiwrap('JS_Memoir','HandmadeMemoir_syms', exdir);

**Comment by FFroehlich** [comment]
what version of OS X are you using?

**Comment by paulstapor** [comment]
El Capitan, OS X 10.11.6
