### ISSUE TITLE
Defining constant parameters

### ISSUE THREAD

**Issue by paulflang** [ICB-DCM/AMICI#952]
I am trying to define constant parameters in a model called "G2M_copasi_init_pert_Ob" to simulate experimental perturbations.

As preliminary test, I created a model without perturbations/constant parameters (see [G2M_copasi_init.zip](https://github.com/ICB-DCM/AMICI/files/4186166/G2M_copasi_init.zip), which contains i.a. the mex file of the model, and the inputs to simulate the mex model). The output `sol.x` after simulating the model via `sol = ami_G2M_copasi_init_Ob(tout,theta(1:27),kappa(1:0),options_ami,plist,pbar,xscale,data);` is as expected.

I next added three parameters ('cCb_0', 'cB55_0', 'cPhWee') to the model in Copasi and exported the sbml. I then converted the sbml file to an AMICI model via Python/Matlab, setting the above three parameters as `constantParameters` ([G2M_copasi_init_pert.zip](https://github.com/ICB-DCM/AMICI/files/4186167/G2M_copasi_init_pert.zip)). The output `sol.x` when setting the three constant parameters to one, i.e. simulating via `sol = ami_G2M_copasi_init_pert_Ob(tout,theta(1:27),kappa(1:3),options_ami,plist,pbar,xscale,data);` should be the same as before. Unfortunately, it is not, and I was not able to figure out why. I would be grateful for any help with this.

**Comment by FFroehlich** [comment]
Hi paulflang,

the mex files are platform specific binary code which makes it difficult to run/analyze them. Could you show us the script you used to compile both models?

**Comment by paulflang** [comment]
Hi @FFroehlich ,
Thank you very much for looking into this. To generate the "G2M_copasi_init_pert_Ob" model I used python script [sbml2ami_mex.txt](https://github.com/ICB-DCM/AMICI/files/4186491/sbml2ami_mex.txt) (I cannot upload .py or .m files, hence the .txt ending), which I used (in Ubuntu) to generate the file [compileMexFile.txt](https://github.com/ICB-DCM/AMICI/files/4186499/compileMexFile.txt) (for "G2M_copasi_init_Ob" I used the same python script, but modified the variables `sbml_file`, `model_name` and left `constantParameters` away). I used `complileMexFile.m` to generate `ami_G2M_copasi_init_pert_Ob.mexw64` in Matlab 2019b on Windows 10.

There are two more things I should probably mention:
- For both models, the python script failed in line 43, but `compileMexFile.m` was always generated.
- I am not using the `simulate_G2M_copasi_init_... .m` file generated by `compileMexFile.m` of my current AMICI version as interface to the .mexw64 file. Instead, I am modifying a template file from the paper 'Benchmarking optimization methods for parameter estimation in large kinetic models' to yield [simulate_G2M_copasi_init_pert_Ob.txt](https://github.com/ICB-DCM/AMICI/files/4186612/simulate_G2M_copasi_init_pert_Ob.txt). This is because I am using the eSS-FMINCON-ADJ-LOG algorithm as implemented in the supplementary code, which appears to require a slightly different AMICI version (i.e. I generate `ami_G2M_copasi_init_pert_Ob.mexw64` with a different AMICI version than the one that is on path while running it (AMICI-master). Up until now, this was fine.)

**Comment by FFroehlich** [comment]
> Hi @FFroehlich ,
> Thank you very much for looking into this. To generate the "G2M_copasi_init_pert_Ob" model I used python script [sbml2ami_mex.txt](https://github.com/ICB-DCM/AMICI/files/4186491/sbml2ami_mex.txt) (I cannot upload .py or .m files, hence the .txt ending), which I used (in Ubuntu) to generate the file [compileMexFile.txt](https://github.com/ICB-DCM/AMICI/files/4186499/compileMexFile.txt) (for "G2M_copasi_init_Ob" I used the same python script, but modified the variables `sbml_file`, `model_name` and left `constantParameters` away). I used `complileMexFile.m` to generate `ami_G2M_copasi_init_pert_Ob.mexw64` in Matlab 2019b on Windows 10.

At first glance, this all looks reasonable to me.

> 
> There are two more things I should probably mention:
> 
> * For both models, the python script failed in line 43, but `compileMexFile.m` was always generated.

Thats fine. `compile=False` 

> * I am not using the `simulate_G2M_copasi_init_... .m` file generated by `compileMexFile.m` of my current AMICI version as interface to the .mexw64 file. Instead, I am modifying a template file from the paper 'Benchmarking optimization methods for parameter estimation in large kinetic models' to yield [simulate_G2M_copasi_init_pert_Ob.txt](https://github.com/ICB-DCM/AMICI/files/4186612/simulate_G2M_copasi_init_pert_Ob.txt). This is because I am using the eSS-FMINCON-ADJ-LOG algorithm as implemented in the supplementary code, which appears to require a slightly different AMICI version (i.e. I generate `ami_G2M_copasi_init_pert_Ob.mexw64` with a different AMICI version than the one that is on path while running it (AMICI-master). Up until now, this was fine.)

Yeah, thats probably the culprit. The `simulate_...` function is unlikely to work across different versions of MATLAB (this is why we included a stern warning not make any manual changes to the file). In fact looking at the diff between the generated file and what you used its actually surprising MATLAB didn't crash right away.

However, I don't think that using the old `simulate_...` function is actually necessary, you should be able to use wrapper code just the same way as in the supplement.

**Comment by paulflang** [comment]
So I've tried using the auto generated `simulate_...` function. When using with `AMICI-master` on path, I get:

```
>> launch_meigo_G2M_copasi_init_pert_Ob

------------------------------------------------------------------------------ 
 eSS R2016A - Enhanced Scatter Search    
<c> IIM-CSIC, Vigo, Spain -  email: gingproc@iim.csic.es 
------------------------------------------------------------------------------ 

Refset size automatically calculated: 18
Number of diverse solutions automatically calculated: 270
Unrecognized method, property, or field 'pscale' for class 'amioption'.

Error in simulate_G2M_copasi_init_pert_Ob (line 156)
if(isempty(options_ami.pscale))

Error in like_MEIGO_G2M_copasi_init_pert_Ob (line 49)
        sol = simulate_G2M_copasi_init_pert_Ob(D(idata).t,theta,D(idata).condition,D(idata),options);

Error in ssm_evalfc (line 44)
    value=feval(fobj,x,varargin{:});

Error in ess_kernel (line 610)
    [val,val_penalty,pena,nlc,include,x] = ssm_evalfc(solutions(i,:),x_L,x_U,fobj,nconst,c_L,c_U,...

Error in MEIGO (line 8)
    Results = ess_kernel(problem,opts,varargin{:});

Error in launch_meigo_G2M_copasi_init_pert_Ob (line 83)
    Results = MEIGO(problem,opts,optim_algorithm);
```

When switching to my most recent version of AMICI, `sol = ami_G2M_copasi_init_pert_Ob(tout,theta(1:27),kappa(1:3),options_ami,plist,xscale,init,data);`  returns `sol.status = -1` and `sol.llh = NaN`. This is despite the inputs to the `ami_...` file ([auto-generated_simulate_file.zip](https://github.com/ICB-DCM/AMICI/files/4192164/auto-generated_simulate_file.zip)) seem OK to me.

I am not sure if I understand what you mean with using "wrapper code just the same way as in the supplement". Isn't the `simulate_..." function the wrapper? If so, I guess I can just use it rather than writing my own wrapper.

**Comment by FFroehlich** [comment]
> I am not sure if I understand what you mean with using "wrapper code just the same way as in the supplement". Isn't the `simulate_..." function the wrapper? If so, I guess I can just use it rather than writing my own wrapper.

The `simulate_` function serves as an interface between MATLAB and C++ code. The main reason for its existence is that the MATLAB provided interface generally is very unforgiving for malformed inputs which can frequently lead to crashes or, possibly worse, incorrect results without throwing any error messages (which is what you experienced.

Accordingly, you should try to avoid directly calling the mex file and, instead, always use the generated `simulate` function.

In terms of the error, it can easily be fixed. The `pscale` field was introduced in more recent MATLAB versions. It looks like you are using different AMICI versions in MATLAB for compilation and simulation (the launch script probably adds the AMICI version from the supplement to the path). Please make sure that you always use the same AMICI version.

**Comment by paulflang** [comment]
Well, I do not have an `addpath` function in my launch script. But to be absolutely sure that I use the identical AMICI version for generating the `compileMexFile.m`, running it, and launching the model
- I installed the newest AMICI version on Ubuntu in a fresh virtualenv: `python -m pip install -e git+https://github.com/icb-dcm/amici.git@master#egg=amici\&subdirectory=python/sdist`
- I ran my `sbml2ami_mex.py` file to obtain a new AMICI model and `compileMexFile.m`.
- I removed the old AMICI version from the Matlab path (on Windows), cloned the newest AMICI version from GitHub and added it to the Matlab path.
- I ran `compileMexFile.m` but got the following error (sorry for the long output):

```
MEX completed successfully.
AMICI base files | Building with 'MinGW64 Compiler (C++)'.
Error using mex
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp: In member function 'void
amici::Solver::initializeLinearSolver(const amici::Model*) const':
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:201:24: error: 'make_unique'
is not a member of 'std'
         linearSolver = std::make_unique<SUNLinSolDense>(x);
                        ^~~
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:201:55: error: expected
primary-expression before '>' token
         linearSolver = std::make_unique<SUNLinSolDense>(x);
                                                       ^
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:208:13: error: 'make_unique'
is not a member of 'std'
             std::make_unique<SUNLinSolBand>(x, model->ubw, model->lbw);
             ^~~
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:208:43: error: expected
primary-expression before '>' token
             std::make_unique<SUNLinSolBand>(x, model->ubw, model->lbw);
                                           ^
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:227:24: error: 'make_unique'
is not a member of 'std'
         linearSolver = std::make_unique<SUNLinSolSPGMR>(x);
                        ^~~
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:227:55: error: expected
primary-expression before '>' token
         linearSolver = std::make_unique<SUNLinSolSPGMR>(x);
                                                       ^
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:233:24: error: 'make_unique'
is not a member of 'std'
         linearSolver = std::make_unique<SUNLinSolSPBCGS>(x);
                        ^~~
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:233:56: error: expected
primary-expression before '>' token
         linearSolver = std::make_unique<SUNLinSolSPBCGS>(x);
                                                        ^
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:239:24: error: 'make_unique'
is not a member of 'std'
         linearSolver = std::make_unique<SUNLinSolSPTFQMR>(x);
                        ^~~
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:239:57: error: expected
primary-expression before '>' token
         linearSolver = std::make_unique<SUNLinSolSPTFQMR>(x);
                                                         ^
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:247:24: error: 'make_unique'
is not a member of 'std'
         linearSolver = std::make_unique<SUNLinSolKLU>(
                        ^~~
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:247:53: error: expected
primary-expression before '>' token
         linearSolver = std::make_unique<SUNLinSolKLU>(
                                                     ^
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp: In member function 'void
amici::Solver::initializeNonLinearSolver() const':
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:274:27: error: 'make_unique'
is not a member of 'std'
         nonLinearSolver = std::make_unique<SUNNonLinSolNewton>(x.getNVector());
                           ^~~
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:274:62: error: expected
primary-expression before '>' token
         nonLinearSolver = std::make_unique<SUNNonLinSolNewton>(x.getNVector());
                                                              ^
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:278:13: error: 'make_unique'
is not a member of 'std'
             std::make_unique<SUNNonLinSolFixedPoint>(x.getNVector());
             ^~~
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:278:52: error: expected
primary-expression before '>' token
             std::make_unique<SUNNonLinSolFixedPoint>(x.getNVector());
                                                    ^
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp: In member function 'void
amici::Solver::initializeLinearSolverB(const amici::Model*, int) const':
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:293:25: error: 'make_unique'
is not a member of 'std'
         linearSolverB = std::make_unique<SUNLinSolDense>(xB);
                         ^~~
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:293:56: error: expected
primary-expression before '>' token
         linearSolverB = std::make_unique<SUNLinSolDense>(xB);
                                                        ^
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:300:13: error: 'make_unique'
is not a member of 'std'
             std::make_unique<SUNLinSolBand>(xB, model->ubw, model->lbw);
             ^~~
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:300:43: error: expected
primary-expression before '>' token
             std::make_unique<SUNLinSolBand>(xB, model->ubw, model->lbw);
                                           ^
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:319:25: error: 'make_unique'
is not a member of 'std'
         linearSolverB = std::make_unique<SUNLinSolSPGMR>(xB);
                         ^~~
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:319:56: error: expected
primary-expression before '>' token
         linearSolverB = std::make_unique<SUNLinSolSPGMR>(xB);
                                                        ^
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:325:25: error: 'make_unique'
is not a member of 'std'
         linearSolverB = std::make_unique<SUNLinSolSPBCGS>(xB);
                         ^~~
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:325:57: error: expected
primary-expression before '>' token
         linearSolverB = std::make_unique<SUNLinSolSPBCGS>(xB);
                                                         ^
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:331:25: error: 'make_unique'
is not a member of 'std'
         linearSolverB = std::make_unique<SUNLinSolSPTFQMR>(xB);
                         ^~~
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:331:58: error: expected
primary-expression before '>' token
         linearSolverB = std::make_unique<SUNLinSolSPTFQMR>(xB);
                                                          ^
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:339:25: error: 'make_unique'
is not a member of 'std'
         linearSolverB = std::make_unique<SUNLinSolKLU>(
                         ^~~
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:339:54: error: expected
primary-expression before '>' token
         linearSolverB = std::make_unique<SUNLinSolKLU>(
                                                      ^
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp: In member function 'void
amici::Solver::initializeNonLinearSolverB(int) const':
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:364:13: error: 'make_unique'
is not a member of 'std'
             std::make_unique<SUNNonLinSolNewton>(xB.getNVector());
             ^~~
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:364:48: error: expected
primary-expression before '>' token
             std::make_unique<SUNNonLinSolNewton>(xB.getNVector());
                                                ^
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:368:13: error: 'make_unique'
is not a member of 'std'
             std::make_unique<SUNNonLinSolFixedPoint>(xB.getNVector());
             ^~~
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:368:52: error: expected
primary-expression before '>' token
             std::make_unique<SUNNonLinSolFixedPoint>(xB.getNVector());
                                                    ^
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp: In member function 'void
amici::Solver::initializeNonLinearSolverSens(const amici::Model*) const':
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:812:35: error: 'make_unique'
is not a member of 'std'
             nonLinearSolverSens = std::make_unique<SUNNonLinSolNewton>(
                                   ^~~
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:812:70: error: expected
primary-expression before '>' token
             nonLinearSolverSens = std::make_unique<SUNNonLinSolNewton>(
                                                                      ^
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:817:17: error: 'make_unique'
is not a member of 'std'
                 std::make_unique<SUNNonLinSolNewton>(x.getNVector());
                 ^~~
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:817:52: error: expected
primary-expression before '>' token
                 std::make_unique<SUNNonLinSolNewton>(x.getNVector());
                                                    ^
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:828:35: error: 'make_unique'
is not a member of 'std'
             nonLinearSolverSens = std::make_unique<SUNNonLinSolFixedPoint>(
                                   ^~~
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:828:74: error: expected
primary-expression before '>' token
             nonLinearSolverSens = std::make_unique<SUNNonLinSolFixedPoint>(
                                                                          ^
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:833:17: error: 'make_unique'
is not a member of 'std'
                 std::make_unique<SUNNonLinSolFixedPoint>(x.getNVector());
                 ^~~
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp:833:56: error: expected
primary-expression before '>' token
                 std::make_unique<SUNNonLinSolFixedPoint>(x.getNVector());
                                                        ^


Error in amimodel.compileAndLinkModel>compileAmiciBase (line 209)
        eval(['mex ' DEBUG COPT ' -c -outdir "' objectFolder '" ' ...

Error in amimodel.compileAndLinkModel (line 72)
    [objectStrAmici] = compileAmiciBase(amiciRootPath, objectFolder, objectFileSuffix, includesstr, DEBUG, COPT);

Error in compileMexFile (line 6)
amimodel.compileAndLinkModel(modelName, '', [], [], [], []);
 
>> 
```

- I repeated the procedure, using v0.10.18 instead of the latest AMICI version, but got the same error.

**Comment by dweindl** [comment]
Yeah, that slipped in very recently. @FFroehlich fixed it already on branch `develop`. We will create a new release soon. Sorry for that.

If you check out `develop` in your second last step, that should be gone.

**Comment by FFroehlich** [comment]
> If you check out `develop` in your second last step, that should be gone.

Alternatively you can install 0.10.17 via `pip3 install amici==0.10.17` or manually apply the following changes: https://github.com/ICB-DCM/AMICI/pull/953/commits/e43c02360a0081b65a32cf5b6c62186c24a65c3a

**Comment by paulflang** [comment]
@dweindl : Thanks, compiling worked now. Unfortunately, the following problem persisted in line 224 of the `simulate_...` function:

> `sol = ami_G2M_copasi_init_pert_Ob(tout,theta(1:27),kappa(1:3),options_ami,plist,xscale,init,data);` returns `sol.status = -1` and `sol.llh = NaN`.

Rerunning my `sbml2ami_mex.py` script with the develop version did not fix it either.

@FFroehlich : Thanks, I'll give it a try now.

**Comment by FFroehlich** [comment]
> @dweindl : Thanks, compiling worked now. Unfortunately, the following problem persisted in line 224 of the `simulate_...` function:
> 
> > `sol = ami_G2M_copasi_init_pert_Ob(tout,theta(1:27),kappa(1:3),options_ami,plist,xscale,init,data);` returns `sol.status = -1` and `sol.llh = NaN`.
> 

mind that `sol.status < 0` may also simply indicate an integration failure. Try simulating at your nominal parameter values and see whether the results look as expected.

**Comment by paulflang** [comment]
@FFroehlich : Unfortunately, I still get `sol.status = -1`.

**Comment by paulflang** [comment]
Just that I understand it correctly:
If I have 30 parameters in my sbml file, three of which I define as `constantParameters` in my sbml2amici.py script, then `theta` should have 27 dimensions and `kappa` 3. Is this right?
Cause things worked before I started to introduce these extra three parameters to simulate various experimental conditions.

**Comment by FFroehlich** [comment]
> Just that I understand it correctly:
> If I have 30 parameters in my sbml file, three of which I define as `constantParameters` in my sbml2amici.py script, then `theta` should have 27 dimensions and `kappa` 3. Is this right?
> Cause things worked before I started to introduce these extra three parameters to simulate various experimental conditions.

Yes, that is correct.

**Comment by paulflang** [comment]
OK. I just figured out what the problem was: the auto generated `simulate_...` file does not compute the exponential of theta. I added a line to do that and it seems to work now.
@FFroehlich and @dweindl  : thanks for pointing out that the problem may only indicate an integration failure, and that I need to use the develop version for the last step.

**Comment by FFroehlich** [comment]
> OK. I just figured out what the problem was: the auto generated `simulate_...` file does not compute the exponential of theta. I added a line to do that and it seems to work now.
> @FFroehlich and @dweindl : thanks for pointing out that the problem may only indicate an integration failure, and that I need to use the develop version for the last step.

Hey @paulflang, yeah thats a common error that we also still run into. The reason why the model  expects linear model parameters is because you specified the default parameter scale to be `'lin'` in 
```
amimodel.generateMatlabWrapper(12, 2, 27, 3, 0, 0, [], ...
            ['simulate_' modelName '.m'], modelName, 'lin', 1, 1);
```
In order to obtain correct gradients, you should use the amici provided interface to set the parameter scale. You can either do this at compile time by changing the above `'lin'` to a `'log'` or at runtime by setting amioptions.pscale (this allows control over individual parameters to be in lin/log scale, see respective documentation). You can see that this is a "recent" addition to amici as in the supplement of the paper we had to compile individual models and likelihood functions for lin/log parameterization, which is now no longer necessary.

Hope this helps.

**Comment by FFroehlich** [comment]
On a related not, you may have noticed that setting up parameter estimation is a quite an error-prone process so you may want to check out https://github.com/icb-dcm/pypesto and https://github.com/ICB-DCM/PEtab which substantially simplify the setup procedure. Currently that setup, as far as I know, doesn't feature the enhanced scatter search routine, but supports multistart optimization which generally has similar performance.

**Comment by paulflang** [comment]
@FFroehlich , thank you for all that advice. For now, I will just set `lin` to `log` at compile time. In the future, I may experiment with setting initial condition parameters to `lin`.
Thank you also for pointing me to pypesto an PEtab. Certainly good to be aware of them, especially when I run into problems in future.
