### ISSUE TITLE
AttributeError: module 'amici' has no attribute 'Model'

### ISSUE THREAD

**Issue by fbergmann** [ICB-DCM/AMICI#954]
I'm having an issue with using amici (develop) using python 3.7. The issue is with the return type declaration: 

```
~/AMICI/python/sdist/amici/petab_import.py in <module>
    221         model_name: str = None,
    222         force_compile: bool = False,
--> 223         **kwargs) -> amici.Model:
    224     """
    225     Import model from petab problem.

AttributeError: module 'amici' has no attribute 'Model'
```

This is called from the pyPESTO petab import with the line: 

```
from amici.petab_import import import_model
```

**Comment by fbergmann** [comment]
I've tried just running the example: 

```
https://github.com/ICB-DCM/AMICI/tree/develop/python/examples/example_presimulation
```

I think something happened during the SWIG step, but that one also failed in the container. given the console warning: 

```
swig/python detected a memory leak of type 'std::unique_ptr< amici::Model > *', no destructor found.
swig/python detected a memory leak of type 'std::unique_ptr< amici::Model > *', no destructor found.
```
it could be that something went wrong with the swig stage of things. Which would also explain the other error message.

**Comment by LeonardSchmiester** [comment]
I had a similar issue with AMICI 0.10.18. Somehow reinstalling AMICI worked for me.

**Comment by fbergmann** [comment]
Reinstalling does not solve the issue ... to reproduce run the attached file with: 

`docker build . -t fbergmann/pypesto-x64`

it fails for me with: 


```
_________ ERROR collecting tests/benchmark-models/test_petab_model.py __________
tests/benchmark-models/test_petab_model.py:16: in <module>
    from amici.petab_objective import (simulate_petab, rdatas_to_measurement_df,
python/sdist/amici/petab_objective.py:40: in <module>
    log_level: int = logging.WARNING
E   AttributeError: module 'amici' has no attribute 'Model'
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
```

[Dockerfile.txt](https://github.com/ICB-DCM/AMICI/files/4192951/Dockerfile.txt)

**Comment by FFroehlich** [comment]
I agree, this sounds like a swig issue. 

Can you try to add 
```
RUN ln -sf /usr/bin/swig3.0 /usr/bin/swig
```
to your dockerfile?

**Comment by FFroehlich** [comment]
@dweindl is there any chance we can get rid of https://github.com/ICB-DCM/AMICI/blob/fcd0a4d3d329dac53d27de6a17dc5b314d1125c1/python/amici/__init__.py#L89 ?

That except is a constant source of pain and suffering, i.e., error messages not being shown when they should).

**Comment by FFroehlich** [comment]
@dweindl also any idea why https://github.com/ICB-DCM/AMICI/blob/76162dfc09d74d439939ab92eac7a2f7b80f0873/python/sdist/amici/swig.py#L41didn't catch this. Was about to implement it and then found that we already have a check in place which apparently isn't working.

**Comment by dweindl** [comment]
> @dweindl is there any chance we can get rid of
> 
> https://github.com/ICB-DCM/AMICI/blob/fcd0a4d3d329dac53d27de6a17dc5b314d1125c1/python/amici/__init__.py#L89
> ?
> 
> That except is a constant source of pain and suffering, i.e., error messages not being shown when they should.

I have the same feeling. It will require a bit of fiddling. The problem is, that some files we want to use from the installed package as well as for creating the source distribution before installing. Need to check to best handle...

> @dweindl also any idea why https://github.com/ICB-DCM/AMICI/blob/76162dfc09d74d439939ab92eac7a2f7b80f0873/python/sdist/amici/swig.py#L41didn't catch this. Was about to implement it and then found that we already have a check in place which apparently isn't working.

Not sure. Would have to see detailed output.

@fbergmann : SWIG not being there would be one cause. Also, it feels like the recent PEtab update which brought in libcombine  can cause some trouble. I didn't fully understand what's going on, but there is some interference of different SWIGGED-libraries if they export the same classes (despite being in different python modules). We stumbled across that with libsbml and amici a while ago. But it is somewhat hard to reproduce.

**Comment by dweindl** [comment]
> @dweindl also any idea why https://github.com/ICB-DCM/AMICI/blob/76162dfc09d74d439939ab92eac7a2f7b80f0873/python/sdist/amici/swig.py#L41didn't catch this. Was about to implement it and then found that we already have a check in place which apparently isn't working.

SWIG is present and works (tested with the provided Dockerfile). It's a different problem there.

**Comment by dweindl** [comment]
There is some linking trouble with HDF5.

> ImportError: /home/jovyan/AMICI/python/sdist/amici/_amici.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK2H58CommonFG13createDataSetERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS_8DataTypeERKNS_9DataSpaceERKNS_17DSetCreatPropListE

Also occurred for @LeonardSchmiester . Trying to find out what's going wrong there.

**Comment by dweindl** [comment]
We are compiling using system hdf5 headers, the extension is linked against conda hdf5 libraries.

**Comment by dweindl** [comment]
@fbergmann : should work with branch `fix_954_import_errors`

**Comment by mhhoog** [comment]
> I'm having an issue with using amici (develop) using python 3.7. The issue is with the return type declaration:
> 
> ```
> ~/AMICI/python/sdist/amici/petab_import.py in <module>
>     221         model_name: str = None,
>     222         force_compile: bool = False,
> --> 223         **kwargs) -> amici.Model:
>     224     """
>     225     Import model from petab problem.
> 
> AttributeError: module 'amici' has no attribute 'Model'
> ```
> 
> This is called from the pyPESTO petab import with the line:
> 
> ```
> from amici.petab_import import import_model
> ```

For me the same error occurs importing pypesto in python (spyder environment)
`import pypesto`

`Traceback (most recent call last):

  File "<ipython-input-49-003e1855ec7e>", line 1, in <module>
    import pypesto

  File "c:\users\s155508\src\pypesto\pypesto\__init__.py", line 10, in <module>
    from .objective import (ObjectiveOptions,

  File "c:\users\s155508\src\pypesto\pypesto\objective\__init__.py", line 15, in <module>
    from .petab_import import PetabImporter

  File "c:\users\s155508\src\pypesto\pypesto\objective\petab_import.py", line 14, in <module>
    from amici.petab_import import import_model

  File "C:\Users\s155508\AppData\Local\Continuum\anaconda3\lib\site-packages\amici\petab_import.py", line 223, in <module>
    **kwargs) -> amici.Model:

AttributeError: module 'amici' has no attribute 'Model'`

I've got the amici master installed and the develop branches of pyPESTO and PEtab.
Furthermore 'swig' gets recognised by my command terminal (windows)

**Comment by dweindl** [comment]
@mhhoog: what is the output of `from amici import _amici; print(_amici)`?

**Comment by mhhoog** [comment]
> from amici import _amici; print(_amici

It can't find it:

```
Traceback (most recent call last):

  File "<ipython-input-2-71f10b6da72a>", line 1, in <module>
    from amici import _amici

ImportError: DLL load failed: The specified module could not be found.
```

**Comment by dweindl** [comment]
> It can't find it

Okay, that means something went wrong already during amici installation. Could you please remove and re-install amici with `--verbose`, and post the full installation output in a new issue?
