### ISSUE TITLE
petab_import fails due to filesystem/import delay?

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#965]
Not sure about the exact reason, but I find that https://github.com/ICB-DCM/AMICI/blob/16e3d762a94a35d21825f904d9d4381f82d117ab/python/amici/petab_import.py#L288 is sometimes arbitrarily failing. Might be due to filesystem delay?

**Comment by dweindl** [comment]
Can you provide some stack trace?

**Comment by FFroehlich** [comment]
```
Traceback (most recent call last):
  File "build_model.py", line 32, in <module>
    force_compile=True,
  File "/Users/ffroehlich/Documents/HMS/cell_cycle/cell_cycle_ode/petab_problem/venv/src/amici/python/sdist/amici/petab_import.py", line 288, in import_petab_problem
    model = model_module.getModel()
AttributeError: module 'cell_cycle_no_M_washout_ridge' has no attribute 'getModel'
    [Thu Feb 20 16:31:33 2020]
    Error in rule model:
        jobid: 56
        output: models/cell_cycle_no_M_washout_ridge/cell_cycle_no_M_washout_ridge/cell_cycle_no_M_washout_ridge.py
```

**Comment by FFroehlich** [comment]
it consistently succeeds when calling the respective script directly but will consistently fail on the first attempt when called from snakemake. Second attempt always goes through.

amici.petab_import.import_petab_problem is called with `force_compile=True` and `getModel` on the module  fails although retrospective inspection suggests that the dynamic library was indeed created.

**Comment by dweindl** [comment]
Are you providing `model_output_dir`?

It may be that a relative path is added to `sys.path` and that something other than the actual model package is imported. This would be plausible given your rule output `cell_cycle_no_M_washout_ridge/cell_cycle_no_M_washout_ridge` (parent directory is imported).

**Comment by FFroehlich** [comment]
`model_output_dir` is provided as absolute path

**Comment by dweindl** [comment]
:-/ 

My guess would still be that it is importing the wrong (parent) directory. 

Maybe a `print(model_module)` in 
>  File "/Users/ffroehlich/Documents/HMS/cell_cycle/cell_cycle_ode/petab_problem/venv/src/amici/python/sdist/amici/petab_import.py", line 288, in import_petab_problem

will be more informative

**Comment by FFroehlich** [comment]
Added 
```
    print(model_module)
    print(model_module.__file__)
    print(dir(model_module))
```
to petab_import.py

On the first go:

<module 'cell_cycle_no_M_washout_ridge' (namespace)>
None
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']

On the second go:

<module 'cell_cycle_no_M_washout_ridge' from '/Users/ffroehlich/Documents/HMS/cell_cycle/cell_cycle_ode/petab_problem/models/cell_cycle_no_M_washout_ridge/cell_cycle_no_M_washout_ridge/__init__.py'>
/Users/ffroehlich/Documents/HMS/cell_cycle/cell_cycle_ode/petab_problem/models/cell_cycle_no_M_washout_ridge/cell_cycle_no_M_washout_ridge/__init__.py
['SWIG_PyInstanceMethod_New', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_cell_cycle_no_M_washout_ridge', 'amici', 'getModel']

**Comment by FFroehlich** [comment]
`print(os.listdir(os.path.join(model_output_dir, model_name)))`

returns 

`['__init__.py', 'cell_cycle_no_M_washout_ridge.py', '_cell_cycle_no_M_washout_ridge.cpython-37m-darwin.so']`

in both cases

**Comment by dweindl** [comment]
Feel free to try again with branch `fix_965`.

**Comment by FFroehlich** [comment]
Yep, works! Thanks.
