### ISSUE TITLE
Setup script exited with error: SandboxViolation

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#985]
setup.py:
```
setup(name='test',
      version='0.0.1',
      description='test',
      author='',
      packages=['test],
      install_requires=[
            'amici>=0.10.19',
      ],
      python_requires='>=3.6',
      zip_safe=False)
```

running `python setup.py install` produces

> Running amici-0.10.19/setup.py -q bdist_egg --dist-dir /var/folders/jk/dwv8fvns5q58ht4z1x184jb80000gp/T/easy_install-4krftnty/amici-0.10.19/egg-dist-tmp-huvqovhj
hdf5.h found in /usr/local/include
libhdf5.a found in /usr/local/lib
HDF5 library found. Building AMICI with HDF5 support.
error: Setup script exited with error: SandboxViolation: open('/Users/ffroehlich/Documents/HMS/melanoma/erk_pulses_calibration/venv/lib/python3.7/site-packages/test-easy-install-40180.write-test', 'w') {}

>The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

>This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.

**Comment by FFroehlich** [comment]
can be circumvented by manually installing amici via `pip install amici`, but it think it should be possible to specify amici as dependency and have it autoinstall in a setup.py

**Comment by dweindl** [comment]
Also ran into that a couple of times. Would be good to fix. Need to disable easy-install in setup.py somehow. Probably requires some deep-dive into setuptools/distutils again.

**Comment by dweindl** [comment]
Does this still happen with setuptools >=42? Can't reproduce it currently. https://github.com/numpy/numpy/issues/14873#issuecomment-557832035

**Comment by FFroehlich** [comment]
with python3.7 and setuptools I get a shitton of compilation warnings/errors while installing pandas numpy and astropy and can still reproduce the error above

**Comment by dweindl** [comment]
I may have found the problem. Can you test with branch `feature_881_parallel_compile_model`? I can't reproduce the error locally.

**Comment by FFroehlich** [comment]
can't get easy_install to check out custom branches
```
install_requires=[
            'amici@git+https://github.com/ICB-DCM/AMICI@feature_881_parallel_compile_model#egg=amici&subdirectory=python/sdist',
      ],
```
will still install the release tar from `https://pypi.org/simple/amici/`

**Comment by FFroehlich** [comment]
this is indeed fixed on master now
