### ISSUE TITLE
Make more model parameters specifiable at simulation time

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#99]
the parameter transformation could be set at simulation time but can currently only be set at compilation time, which is an unnecessary limitation.

**Comment by dweindl** [comment]
If the parameter transformation can be set at compile time, would you still allow for specifiying `amimodel::param`? Would be good for backward compatibility, but would be cleaner if we remove it.

**Comment by FFroehlich** [comment]
I would use amimodel::param as specification of the default value.
