### ISSUE TITLE
Make flux vector available in ReturnData

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#990]
Would be helpful. Is already computed, but so far not exposed.

Will again increase memory requirements. If that is a concern, it could be addressed by introducing an option to specify which quantities are to be retained.

Anything against adding that to ReturnData?

**Comment by FFroehlich** [comment]
I would argue to make values of `w` available. I am planning to start working on these memory requirements soon, should then be possible to request these values ad hoc, so don't worry about that now.

**Comment by FFroehlich** [comment]
Ideally goes hand in hand with introducing something like `getExpressionNames()`/`getExpressionIds()` in model which provides names for those variables for easier indexing.

**Comment by dweindl** [comment]
Sounds good. Until a more general way is implemented, i would add `w` to ReturnData. Can then be dropped as soon as alternatives exist.
